### ISSUE TITLE
Possibility not to add `getStaticProps` on each page

### ISSUE THREAD

**Issue by oceandrama** [i18next/next-i18next#1215]
Now to migrate to v8 of `next-i18next`  it's necessary to add `getStaticProps` or `getServerSideProps` on each page. It may take a long time if you have a lot of pages. After [this PR](https://github.com/vercel/next.js/pull/21930) merged to `Next.js` is it possible to load all translations in `getInitialProps` in the `_app` component?

**Comment by isaachinman** [comment]
@oceandrama That is not something that `next-i18next` currently supports, but I suppose it would be possible in theory. The whole idea behind loading translations via `getStaticProps` or `getServerSideProps` is that each page will have its own translation dependencies, and we shouldn't send _all_ translations to _all_ pages.

**Comment by oceandrama** [comment]
@isaachinman I think this is fine, because even now you can pass `undefined` as an array of namespaces to `serverSideTranslations` function and this will work the same - all translations will send to the page

**Comment by isaachinman** [comment]
@oceandrama If you want to work on a PR, I would be OK with adding that type of functionality. However, it will never be advertised as the main installation/approach for `next-i18next`.

**Comment by stophecom** [comment]
@oceandrama I think you got a valid point - are you planning to do a PR? 😄

**Comment by aethiss** [comment]
agree, super valid point.

**Comment by ZahidSaeed7** [comment]
@oceandrama I've implemented the following example:
https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js

Every time, I add a new translation to one of my files, it is NOT loaded automatically until I quit the server and load it again. Is this happening to you as well?

Any workaround for this?

**Comment by rodilo** [comment]
Is there any progress on this one? Right now build times are crazy high with current implementation.

**Comment by isaachinman** [comment]
@rodilo Why do you believe `next-i18next` is affecting your build times?

**Comment by rodilo** [comment]
@isaachinman we had to move from `next export` when we implemented `next-i18next`  into our app, so building became so slow on vercel, and I thought it had something to do with `getStaticProps` on each page.
But after some debugging, I found out that it was one of the imports from `@material-ui/icons` that was causing this ( don't know why).
After we removed that, build time went from ~25 minutes to ~8 minutes.

**Comment by isaachinman** [comment]
> I believe a good in-between would be to allow the developer to specify an array of dependencies that should be served on all pages.

That is the entire idea behind `defaultNS`, and the `common` namespace in the [example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple).

**Comment by Naumov1889** [comment]
Checkout this lib [next-translate](https://github.com/vinissimus/next-translate)

You can configure where and what translations are loaded like this: 
```
{
  "pages": {
    "*": ["common"],
    "/": ["home"],
    "/cart": ["cart"],
    "/content/[slug]": ["content"],
    "rgx:^/account": ["account"]
  }
  // rest of config here...
}
```

**Comment by oceandrama** [comment]
@Naumov1889 It's a great library, but unfortunately it doesn't expose global `i18n` object, which is very usefull for me
We had small conversation here https://github.com/vinissimus/next-translate/discussions/600#discussioncomment-713865

**Comment by chrillep** [comment]
> I think what you're _really_ asking for, is for `_app` to support `getStaticProps`/`getServerSideProps`, which is a long-standing request: [vercel/next.js#10949](https://github.com/vercel/next.js/discussions/10949)

so until then if u want next-i18next with
https://nextjs.org/docs/advanced-features/custom-app

- Persisting layout between page changes
- Keeping state when navigating pages
- Custom error handling using componentDidCatch
- Inject additional data into pages
- [Add global CSS](https://nextjs.org/docs/basic-features/built-in-css-support#adding-a-global-stylesheet)

your just stuck between a rock (nextjs) and hard place (next-i18next) :) 

if im understanding this right @isaachinman ?

**Comment by isaachinman** [comment]
@chrillep No, that is not the case at all. Just put whatever persistent logic you want _one level higher_ than `appWithTranslation`.

**Comment by chrillep** [comment]
> @chrillep No, that is not the case at all. Just put whatever persistent logic you want _one level higher_ than `appWithTranslation`.

sry i meant 

```
// Only uncomment this method if you have blocking data requirements for
// every single page in your application. This disables the ability to
// perform automatic static optimization, causing every page in your app to
// be server-side rendered.
//
// MyApp.getInitialProps = async (appContext) => {
//   // calls page's `getInitialProps` and fills `appProps.pageProps`
//   const appProps = await App.getInitialProps(appContext);
//
//   return { ...appProps }
// }
```

**Comment by Tockra** [comment]
I think I'm running into the same problem.
Without adding 
```code
import { GetStaticProps } from 'next/types';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
export const getStaticProps: GetStaticProps = async ({ locale }) => {
    const translationsProps = await serverSideTranslations(locale ?? 'de', [
        // `i18next` namespace, matches translations file names
        // & `defaultNS` in `next-i18next.config.js`
        'default',
    ]);

    return {
        props: {
            // These props are used by `appWithTranslation` in `_app.tsx`
            // to set up a React context which holds translations
            ...translationsProps,
        },
    };
};
```

to every page, my i18n translation does not work. It is very annoying, because it is simple stuff I'm doing there and it would be great to configure that somewhere on a global place without have boilerplate code in every .tsx file.

**Comment by rmartins0** [comment]
What's the state of this problem? Is there today a way to not have to include that getStaticProps on every single page? So only do it once and have it work everywhere.
