### ISSUE TITLE
Translations not loaded after revalidate and when `ns` is passed 

### ISSUE THREAD

**Issue by martinratinaud** [i18next/next-i18next#1577]
I created a repo with the error reproduced as it is quite of a tricky one 

https://github.com/martinratinaud/next-i18next-revalidate-error

## Reproduce failing config
on branch `develop` 
Go to https://next-i18next-revalidate-error-8i5jgt2jl-martinratinaud.vercel.app/fr/_debug/1  (or replace 1 with another number between 1 and 300) -> content in french
Refresh -> content in default language with initialI18nStore empty

`develop` has one more commit than `main` which sets up `ns:["common"]` in the i18n config https://github.com/martinratinaud/next-i18next-revalidate-error/commits/develop

## Reproduce working config
on branch `main` -> everything works fine
Goto https://next-i18next-revalidate-error.vercel.app/fr/_debug/1 -> content in french
Refresh -> content in french

## Environment
This occurs with v10.0.1 when deploying on vercel

I hope it'll be enough to understand this bug because I've been spending some time on this now

**Comment by frontshift** [comment]
Having the same issue. Took me quite a while to realise that it's something to do with revalidation.

**Comment by isaachinman** [comment]
@martinratinaud @frontshift It's critical to note that this error _only_ occurs on Vercel deploys and is not reproducible locally whatsoever, correct?

I suspect this has to do with #1448 (and many others). Let me know if that helps.

**Comment by frontshift** [comment]
@isaachinman yes, Vercel only. And your suggestion to set the resolved `localePath` has fixed it for me. Thanks mate!

**Comment by Baoufa** [comment]
I am encoutering the same error on next 12.2.4 It is was tricky to understand that the problem was coming from the revalidation

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next#reloading-resources-in-development
