### ISSUE TITLE
[Feature request] update the logic in createConfig to not check locales via the fs when they are covered with a fallback

### ISSUE THREAD

**Issue by Sin1tar** [i18next/next-i18next#1652]
## Is your feature request related to a problem? Please describe.
https://github.com/isaachinman/next-i18next/discussions/1649

it would be really great to be able to define multiple routes that will have a translation from the same entry point.

so if we define in next-i18next.config.js
```
module.exports = {
  fallbackLng: {
    'en-CA': ['en'],
    'en-DE': ['en'],
    'it-CA': ['it'],
    'it-DE': ['it'],
    'default': ['en'],
  },
  i18n: {
    defaultLocale: 'en',
    locales: [
      'en-CA',
      'en-DE',
      'en',
      'it-CA',
      'it-DE',
      'it',
    ],
  },
}
```
then these routes will get translation from the one entry point instead of hard fs cover:
/en-CA (now: public\locales\en-CA) (need: public\locales\en)
/en-DE (now: public\locales\en-DE) (need: public\locales\en)
/en

/it-CA (now: public\locales\it-CA) (need: public\locales\it)
/it-DE (now: public\locales\it-CA) (need: public\locales\it)
/it

Thank you

**Comment by isaachinman** [comment]
Fix should be handled as described [here](https://github.com/isaachinman/next-i18next/discussions/1649#discussioncomment-2045156).

PRs would be very welcome!
