### ISSUE TITLE
Custom localeStructure not working and searching in default dir

### ISSUE THREAD

**Issue by rKrivko** [i18next/next-i18next#1655]
## Describe the bug
After adding the lcoalStructure wth custom structure, it still tries to search into default dir.

Maybe i oversaw something in the Docs. But if i use the default paths it works fine.

## Occurs in next-i18next version
10.2.0

## Steps to reproduce
Pretty much just copy the config and re-create the folder structure.

## Expected behaviour
Should look into /public/translations/{ns}/{lng}.json for translation file and not in default path.

## Screenshots
**Error**
![image](https://user-images.githubusercontent.com/62034582/151714103-f168bc88-8d1e-4f0b-adf1-856e2adbc2d9.png)

**next-i18next,config.js**
![image](https://user-images.githubusercontent.com/62034582/151713869-b30eafee-c954-4b40-af88-0929969fbebe.png)

**next.config.js**
![image](https://user-images.githubusercontent.com/62034582/151713879-30d52a92-be79-4ed0-b8f0-cd77a4e4617a.png)

**Component**
![image](https://user-images.githubusercontent.com/62034582/151713890-bea9c91f-17ec-4a29-9447-89e64e1d612f.png)

**Translation Folder Structure**
![image](https://user-images.githubusercontent.com/62034582/151713904-0ab28811-12e2-4bcd-beab-dae6c2b8dc89.png)

## OS (please complete the following information)
 - Device: WIN 10
 - Browser: Chrome 97.0.4692.99

**Comment by isaachinman** [comment]
Can you provide a reproducible repository?

**Comment by rKrivko** [comment]
> Can you provide a reproducible repository?

Here: https://github.com/rKrivko/nexti18bug

**Comment by isaachinman** [comment]
There is no `public` directory in that repo at all.

**Comment by rKrivko** [comment]
> There is no `public` directory in that repo at all.

My bad :( just pushed.

**Comment by isaachinman** [comment]
It's [this line](https://github.com/isaachinman/next-i18next/blob/master/src/config/createConfig.ts#L89) which is causing the problem.

You may be able to collaborate with #1593 as the work is very related. Otherwise this can be fixed in a standalone PR.
