### ISSUE TITLE
Support for 'default' locale

### ISSUE THREAD

**Issue by nhac-lly** [i18next/next-i18next#1679]
https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale
as NextJS team suggest, it is better to use 'default' that fallback to actual main language for some case. 
One of those case is to have locale routing always on URL. 

For now to use it I need to create a local file for 'default'.
Can we somehow map it to 'en'?

**Comment by isaachinman** [comment]
Sorry, I don't think I understand your question. Can you explain further?

**Comment by nhac-lly** [comment]
`module.exports = {
  i18n: {
    locales: ['default', 'en', 'de', 'fr'],
    defaultLocale: 'default',
    localeDetection: false,
  },
  trailingSlash: true,
}`
I meant when using this config, you need to also create a public/locale/default/common.json for the 'default' locale, but 'default' is just to fallback to the actual language like 'en'. 
In other word is to force 'default' to not needing a locale json for it as it is not used.

**Comment by isaachinman** [comment]
Ah OK, got it. I'm not convinced that using a non-standard "locale" like `default` just to manipulate routing is a good idea in the first place. It speaks to the lack of configurability on the NextJs routing side of things.

That being said, I would be fine with merging support for this, as it is indeed in the official NextJs docs, for better or worse. We would need to update [createConfig](https://github.com/isaachinman/next-i18next/blob/master/src/config/createConfig.ts) to ignore non-standard locales. PRs welcome.

**Comment by fcandi** [comment]
Thanks, I am in the same boat, using the "default" language as recommended in the official docs, forwarding "/" to "/some_locale" depending of the browsers  language.

I not get an ENOENT error loading the non existing default language. Is there a simple preliminary fix for now?

Andreas

**Comment by santyas** [comment]
Hey @fcandi @nhac-lly 

I've tested it, first you have to create default folder inside /public/locales/ with a common.js file inside (I think empty works, if it crash duplicate common.js file like your prefered locale default).

Then update your getStaticsProps func:
```
export const getStaticProps: GetStaticProps = async ({locale}) => {
  let locales = locale as string
  console.log(`Locale: ${locales}`)

  return {
    props: {
      ...(await serverSideTranslations(locales == 'default' ? 'ar' : locales, ['common'])),
    },
  };
}
```
I'm using TS so I had to edit it a little bit.

Keep in mind you must have the file configured as specified in the nextjs  i18n docs.

CC @isaachinman

**Comment by adrai** [comment]
fyi: to validate the languges something like this (probably needs also special handling for "default") could be helpful:

```js
const validateCode = (value) => {
  const pass = value.match(/^[a-z]{2,5}(?:-?[a-zA-Z\d]*(?:-[a-zA-Z\d]*)?(?:-x-[a-zA-Z-\d]*)*)?$/) // allow sv-SE-x-trygg-sbo (private lng code)
  if (!pass || value.indexOf('--') > -1) throw new Error(`Language code ${value} not valid!`)
}
```

**Comment by adrai** [comment]
Support for [Prefixing the Default Locale](https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale) will be included in the next release.

**Comment by adrai** [comment]
included in v11.1.0

**Comment by deltasierra96** [comment]
> included in v11.1.1

Any documentation on this feature or is it as before?

**Comment by adrai** [comment]
there is no extra config needed. it just ignores the language "default" when configured in the i18n config: https://github.com/i18next/next-i18next/commit/f9a653966cd52fbb50bcbbd545369dbad50b489b

**Comment by deltasierra96** [comment]
> there is no extra config needed. it just ignores the language "default" when configured in the i18n config: [f9a6539#diff-28136a2e354d423cb0c0191cef90624f802ee7921bf0aacbb9bfd3e5f2b1f501R226](https://github.com/i18next/next-i18next/commit/f9a653966cd52fbb50bcbbd545369dbad50b489b#diff-28136a2e354d423cb0c0191cef90624f802ee7921bf0aacbb9bfd3e5f2b1f501R226)

Awesome. Thanks for the update, Adraino!
