### ISSUE TITLE
Type error: Type 'TFunctionResult' is not assignable to type 'ReactNode'.

### ISSUE THREAD

**Issue by HT-Moh** [i18next/next-i18next#1795]
## Describe the bug
You must provide a clear and concise description of what the bug is.

## Occurs in next-i18next version  
11.0.0

## Steps to reproduce
update to react 18 

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
![image](https://user-images.githubusercontent.com/34759569/163270968-dfbc56b8-c33a-48e7-ad13-361e935e3d7c.png)

## Additional context

This seems to be due to the following two issues
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

## Solution 
pumping react-i18next to the last version which contain the [commit](https://github.com/i18next/react-i18next/commit/4aecf5c0ec277a4a8c20308fd22eef30b3b88713)

**Comment by HT-Moh** [comment]
Temporary solution add the following to package.json

``` 
"resolutions": {
    "react-i18next": ">=11.16.4"
  }
```

**Comment by azuken** [comment]
> "resolutions": {
>     "react-i18next": ">=11.16.4"
>   }

This is a workaround fix, will an update be available soon ?

**Comment by quertenmont** [comment]
I am having the same issue and the working around is indeed not working
![image](https://user-images.githubusercontent.com/4639944/166950312-05c3edee-8e4c-47f9-8e57-e1675bdd4a47.png)

**Comment by qjnz** [comment]
I have the same issue 

> I am having the same issue and the working around is indeed not working ![image](https://user-images.githubusercontent.com/4639944/166950312-05c3edee-8e4c-47f9-8e57-e1675bdd4a47.png)

I am having the same issue by using the latest package [react-i18next v11.16.8](https://github.com/i18next/react-i18next/releases/tag/v11.16.8)

**Comment by MouzamSadiq** [comment]
place "as string " to it . eg {t."dashboard.title,"dashboad")  as string}

**Comment by phankietit** [comment]
Fix by update rn i18next version: **[Here](https://changelogs.md/github/i18next/react-i18next/)**

**Comment by adriandmitroca** [comment]
Still broken in latest release (11.16.9): `Type 'TFunctionResult' is not assignable to type 'ReactNode'.`

**Comment by bedcoding** [comment]
I also had the same error when applying TypeScript in i18n.

```
Type 'TFunctionResult' is not assignable to type 'ReactNode'.
  Type 'object' is not assignable to type 'ReactNode'.
    Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, propsts(2322)
```

So I modified it as follows.
```
{t("base.content.no")}
=> t<string>("base.content.no")
```
![스크린샷 2022-05-30 오전 11 09 18](https://user-images.githubusercontent.com/33927558/170904689-1e1b4947-6d44-49c1-baae-23862e1e4cef.jpg)


or

```
{t("brand.button.management")}
=> {`${t("brand.button.management")}`}
```

**Comment by marcoXbresciani** [comment]
> {`${t("brand.button.management")}`}

This one is working for me.
* react-i18next ^11.17.1
* i18next ^21.6.16

**Comment by keremcanb** [comment]
I'm getting this error if it is only used like this:

`i18n.t('text.example')`

No problems with this:

`t('text.example')`

**Comment by Shackey666** [comment]
Hello, I still have this bug on my side too.

package.json:

peerDep: {
    "i18next": "^21.8.11",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^11.18.0",
}

devDependencies: {
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
}

**Comment by HT-Moh** [comment]
The other solution is to update all packages **to the last version** and remove the devDependencies entry, for me the following versions work
```
"react": "^18.2.0",
"react-dom": "^18.2.0",
```
```
 "@types/react": "^18.0.15",
 "@types/react-dom": "^18.0.6",
```
update all eslint and it's plugins
what works for me **last versions**
```
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-jsx-a11y": "^6.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.30.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-security": "^1.5.0",
    "eslint-plugin-simple-import-sort": "^7.0.0",
    "eslint-plugin-sonarjs": "^0.13.0",
    "eslint-plugin-unicorn": "^43.0.1",
```
to check the package that needs to be updated run `yarn outdated` 
I hope this helps.

**Comment by alessandraluzm** [comment]
for me what worked was to call like this: const { t }: { t: any } = useTranslation()

**Comment by sigespweb22** [comment]
> Correção por atualização rn i18next version: **[Aqui](https://changelogs.md/github/i18next/react-i18next/)**

It worked for me. Thanks

**Comment by Dam998** [comment]
you can do something like that too:

```typescript
export type i18translateType = {
  t: (key: string | TemplateStringsArray | (string | TemplateStringsArray)[], options?: string | TOptions<StringMap> | undefined) => string
}

const component = (props: ...) => {
  const { t }: i18translateType = useTranslation();
  ...
  
  return <div>
    ...
    <p>{t("text")}</p>
    ...
    <button>{t("dashboard")}</button>
  </div>
}

```

**Comment by adjustmentlayer** [comment]
updating typescript to ^4.8.3 helped me

**Comment by MarcelGeo** [comment]
If I am using withTranslation() HOC, fix in newest version is not available. Same error:

(property) placeholder?: ReactNode
Type 'TFunctionResult' is not assignable to type 'ReactNode'

**Comment by OnkelTem** [comment]
I don't quite understand what this mess is all about. Could the author provide an explanation?

Here is a mini-demo of the problem: [TypeScript Sandbox](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQGIFcB2BjGwKZwCGAzihjngQHICmAHvAL5wBmUEIcA5JgzAFpgARgAcfRtwBQoSLETksufIVKLKKgEq0iuOC3aceUHbiFiJMaVJgBPMLTioIEOAF5EUuHDwwANrQAXHDaujAAdKG41BAAJrRSTFJSrEpUhABGRFB0jAAUrC7BzhAAND7BaGkquTAAlJ7e3oUQ4b4B7j553AAKHLHAeu203HWJyakaBHBZUFEwBUVOLuUwlRTKBPMNCF5NLW3A-o4eC739g-DDo+PJUkA)

```ts
import { TFunction as TFunctionNext } from 'next-i18next'
import { TFunction as TFunctionReact } from 'react-i18next'

type Foo = {
  title: React.ReactNode
}

function barNext(foo: Foo, t: TFunctionNext) {
    foo.title = t('Prodict title') 
// ^^^^^^^
// ERROR:
//   Type 'TFunctionResult' is not assignable to type 'ReactNode'.
//      Type 'object' is not assignable to type 'ReactNode'.(2322)
}

function barReact(foo: Foo, t: TFunctionReact) {
    foo.title = t('Prodict title')
}

```

Conclusions:
1) ` TFunction` from `react-i18next` doesn't produce any problems.
2) ` TFunction` from `next-i18next` is the culprit.

Can it be just fixed?

Meanwhile, in such circumstances I would just change all `TFunction` imports to `react-i18next`

**Comment by OnkelTem** [comment]
@HT-Moh  I see this one is closed. Well, should I file a new report?

**Comment by ivansvlv** [comment]
I was just migrating the app to React 18 and latest TypeScript and faced the same issue.

```json
"dependencies" : {
    "i18next": "^22.0.1",
    "i18next-browser-languagedetector": "^6.1.8",
    "i18next-http-backend": "^1.4.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^12.0.0",
},
"devDependencies": {
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "@typescript-eslint/eslint-plugin": "^5.40.1",
    "@typescript-eslint/parser": "^5.40.1",
    "eslint": "^8.25.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "^4.6.0",
    "typescript": "^4.8.4",
}
```

```tsx
const { t } = useTranslation('footer');

            <div>
              <Link to="/terms-conditions">{t('links.terms-conditions')}</Link>
              <Link to="/privacy-policy">{t('links.privacy-policy')}</Link>
            </div>
```

This `t()` usage type error:

`Type 'DefaultTFuncReturn' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.ts(2322)
index.d.ts(47, 5): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & LinkProps & RefAttributes<HTMLAnchorElement>'`

However, I can see relevant type definitions that should allow this. Similar error is noticed with general JSX tags:

```tsx
  const { t } = useTranslation(['login', 'errors']);

        <LoginHeader>
          <h1 className={style.login__title}>{t('login:signin.title')}</h1>
          <p className={style.login__paragraph}>{t('login:signin.subtitle')}</p>
        </LoginHeader>
```

`Type 'DefaultTFuncReturn' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.ts(2322)
index.d.ts(47, 5): The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'`

I've already tried to remove `package-lock.json` and `node_modules` to have a clean install, but it didn't help.

**Comment by fitimbyttyqi** [comment]
> I was just migrating the app to React 18 and latest TypeScript and faced the same issue.
> 
> ```json
> "dependencies" : {
>     "i18next": "^22.0.1",
>     "i18next-browser-languagedetector": "^6.1.8",
>     "i18next-http-backend": "^1.4.4",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "react-i18next": "^12.0.0",
> },
> "devDependencies": {
>     "@types/react": "^18.0.21",
>     "@types/react-dom": "^18.0.6",
>     "@typescript-eslint/eslint-plugin": "^5.40.1",
>     "@typescript-eslint/parser": "^5.40.1",
>     "eslint": "^8.25.0",
>     "eslint-config-airbnb": "^19.0.4",
>     "eslint-config-prettier": "^8.5.0",
>     "eslint-plugin-import": "^2.26.0",
>     "eslint-plugin-jsx-a11y": "^6.6.1",
>     "eslint-plugin-react": "^7.31.10",
>     "eslint-plugin-react-hooks": "^4.6.0",
>     "typescript": "^4.8.4",
> }
> ```
> 
> ```tsx
> const { t } = useTranslation('footer');
> 
>             <div>
>               <Link to="/terms-conditions">{t('links.terms-conditions')}</Link>
>               <Link to="/privacy-policy">{t('links.privacy-policy')}</Link>
>             </div>
> ```
> 
> This `t()` usage type error:
> 
> `Type 'DefaultTFuncReturn' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.ts(2322) index.d.ts(47, 5): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & LinkProps & RefAttributes<HTMLAnchorElement>'`
> 
> However, I can see relevant type definitions that should allow this. Similar error is noticed with general JSX tags:
> 
> ```tsx
>   const { t } = useTranslation(['login', 'errors']);
> 
>         <LoginHeader>
>           <h1 className={style.login__title}>{t('login:signin.title')}</h1>
>           <p className={style.login__paragraph}>{t('login:signin.subtitle')}</p>
>         </LoginHeader>
> ```
> 
> `Type 'DefaultTFuncReturn' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.ts(2322) index.d.ts(47, 5): The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'`
> 
> I've already tried to remove `package-lock.json` and `node_modules` to have a clean install, but it didn't help.

I'm running into the same issue with the versions mentioned above, have you found any solutions yet ?

**Comment by ivansvlv** [comment]
@fitimbyttyqi thanks, that helped indeed. Version `^11.18.6` works fine.

**Comment by cjsilva-umich** [comment]
Would be great if this could be looked into so that version 12 could be used without this error

**Comment by imransilvake** [comment]
working for `^11.18.6`
problem with `^12.0.0`

**Comment by HT-Moh** [comment]
I reopened this issue as saw a lot of activity. 
An update from my side, now I am using the last version `"next-i18next": "^11.3.0",` I removed the `devDependencies` and `resolutions`, and I am using 
```
"@types/react": "^18.0.23",
"@types/react-dom": "^18.0.7",
```
```
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```
everything works.

**Comment by ben-lawlor-kaseya** [comment]
> I also had the same error when applying TypeScript in i18n.
> 
> ```
> Type 'TFunctionResult' is not assignable to type 'ReactNode'.
>   Type 'object' is not assignable to type 'ReactNode'.
>     Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, propsts(2322)
> ```
> 
> So I modified it as follows.
> 
> ```
> {t("base.content.no")}
> => {t<string>("base.content.no")}
> ```
> 
> ![스크린샷 2022-05-30 오전 11 09 18](https://user-images.githubusercontent.com/33927558/170904689-1e1b4947-6d44-49c1-baae-23862e1e4cef.jpg)
> 
> or
> 
> ```
> {t("brand.button.management")}
> => {`${t("brand.button.management")}`}
> ```


This works with react-i18next ^12.0.0

**Comment by Tautorn** [comment]
> working with `^11.18.6` problem with `^12.0.0`

It works for me. Thank you. 

I did update to version 12.0.0 and it generated the error. Was it necessary a downgrade version.

**Comment by imransilvake** [comment]
> > working with `^11.18.6` problem with `^12.0.0`
> 
> It works for me. Thank you.
> 
> I did update to version 12.0.0 and it generated the error. Was it necessary a downgrade version.

Yes until there is a standard fix from the team.

**Comment by pedrodurek** [comment]
This [PR](https://github.com/i18next/i18next/pull/1858) will fix that, there is only one small downside that I'll describe there.

**Comment by adrai** [comment]
can you try with i18next v22.0.3?

**Comment by ben-lawlor-kaseya** [comment]
> can you try with i18next v22.0.3?

Working with i18next v22.0.3 and react-i18next v12.0.0. Thank you!

**Comment by gHashTag** [comment]
the following versions work for me
```
"i18next": "22.0.4",
"react-i18next": "12.0.0",
```

**Comment by nick4fake** [comment]
@gHashTag I have same versions, it doesn't work

**Comment by adrai** [comment]
and with i18next v22.0.5?

**Comment by nick4fake** [comment]
@adrai Exactly the same error after updating to 22.0.5

**Comment by nick4fake** [comment]
@adrai I am really sorry, apparently I've had it cached. 22.0.5 works! Thanks

**Comment by EnvyIT** [comment]
@adrai this issues should be reopned. it still is a problem with:

    "i18next": "^22.0.6",
    "react": "18.2.0",
    "react-i18next": "^12.0.0",
    

Leads to TS error : `TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | undefined'.   Type 'null' is not assignable to type 'string | undefined'.`

**Comment by EnvyIT** [comment]
Well , you are right @adrai thanks for your fast response. Was this introduced in a specific version? I am curious because in `21.8.10` it is working perfectly fine.

**Comment by adrai** [comment]
> Well , you are right @adrai thanks for your fast response. Was this introduced in a specific version? I am curious because in `21.8.10` it is working perfectly fine.

Yes, in the last major v22

**Comment by kirillleogky** [comment]
```
"next": "^12.3.0",
"next-i18next": "^13.0.0",
"react": "17.0.2",
"react-i18next": "^12.0.0",
"i18next": "^22.0.6",
```

my `next-i18next.config.js`:

```
module.exports = {
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
  },
};
```

inside app:
```

import { useTranslation } from 'react-i18next';
....
const [label, setLabel] = useState('');
const { t } = useTranslation();
...
setLabel(t('common:continue'));

```
![image](https://user-images.githubusercontent.com/47118725/204553539-50ffa9bb-4cc1-46cc-96db-5c1f870d5a85.png)


I don't get where I need to put `returnNull: false,`

**Comment by adrai** [comment]
> ```
> 
> "next": "^12.3.0",
> 
> "next-i18next": "^13.0.0",
> 
> "react": "17.0.2",
> 
> "react-i18next": "^12.0.0",
> 
> "i18next": "^22.0.6",
> 
> ```
> 
> 
> 
> my `next-i18next.config.js`:
> 
> 
> 
> ```
> 
> module.exports = {
> 
>   i18n: {
> 
>     locales: ['en'],
> 
>     defaultLocale: 'en',
> 
>   },
> 
> };
> 
> ```
> 
> 
> 
> inside app:
> 
> ```
> 
> 
> 
> import { useTranslation } from 'react-i18next';
> 
> ....
> 
> const [label, setLabel] = useState('');
> 
> const { t } = useTranslation();
> 
> ...
> 
> setLabel(t('common:continue'));
> 
> 
> 
> ```
> 
> ![image](https://user-images.githubusercontent.com/47118725/204553539-50ffa9bb-4cc1-46cc-96db-5c1f870d5a85.png)
> 
> 
> 
> 
> 
> I don't get where I need to put `returnNull: false,`

```js
module.exports = {
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
  },
  returnNull: false,
};
```

**Comment by kirillleogky** [comment]
> > ```
> > 
> > "next": "^12.3.0",
> > 
> > "next-i18next": "^13.0.0",
> > 
> > "react": "17.0.2",
> > 
> > "react-i18next": "^12.0.0",
> > 
> > "i18next": "^22.0.6",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > my `next-i18next.config.js`:
> > ```
> > 
> > module.exports = {
> > 
> >   i18n: {
> > 
> >     locales: ['en'],
> > 
> >     defaultLocale: 'en',
> > 
> >   },
> > 
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > inside app:
> > ```
> > 
> > 
> > 
> > import { useTranslation } from 'react-i18next';
> > 
> > ....
> > 
> > const [label, setLabel] = useState('');
> > 
> > const { t } = useTranslation();
> > 
> > ...
> > 
> > setLabel(t('common:continue'));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/47118725/204553539-50ffa9bb-4cc1-46cc-96db-5c1f870d5a85.png)
> > I don't get where I need to put `returnNull: false,`
> 
> ```js
> module.exports = {
>   i18n: {
>     locales: ['en'],
>     defaultLocale: 'en',
>   },
>   returnNull: false,
> };
> ```

still the same
i even re-install modules but nothing

![image](https://user-images.githubusercontent.com/47118725/204571759-c46a7e2b-10fc-438c-9b79-5412c47daf42.png)


maybe smth wrong inside `next.config.js`

```
/** @type {import('next').NextConfig} */
const { i18n } = require('./next-i18next.config');
const withPWA = require('next-pwa');

const nextConfig = {
  i18n,
  // Due to Material UI styles mismatch
  reactStrictMode: false,
  fallback: true,
  images: {
    loader: 'custom',
  },

  compiler: {
    emotion: true,
  },

  pwa: {
    dest: 'public',
    swSrc: 'service-worker.js',
    disable: process.env.NODE_ENV === 'development',
    // cacheOnFrontEndNav: true,
    fallbacks: {
      image: '/assets/default-image.png',
    },
  },

  publicRuntimeConfig: {
......
  },

  serverRuntimeConfig: {
....
  },

  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });

    return config;
  },

  async redirects() {
    return [
      {
        source: '/admin',
        destination: '/admin/performance',
        permanent: true,
      },
      {
        source: '/creator',
        destination: '/creator/episodes',
        permanent: true,
      },
    ];
  },
};

module.exports = withPWA(nextConfig);
```

**Comment by adrai** [comment]
@kirillleogky did you also set returnNull in the i18next.d.ts file?

```ts
// i18next.d.ts
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    returnNull: false;
    ...
  }
}
```

If so, please create a minimal reproducible example and open a new issue.

**Comment by zhrivodkin** [comment]
```
import { useTranslation } from 'next-i18next';
const { t } = useTranslation(['layout']);
...
<Button size="xs" kind="secondary">
  {t('signup_submit')}
</Button>
```

package.json:
```
"i18next": "^22.4.9",
"next": "^13.1.5",
"next-i18next": "^13.1.4",
"react-i18next": "^12.1.5"
```

Still not working.

**Comment by adrai** [comment]
@zhrivodkin did you try: https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz ?

**Comment by zhrivodkin** [comment]
> @zhrivodkin did you try: https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz ?

Oh, thank you so much! Among the waterfall of comments I did not see the solution.

**Comment by FranciscoOssian** [comment]
It may not necessarily be a bug, but somehow it ends up causing a problem. Ideally, the function should return a string with a fallback value.

```ts
const { t: translation, i18n } = useTranslation();
const t = (s: string) => translation<string>(s);
```
I went with this approach so I don't have to make changes throughout the entire file. By the way, I'm migrating the code to ts, and this issue hasn't come up before.

**Comment by IberaSoft** [comment]
A potential solution could be:

`<div>{t<string>('your-label')}</div>`

_or_

`<div>{`${t('your-label')}`}</div>`
