### ISSUE TITLE
How to use the ```t``` function in an API call on Vercel?

### ISSUE THREAD

**Issue by Balabanovskii** [i18next/next-i18next#1833]
Hey,

I use next-i18next to translate my app and it works really great, but I can’t figure out how to use it properly in the API calls. I don’t want to use the locale detection because I send the locale in the request body.

I have an API endpoint like `pages/api/image/[id].js`. In this file I'm trying to use the `t` function like #1437 solution:

```
import { i18n } from 'next-i18next';
const createImage = async ( req, res ) => {
  i18n?.init() // Initialize i18n
  i18n?.changeLanguage('en')
  
  const translated = i18n?.t('key')
  // ...
}
```
This code works well on my local machine,  but after deployment on Vercel the "translated" variable always equals "undefined". 
I also didn’t find an answer in the #918 issue.

A few notes: 
1. Of course, I use the appWithTranslation HOC. 
2. This API endpoint can be called directly (outside of my app) like `site.com/api/image/12345_en`.
3. I use this code for image generation (open graph and others).

**Comment by Balabanovskii** [comment]
P.S. The ideal solution for me would be a function like "getT" from the [next-translate](https://github.com/vinissimus/next-translate) plugin: https://github.com/vinissimus/next-translate/issues/341.

**Comment by felixmosh** [comment]
i18n.init() is an async function.
You should add `await` before it.

```js
import { i18n } from 'next-i18next';
const createImage = async ( req, res ) => {
  await i18n?.init() // Initialize i18n
  await i18n?.changeLanguage('en')
  
  const translated = i18n?.t('key')
  // ...
}
```

**Comment by Balabanovskii** [comment]
Thanks for the answer! Indeed, it's easy. 
But now I met another problem — i18n is always "null" on the Vercel deployment. This code works perfectly on my local machine, but on the Vercel it always returns "i18n doesn't work".

Do you have an idea how to deal with it?

```js
import { i18n } from 'next-i18next';
const createImage = async ( req, res ) => {
  await i18n?.init() // Initialize i18n
  await i18n?.changeLanguage('en')
  let t;

  if (i18n === null) {
      t = ( ) => { return `i18n doesn't work` }
  } else {
      t = i18n.t
  }
  
  const translated = i18n?.t('key')
  // ...
}
```

**Comment by yanickrochon** [comment]
This is an issue I have as well. The global `i18n` instance is initialized from the `serverSideTranslations`, however when the API route is hit before that function is called, the global instance is `null`.

There should be a `getGlobalInstance` function, similar to `serverSideTranslations`, but only receiving a locale, returning the `i18n` instance. Because `import { i18n } from 'next-i18next';` clearly does not work and is unstable!

Solution proposed instead would be

```js
import { getInstance } from 'next-i18next';

export default async function handler(req, res) {
   const { lang } = req.query;
   const i18n = await getInstance(lang);

   ....

};
```

Since each API route can be hit and processed asynchronously, it makes no sense whatsoever to use the global instance! The proposed function should create the global instance if not initialized, then return 

```js
// async function getInstance(locale: string): Promise<I18n>

const instance = globalInstance.cloneInstance();
instance.changeLanguage(locale);

return instance;
```

**Comment by isaachinman** [comment]
Please note that you can use `createClient` from `next-i18next`  and instantiate an i18next instance yourselves.

**Comment by yanickrochon** [comment]
@isaachinman is there a concrete example of this? The source code shows the function receiving arguments, so do I pass the config from `next-i18next.config.js`?

**Comment by isaachinman** [comment]
> is there a concrete example of this?

Of course. Check how [serverSideTranslations](https://github.com/isaachinman/next-i18next/blob/master/src/serverSideTranslations.ts#L72) calls the function:

```ts
const config = createConfig({
  ...userConfig,
  lng: initialLocale,
})

const { i18n, initPromise } = createClient({
  ...config,
  lng: initialLocale,
})
```

**Comment by yanickrochon** [comment]
Then I would suggest adding a middleware to make the process simpler. Something like this

```js
import { apiTranslations } from `next-i18next/requestTranslations`;

const options = {
   queryParam: 'lng'    // "http://domain.com/api/foo?lng=en"  will set language to "en"
};

export default apiTranslations(options, async (req, res) => {
   const { i18n } = req;

   ...
});
```

Instead of throwing this redundent responsibility into user land?

**Comment by isaachinman** [comment]
@yanickrochon Feel free to submit a PR 👍

**Comment by yanickrochon** [comment]
I will certainly look at it, but I'm having issues with what you're suggesting.

```js
import createConfig from 'next-i18next/dist/commonjs/config/createConfig';
import createClient from 'next-i18next/dist/commonjs/createClient';
import { i18n as i18nConfig } from '../../../next-i18next.config';

const apiTranslations = handler => async (req, res) => {
   const locale = req.query?.lang || i18nConfig.defaultLocale;

   const config = createConfig({
      ...i18nConfig,
      lng: locale,
   });

   const { i18n, initPromise } = createClient({
      ...config,
      lng: locale,
   });

   await initPromise

   req.i18n = i18n;

   return handler(req, res);
};

export default apiTranslations(async (req, res) => {
   const { i18n } = req;

   ...
});
```

I get the error `Error: Initial locale argument was not passed into serverSideTranslations`. The error is thrown somewhere inside `createConfig`.

**Comment by isaachinman** [comment]
Not sure I follow. `createConfig` does not call `serverSideTranslations`. If you can provide a minimal repo, I can help you.

**Comment by yanickrochon** [comment]
The error came from a improperly setup error page (this is a project I am porting from another framework into Next.js) I had to change the import statement to 

```js
import { createConfig } from 'next-i18next/dist/commonjs/config/createConfig';
```

**Comment by rolznz** [comment]
Do you seriously expect people to have to include from the dist file?

I managed to get it working locally using https://github.com/i18next/i18next-fs-backend



```
import i18next from "i18next";
import Backend from "i18next-fs-backend";
const i18n = await i18next.use(Backend).init({
    lng: locale,
    backend: {
      loadPath: path.join(process.cwd(), "/public/locales/{{lng}}/{{ns}}.json"),
      addPath: path.join(
        process.cwd(),
        "/public/locales/{{lng}}/{{ns}}.missing.json"
      ),
    },
  });
  ```

**Comment by kaeon** [comment]
> Do you seriously expect people to have to include from the dist file?
> 
> I managed to get it working locally using https://github.com/i18next/i18next-fs-backend
> 
> ```
> import i18next from "i18next";
> import Backend from "i18next-fs-backend";
> const i18n = await i18next.use(Backend).init({
>     lng: locale,
>     ns: "common",
>     backend: {
>       loadPath: path.join(process.cwd(), "/public/locales/{{lng}}/{{ns}}.json"),
>       addPath: path.join(
>         process.cwd(),
>         "/public/locales/{{lng}}/{{ns}}.missing.json"
>       ),
>     },
>   });
> ```

Does this work on Vercel? For me it works locally but still not on Vercel.
