### ISSUE TITLE
Update i18next to 21.8.3 version to remove chrome warnings because of navigator.userAgent

### ISSUE THREAD

**Issue by adduss** [i18next/next-i18next#1834]
## Describe the bug
next-i18next use i18next underneath, that uses navigator.userAgent causing issue in chrome: https://github.com/i18next/i18next/issues/1778
Issue was already fixed: https://github.com/i18next/i18next/commit/4b9413c1f1a12ebda3760ebf7c8c58377b77cddd
Please update i18next library in project to version 21.8.3

## Occurs in next-i18next version
"next-i18next": "^11.0.0"

## Steps to reproduce
1. Use library in any project
2. Run Lighthouse report from ChromeDev tools with "Best practices" checkbox selected
3. Switch to console tab
4. Open issues - one issue found:
- Title: "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform"
- Description: "A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown."
More details about issue: https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

## Expected behaviour
No issue related with dependent library

## Screenshots
<img width="1462" alt="Screenshot 2022-05-18 at 08 01 40" src="https://user-images.githubusercontent.com/5172081/168984204-e3cc8421-416c-4b41-9654-a447f01e3004.png">

## OS (please complete the following information)
 - Device: MacBook Pro 2021 - macOS Monteret v12.2.1 / Apple M1 Pro
 - Browser: Chrome v100.0.4896.127
 - Runtime version: node v16.14.0

**Comment by adrai** [comment]
#1898
