### ISSUE TITLE
Namespaces option is not synced on the client.

### ISSUE THREAD

**Issue by felixmosh** [i18next/next-i18next#1839]
## Describe the bug
`options.ns` is not propagated to the client properly, it contains some namespace on the server, but the instance on the client doesn't

## Occurs in next-i18next version
11.0.0

## Steps to reproduce
1. Clone [simple example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple)
2. Change the `dev` script to `NODE_OPTIONS='--inspect' next`, which will allow you to debug next server
3. Add break point at the end of `serverSideTranslations`, check `i18n.options.ns`, it should contain all user required namespaces.
4. Add break point of the client, check `i18n.options.ns` it will contain only `common`.

## Expected behaviour
`i18n.options.ns` on the client should reflect the same value as in the server.

### Server side
![image](https://user-images.githubusercontent.com/9304194/169975161-57283dec-fc90-4841-b4ca-6feb8efc94d3.png)

### Client side
![image](https://user-images.githubusercontent.com/9304194/169975512-2fb82ff5-88f6-481a-bc25-916815239e3a.png)

## OS (please complete the following information)
 - Device: MBP 2019
 - Browser:  Chrome 101

**Comment by felixmosh** [comment]
Yeap, I will make a PR for this.

**Comment by felixmosh** [comment]
@adrai I need a consultation, 
From these lines, https://github.com/i18next/next-i18next/blob/d068ccf2242baf93313c5407c260393512bd99c4/src/serverSideTranslations.ts#L102-L108, looks like the initial store contains the loaded names spaces, do you think that it is safe to extract them on the client side from that `initialI18nStore` object or I can pass them separately in the props, WDYT?

**Comment by adrai** [comment]
I think it should be ok.
But I'm also relatively new to next-i18next 😁
