### ISSUE TITLE
Styled JSX Style Tags get removed

### ISSUE THREAD

**Issue by lolafkok** [i18next/next-i18next#1873]
## Describe the bug
I am currently noticing strange behaviour when using **next-i18next** in my nextjs-Application regarding styled-jsx-Style-Tags.

next: version 12.1.0
next-i18-next: version 11.0.0
**Caution: This only happens in production-mode!**
**Note:** I am using _export default appWithTranslation(MyApp);_ in _app.js_. 

## Description 
If I navigate to a page that does not include _getServerSideProps_ I am loosing all of my styled-jsx-Style Tags. (See screenshots below)

Before: 
![image](https://user-images.githubusercontent.com/98736567/174304423-badd1327-d316-4d36-acbf-62df41d9318f.png)

After:
![image](https://user-images.githubusercontent.com/98736567/174304496-93baaae7-8d4b-4d7b-ae2d-8758b0d15792.png)

The same happens if I navigate to a page with _getServerSideProps_ but without _...(await serverSideTranslations(locale, ["common"]))_

Because I just recently included **next-18next** to my Application I **removed** next-18next from my Application and noticed that my styled-jsx-Style-Tags are not getting removed.
If I remove _export default appWithTranslation(MyApp);_ and _...(await serverSideTranslations(locale, ["common"]))_ I am not loosing my styled-jsx-style-Tags. 
I also noticed the described bug when navigating via router.replace or router.push. 

My **temporary bugfix** for this problem is performing a Page Reload/F5 programmatically in these cases. This (a page reload) will recreate the _styled-jsx_-Style-Tags.
However this is not a permanent solution for me.

## Expected behaviour
When using _export default appWithTranslation(MyApp);_ and when navigating from a page with getServerSideProps (with _...(await serverSideTranslations(locale, ["common"]))_)  to a getServerSideProps-Page (without _...(await serverSideTranslations(locale, ["common"]))_) I should not loose all my _styled-jsx_-Style Tags.

**Comment by isaachinman** [comment]
Please provide a minimum reproduction via repo link.
