### ISSUE TITLE
Autocompletion and type-safe with typescript

### ISSUE THREAD

**Issue by bryantobing12** [i18next/next-i18next#1887]
Just checked  `next-intl` library and amazed that it has support for typescript integration and autocompletion out of the box

https://next-intl-docs.vercel.app/docs/usage/typescript

so that we can have type-safe and autocompletion in our `t` Function `t("home.title")`

I'm not sure if `next-i18next` supports this already or not, because I couldn't find any step on how to do this in `next-i18next` issues or description.

Is there some way to do this? or even maybe this case isn't necessary? Because I think it would be convenient to have this

**Comment by adrai** [comment]
related:
https://github.com/i18next/react-i18next/issues/1530
https://github.com/i18next/react-i18next/issues/1500
https://github.com/i18next/react-i18next/issues/1333

**Comment by adrai** [comment]
fyi: @pedrodurek, seems also next-i18next would benefit from this...

**Comment by TrebuhD** [comment]
This should do the trick (`next-i18next.d.ts`)
```typescript
// import the original type declarations
import "react-i18next";

// import all namespaces (for the default language, only)
import type en from "@public/locales/en/translation.json";

declare module "react-i18next" {
  // and extend them!
  interface CustomTypeOptions {
    // custom resources type
    resources: {
      translations: typeof en;
    };
  }
}
```

**Comment by bryantobing12** [comment]
I use `pnpm`, so react-i18next will not be installed with `next-i18next`. Is there a way to use 

```ts
import "next-i18next";

declare module "next-i18next"
```

directly instead of importing react-i18next?

**Comment by matannahmani** [comment]
@TrebuhD while using this solution I encountered a type error after passing ~100 keys
`Type instantiation is excessively deep and possibly infinite`

current code:
`
declare module "react-i18next" {
  // and extend them!
  interface CustomTypeOptions {
    // custom resources type
    resources: {
      common: typeof common;
      accountInfo: typeof accountInfo;
      login: typeof login;
      notifypage: typeof notifypage;
    }
  }
}
`

**Comment by klis87** [comment]
I solved this issue with https://github.com/klis87/i18next-ts-loader , unfortunately I suppose it will not work with next js by default. We could think if this could be worth integrating, then maybe we could have first-class TS citizen here too.

**Comment by KrokoYR** [comment]
Is there any progress on this issue? I've met the same problem

**Comment by ricardo-rp** [comment]
I have also spent the last 3 days looking for a way to do this. Since both i18next and react-i18next can be made fully type-safe by overriding their interfaces, one would expect the same of this lib. It was honestly very confusing to find out this isn't supported. Might be worth it adding to the docs.

As I understand, this lib is built on top of react-i18next. I thought overriding the react-i18next interfaces would be enough for the typescript changes to propagate to this lib's `useTranslation` why do they not do that?

**Comment by adrai** [comment]
Have you tried with v13?

**Comment by ricardo-rp** [comment]
Just tried it now. Sadly, upgrading to v13 doesnt solve the issue.

**Comment by adrai** [comment]
Did you follow: https://github.com/i18next/next-i18next/blob/master/UPGRADING.md ?
If so can you create a reproducible example?

**Comment by ricardo-rp** [comment]
@adrai thank you! v13 is very easy to make fully type-safe!

**Comment by ricardo-rp** [comment]
@adrai may I make a PR adding a typesafety section to the readme?

**Comment by adrai** [comment]
> @adrai may I make a PR adding a typesafety section to the readme?

@belgattitude what do you think?

**Comment by belgattitude** [comment]
+1

**Comment by getvega** [comment]
For anyone looking there is a good example [there](https://github.com/i18next/next-i18next/blob/master/examples/simple/%40types/i18next.d.ts).

**Comment by lesthoward** [comment]
This works for me in React:

```
import 'i18next';
import en from '@/locales/en.json';

declare module 'i18next' {
    interface CustomTypeOptions {
        defaultNS: 'translation';
        resources: {
            translation: typeof en;
        };
    }
}
```

Instead of declaring "react-i18next" I had to declare "i18next". Not really sure why because I am actually using "react-i18next" across the app not "i18next".
