### ISSUE TITLE
Incompatible with Next 12.2

### ISSUE THREAD

**Issue by NicolasBonet** [i18next/next-i18next#1891]
## Describe the bug
When I upgrade to Next 12.2 and deploy to Vercel, I have the following error: 

`Cannot read properties of undefined (reading '_nextI18Next')`

It gets resolved as soon as I downgrade to `next@12.1.6`

## Occurs in next-i18next version
`11.0.0`

## Steps to reproduce
Just upgrade to `next@12.2.0` and then try to access to the app, in my case I get a black screen (screenshot attached).

## Expected behaviour
The page should work just like it did for `next@12.1.6`

## Screenshots
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/13696500/176929720-188d0817-0329-4d91-871e-22733f25892c.png">

## Additional Info

I'm sure I'm using `serverSideTranslations` inside the page that I'm trying to load.

**Comment by raimille1** [comment]
Just ran into this while upgradeing to 12.2.0, for some reason statically generated pages are OK, but with serverSideTranslations + getServerSideProps I cannot get it to work, will be looking deeper into it but haven't gotten the time yet. We'll stay in 12.1.6 for now.

**Comment by adrai** [comment]
If it works locally, have you opened an issue at [next](https://github.com/vercel/next.js) ?

**Comment by ismaelbks** [comment]
I'm experiencing the same issue . I also noticed that the problem might be somehow linked to Incremental Static Regeneration : the problem vanishes after a new build and re-appear after 15 min (my page's cache is supposed to revalidate after 15 min). But I have ISR on 3 others pages with i18n-next which don't have any bug.
I also linted all my .yaml looking for a special character and I didn't found anything.  

```
"next-i18next": "^11.0.0"
"react": "^18.2.0"
"react-dom": "^18.2.0"
```

**Comment by visualcohol** [comment]
We have the same problem, and its somehow related to the middleware were using. Even if the middleware is just using a single next(). If there is no file, it just works fine.

Tried the next canary versions of next though and the error goes away, but with middleware there are still some strange behavior. For now the solution was rolling back the next version.

**Comment by maggo** [comment]
I have a similar issue with a custom middleware (for basic auth) and automatic locale redirects causing infinite redirects and at some point the website crashing because of it.

This is definitely a nextjs error, planning to set up a repro case soon

**Comment by AAS97** [comment]
Same issue here with: 
- next@12.2.0
- custom middleware that handle custom localization and next()


Was working well in the 12.2.beta, as far as I remember.

What is the status ? Has anyone raised an issue on Next ?

**Comment by JCMais** [comment]
Not stale.

**Comment by NicolasBonet** [comment]
Not stale.

**Comment by adrai** [comment]
#1657 same error message other reason?

**Comment by mavridiSS** [comment]
FYI: We had the same issue but we managed to fix it by removing `getInitialProps` in the custom App. We also have a custom middleware with redirects which was not the issue for us

next: 12.1.4
next-i18next: ^12.1.0

**Comment by thirdmusketeer** [comment]
Same issue with

next: 12.2.0,
next-i18next: 12.1.0

**Comment by adrai** [comment]
> Same issue with
> 
> next: 12.2.0, next-i18next: 12.1.0

please provide a minimal reproducible example... seems to work here: https://github.com/i18next/next-i18next/tree/master/examples/simple
