### ISSUE TITLE
Call for maintainer(s)

### ISSUE THREAD

**Issue by isaachinman** [i18next/next-i18next#1897]
Hi all, it's been four years now since I released `next-i18next@0.1.0`, and I feel truly privileged to have contributed to the NextJs ecosystem, and hopefully helped save some other devs' precious time.

Due to other projects and a sheer lack of time, I'll now pass the torch. Hopefully we can find a committed and competent maintainer to continue active development, otherwise I will put the project into archival.

Alternatively, there are several other NextJs i18n packages which are popular these days, so another option would be to simply merge projects, or create an easy migration path for users. I do hope that eventually, NextJs as a framework will support i18n first-class.

Pinging some relevant names, but feedback from anyone is appreciated!

@adrai @kachkaev @aralroca @amannn

**Comment by adrai** [comment]
Thank you Isaac for all your work and all your patience.
It saddens me to hear you made that choice, but that's just the nature of things.

Since I'm one of the i18next maintainer, I would be very happy if someone would agree to continue with next-i18next.
I am still available for support on topics related to i18next. Additionally, I would also offer a small sponsorship (GitHub sponsors or similar).

Wishing you all the best Isaac.

**Comment by adrai** [comment]
Pinging other names that contributed in the past:
@capellini @MathiasKandelborg @felixmosh @lucasfeliciano @prokopsimek @StarpTech @skrivanos @eraygundogmus @mweibel

**Comment by binodnepali** [comment]
Hi all, I am interested to contribute in the project. But this is my first in an open-source project and I did not know things work. Let me know how I can help with the project. :)  @eraygundogmus

**Comment by jamuhl** [comment]
Just discussed this with @adrai - if people agree we would suggest moving next-i18next to the i18next organization and start maintaining it like we do for react-i18next.

We (i18next and locize team) could help with issues, support and documentation - any help from devs using this module would be helpful and could be compensated through sponsoring coming through our locize.com).

This way we could assert this module stays well maintained in the years coming.

**Comment by isaachinman** [comment]
Moving `next-i18next` under the `i18next` org sounds like a great solution. @jamuhl and @adrai are more than competent in handling all internationalisation issues, and hopefully the community can lend some support in regards to the trickier aspects of NextJs.

Perhaps in the end, this shift could lead to a great simplification of the code – let's see.

I'll speak to the `i18next` team privately to start the process.

Thanks everyone!
