### ISSUE TITLE
Missing query object while redirect by locale

### ISSUE THREAD

**Issue by Fi1osof** [i18next/next-i18next#1906]
## 🐛 Bug Report

When load url with another locale, do redirect. For example:
`http://localhost:3000/en/oauth2/connect?foo=foo`
redirects to `http://localhost:3000/oauth2/connect?foo=foo` (if locale equal defaultLocale)

But in this case next-js router missing query params.
![Screenshot from 2022-07-07 19-26-45](https://user-images.githubusercontent.com/2550668/177823847-f30852b2-d393-4217-b562-3a0feb617a7c.png)

Locale ru contains 
```js
query: {
    "foo": "foo"
}
```

But locale en after redirect has empty query object even asPath = "/oauth2/connect?foo=foo"

## To Reproduce

1. Set default locale.
2. Create url with search params
3. Go url with different locale

```ts
// Paste your code here

import { useRouter } from 'next/router';

export const App: React.FC = () => {

  const router = useRouter();
  console.log(`locale ${router.locale}`, router);

  return null;
}

```

## Expected behavior

react.query before and after redirect is equals.

## Your Environment

- next-i18next@11.0.0

**Comment by adrai** [comment]
I'm not sure this is an issue of next-i18next, but it may be an issue of next.js.
Anyway, please provide a reproducible repository or codesandbox example.

**Comment by CallmeHongmaybe** [comment]
Hi there, 
Assuming that you're using `router.push()`, an you try not enabling shallow routing ? 
More info in the link: https://nextjs.org/docs/routing/shallow-routing#caveats

**Comment by techquestions** [comment]
not stale
