### ISSUE TITLE
Async config

### ISSUE THREAD

**Issue by IvanSKIT** [i18next/next-i18next#1908]
## 🚀 Feature Proposal

Allow async function in next-i18next.config.js, alike in next.config.js https://nextjs.org/docs/api-reference/next.config.js/introduction

## Motivation

Need to load locales list from CMS (Drupal) to allow CMS administrator to install new languages

## Example

````
// next-i18next.config.js

const fetchLocales = async () => {
  const response = await ...
  return response.data;
};

module.exports = async () => ({
  i18n: {
    locales: await fetchLocales(),
    defaultLocale: 'sk',
    localeDetection: false
  })
````

**Comment by adrai** [comment]
Do this on build time...
i.e. by creating a new npm script that fetches your locales list and saves it in a file and then import that file in the config
