### ISSUE TITLE
getStaticPaths: react-i18next:: You will need to pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by Zerebokep** [i18next/next-i18next#1909]
## 🐛 Bug Report

When using getStaticPaths the following warning is thrown: react_devtools_backend.js:4026 react-i18next:: You will need to pass in an i18next instance by using initReactI18next

## To Reproduce

https://stackblitz.com/edit/nextjs-na7dtq

visit /test/abc - check console

## Question

Is it possible to load the translations before showing a fallback (using router.isFallback)? I would like to use translated strings inside the fallback, but only the keys are shown.

**Comment by adrai** [comment]
You did not define the paths:

```js
export async function getStaticPaths() {
  return {
    paths: [
      {
        params: {
          testa: 'abc',
        },
      },
    ],
    fallback: true,
  };
}
```

**Comment by Zerebokep** [comment]
Thank you. :)
