### ISSUE TITLE
Unnecessary locale config requests on hover when using next/link <Link> component

### ISSUE THREAD

**Issue by taavisalo** [i18next/next-i18next#1923]
## 🐛 Bug Report

When hovering over components made with next/link, browser will prefetch(?) all translation config files for that page on every hover. This causes network and performance overhead. This happens only with production builds and not under development.

## To Reproduce

Can be reproduced on simple example page https://next.i18next.com/ by hovering over 'Change locale to "de"' or 'To second page buttons' at the bottom of the page by having devtools Network tab open to see requests.

## Expected behavior

Not requesting locale config file on hover.

## Your Environment

- *runtime version*: whatever https://next.i18next.com/ is using
- *i18next version*: 11.3.0
- *os*: Windows

**Comment by adrai** [comment]
This seems to be a Next.js feature: https://nextjs.org/docs/api-reference/next/link

set prefetch to false

**Comment by taavisalo** [comment]
> This seems to be a Next.js feature: https://nextjs.org/docs/api-reference/next/link
> 
> set prefetch to false

Setting prefetch to false does not help.

**Comment by adrai** [comment]
Currently afk...
I have no idea what is triggering that request... but looks to be a Next.js feature 🤷‍♂️

**Comment by taavisalo** [comment]
Quote from Next.js doc: "When prefetch is set to false, prefetching will still occur on hover. Pages using [Static Generation](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) will preload JSON files with the data for faster page transitions. Prefetching is only enabled in production."

So yeah seems to be intended behavior, but it is really bad.

**Comment by adrai** [comment]
you may need to create an issue in the next.js repo if you don't like it, sorry
