### ISSUE TITLE
[CONFIG] there is no posibility to avoid a namespace

### ISSUE THREAD

**Issue by djleonskennedy** [i18next/next-i18next#1925]
## 🐛 Bug Report

Hello i18next Team, Could you give a hand with my situation

I have the next structure

public/locales/
-------------- en.json
-------------- ua.json
-------------- de.json

however library forces me to provide namespace, but I don't need a namespace

How to configure it for my case?

## To Reproduce

provide config:   

```js
{...
   localeStructure: `{{lng}}`,
...}
```

## Expected behavior

locale should be loaded from `public/locales/en.json`

## AR

error - Error: ENOENT: no such file or directory, scandir '<app path>/public/locales/ua'

## Your Environment

- *runtime version*: i.e. node v14 +
- *i18next version*:    "next-i18next": "^11.3.0",
- *os*: Mac

**Comment by adrai** [comment]
Sorry, i18next requires at least 1 namespace.
