### ISSUE TITLE
Build fails with i18next v21.9.1

### ISSUE THREAD

**Issue by loreggia** [i18next/next-i18next#1926]
## 🐛 Bug Report

Building the project (next-i18next) currently fails because of [this change](https://github.com/i18next/i18next/commit/4ab3907567d28ebef622980755a840480d181b85) in i18next 21.9.1.

```
src/config/createConfig.ts:182:28 - error TS2322: Type 'string | false | readonly string[]' is not assignable to type 'string'.
  Type 'boolean' is not assignable to type 'string'.
```

## To Reproduce

on [master]
`npm install && npm build`

## Expected behavior

The build succeeds.

## Your Environment

- *runtime version*: node v16.16.0
- *i18next version*: 21.9.1
- *os*: Mac, Windows, Linux

**Comment by adrai** [comment]
@pedrodurek wasn't my type change not correct?

**Comment by loreggia** [comment]
Sorry, probably wasn't specific enough, it is not a problem when using the library, but when building this repo (I wanted to have a look at its inner workings ;) )

**Comment by adrai** [comment]
will check this in the next hours
