### ISSUE TITLE
Objects are not returned while using returnObjects: true

### ISSUE THREAD

**Issue by mkbctrl** [i18next/next-i18next#1933]
Docs say:
https://www.i18next.com/translation-function/objects-and-arrays

that by using
```
{ returnObjects: true }
```
I can expect an array as returned value. This is not the case here.

## 🐛 Bug Report

```
const benefits = t('benefits', { returnObjects: true })
```

returns 

`benefits`

and I was expecting 

```
['a', 'b']
```

## To Reproduce

```
// sample.json
{
  "benefits": ["a", "b"]
}
```

```
// MyComponent.tsx
export const MyComponent: FC = () => {
  const { t, i18n } = useTranslation('sample')
  const benefits = t('benefits', { returnObjects: true })
  console.log(benefits)
  return (
    <div>
    </div>
  )
}
```

It's so silly I can't believe I even have this issue, maybe I overlooked smth super simple earlier on...

**Comment by adrai** [comment]
just tested in this example: https://github.com/i18next/next-i18next/tree/master/examples/simple
Seems to work.

Please provide a reproducible example.

Maybe also set debug to true and check the developer console.
I suspect the key benefits could not be found.

**Comment by mkbctrl** [comment]
Thanks for the fastest reply in the internet 🍻 🍻 🍻 

Noob mistake? Each time I change smth in the `.json` file I have to restart the server 🤔 and then everything works.
Does it work like that out of the box, I didn't notice anything about that while setting things up.

I was expecting hot reload, sorry for wasting your time if it's by design.

**Comment by adrai** [comment]
maybe setting reloadOnPrerender to true helps
