### ISSUE TITLE
No translations for routes using getServerSideProps 

### ISSUE THREAD

**Issue by leonp-s** [i18next/next-i18next#1935]
## 🐛 Bug Report

Nothing is being translated for any routes deployed to Vercel that are using `getServerSideProps`, they are however working fine for SSG. Everything is working as expected locally.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/23201843/187447147-da22aa8d-80a3-4d42-aaaf-94e13fe7b538.png">

## To Reproduce

next-i18next.config.js
```js
const path = require("path");

module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "de", "fr"],
    reloadOnPrerender: process.env.NODE_ENV === "development",
  },
  localePath: path.resolve("./public/locales"),
};
```
pages/profile.tsx
```tsx
export const getServerSideProps: GetServerSideProps =>
    ...
    return {
      props: {
        ... ,
        ...(await serverSideTranslations(locale!, ["common", "profile"])),
      },
    };
  },
});

const Profile = (
  context: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
  const { t } = useTranslation("profile");
...
```

## Expected behavior

Expected resolution of a key when using `t("key")`

## Your Environment

- *runtime version*: v14
- *i18next version*: ^12.0.0

**Comment by leonp-s** [comment]
Thanks for your fast reply! I have added the debug flag and re-deployed. This is what I am seeing,

Vercel Logs
```
i18next::translator: missingKey en common 'key' 'key'
... missing keys
```
Client Logs
```
i18next: languageChanged en
i18next: initialized ...
i18next::translator: missingKey en common 'key' 'key'
... missing keys
```

Regarding the example you have posted, I can't see where `getServerSideProps` has been used or possibly I missed that?

**Comment by adrai** [comment]
There should be more logs before those... on server side.
something like "loaded namespace common for language en"...

**Comment by leonp-s** [comment]
That is everything I am seeing for runtime logs. However in the build logs I can see a bunch of,

```
i18next::backendConnector: loaded namespace common for language en { ... }
```

**Comment by adrai** [comment]
I just tested this... and I could reproduce it.

Seems saving the localePath in a variable is fixing this?

<img width="867" alt="image" src="https://user-images.githubusercontent.com/1086194/187475868-d8a9ed58-41e2-4072-8def-1ac7d8c2ff8c.png">


```js
const path = require('path')

const localePath = path.resolve('./public/locales')

module.exports = {
  // https://www.i18next.com/overview/configuration-options#logging
  debug: true,
  i18n: {
    defaultLocale: "en",
    locales: ["en", "de", "fr"],
  },
  localePath,
  reloadOnPrerender: process.env.NODE_ENV === 'development',
}
```

Can you try in your project?

**Comment by leonp-s** [comment]
Just gave that a go, unfortunately no change. So you managed to reproduce the error with `examples/simple` deployed to Vercel?

**Comment by adrai** [comment]
sorry, I'm not that experienced with Vercel...

**Comment by FBosler** [comment]
+1 this, We have been seeing similar behaviour since yesterday around 15:00

**Comment by leonp-s** [comment]
Okay, cheers for your help! I also managed to spin up a similar project with getServerSideProps which seemed to work. I noticed a difference in my Next version and have updated that which has somehow resolved everything...

**Comment by alecmcgovern** [comment]
@leonp-s my team also just started experiencing a similar (maybe same) issue, starting yesterday.  Please let me know if you find any updates.

**Comment by alecmcgovern** [comment]
Update: solved this issue by upgrading Nextjs from 11 --> 12

**Comment by leonp-s** [comment]
> Update: solved this issue by upgrading Nextjs from 11 --> 12

Yes, this also solved it for me, would be good to know why this happened.

**Comment by adrai** [comment]
You may open an issue at the Next.js repo and ask the Vercel team.

**Comment by c-schober** [comment]
Upgrade to the newest Next Version and next-i18next version still leads to not found translations for us on catch all routes when deploying with vercel. Seems like that vercel changed some parts of their architecture.
