### ISSUE TITLE
Setting defaultLocale on HTML in examples

### ISSUE THREAD

**Issue by kooba** [i18next/next-i18next#1942]
Not sure if setting default locale on HTML tag [here](https://github.com/i18next/next-i18next/blob/b69c464493a695facd880897eee9e285d213b25b/examples/ssg/pages/_document.js#L9) is a good idea. If `i18nextConfig.i18n.defaultLocale` is set to `en` and supported locales are `['en', 'de', 'it']` and user sends `Accept-Language: de-DE` then `navigator.languages` will be set to `de-DE`. Unfortunately `en` is a better match so English will be chosen even though user explicitly asked for `de`.

**Comment by adrai** [comment]
it's just an example... and de defaultLng is just a fallback...
you can do whatever you want...

**Comment by kooba** [comment]
Yep, you are right. It just requires users to debug through source maps to understand why changing `Accept-Language` has no effect on the redirection.
