### ISSUE TITLE
Server-side translations searching in wrong directory when using `next start <dir>`

### ISSUE THREAD

**Issue by te-online** [i18next/next-i18next#1945]
## 🐛 Bug Report

When using `next start <dir>`, `next-i18next` looks into the current directory for config and locales, instead of the given `<dir>` that next starts from.

Output of `next start --help`
```
      Description
        Starts the application in production mode.
        The application should be compiled with `next build` first.

      Usage
        $ next start <dir> -p <port>

      <dir> represents the directory of the Next.js application.
      If no directory is provided, the current directory will be used.

      Options
        --port, -p      A port number on which to start the application
        --hostname, -H  Hostname on which to start the application (default: 0.0.0.0)
        --help, -h      Displays this message
```

## To Reproduce

1. Create a template project in `/sites/test`
2. Build the next app
3. Change to `/sites`
4. Run `/sites/test/node_modules/.bin/next start /sites/test`
5. `next-i18next` will look in `/sites` for config file and locales

## Expected behavior

`next-i18next` honors the directory that Next.js is started from when looking for files.

## Your Environment

- *runtime version*: node v14.17.0
- *i18next version*: 21.8.9
- *os*: Tested on Mac, Linux

**Comment by adrai** [comment]
If you know how to get that <dir> value, feel free to submit a PR to also look for that directory somewhere here: https://github.com/i18next/next-i18next/blob/master/src/serverSideTranslations.ts#L26

**Comment by te-online** [comment]
I ended up restructuring the my setup, because that was easier 🤷  Sorry!
