### ISSUE TITLE
new translations is not updated at runtime

### ISSUE THREAD

**Issue by MohammedSaberMohammed** [i18next/next-i18next#1946]
Hello everyone I have an issue that when I add new strings to my json files I have to disconnect the server and make `yarn dev ` again in order to make it work . is this normal behavior?

**Comment by adrai** [comment]
Did you set reloadOnPrerender to true?

**Comment by MohammedSaberMohammed** [comment]
@adrai Thanks for your help, it works ffine.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
