### ISSUE TITLE
Feature: Read configs directly from next.config.js

### ISSUE THREAD

**Issue by geoshak** [i18next/next-i18next#1947]
## 🚀 Feature Proposal

It'd be nice it the library could read the `i18n` config object directly from `next.config.js` instead of mandating the creation of a separated `next-i18next.config.js` file. File which in our case has only 6 lines and 81 chars.

## Motivation

To keep repositories and folder structure as minimalist and clean and _navigable_ as possible.
Repos tend to get bloated with config files really quick as projects grow.

**Comment by adrai** [comment]
#1200
