### ISSUE TITLE
Hide locale prefix in URL

### ISSUE THREAD

**Issue by Kalesberg** [i18next/next-i18next#1949]
## 🚀 Feature Proposal
**Issue** i18n next plugin changes url by appending local prefixes
**Proposal** provide an option to remove locale prefixes

## Motivation
Rather than switching over to new route whenever a user chooses different language in the lang switcher, it would be cool if only the text changes in the browser without changing route.
And instead, we can store LOCALE in cookie or local storage to save user choices.

**Comment by adrai** [comment]
This is a Next.js feature of its i18n functionality... not something next-i18next can directly influence.

**Comment by zjy365** [comment]
> ## 🚀 Feature Proposal
> **Issue** i18n next plugin changes url by appending local prefixes **Proposal** provide an option to remove locale prefixes
> 
> ## Motivation
> Rather than switching over to new route whenever a user chooses different language in the lang switcher, it would be cool if only the text changes in the browser without changing route. And instead, we can store LOCALE in cookie or local storage to save user choices.

how did you solve it
