### ISSUE TITLE
Support for onFailedLoading API

### ISSUE THREAD

**Issue by awmottaz** [i18next/next-i18next#1960]
## 🚀 Feature Proposal

I would like to be able to register a callback to the [onFailedLoading i18next event](https://www.i18next.com/overview/api#onfailedloading). We cannot use the global i18n instance to do this because `.init()` is called before we are able to register the callback.

```tsx
// _app.tsx
function MyApp({ Component, pageProps }: AppProps) {
  useEffect(() => {
    function handleFailedLoading() {
      logger.error('failed to load translations');
    }

    // This callback will never be called because the i18n instance
    // has already attempted to load the translation data. The event
    // would have already fired before this is registered.
    i18n.on('failedLoading', handleFailedLoading);

    return () => {
      i18n.off('failedLoading', handleFailedLoading);
    }
  }, [])

  //...
}
```

## Motivation

We had a bug on our end that caused translations not to be loaded. We would like to be able to add logging/alerting when this happens.

## Example

The example above already shows one way we might use this. I am guessing that next-i18next would need to provide some way in `appWithTranslation` to allow us to hook into the time between when the i18n instance is created and when it is initialized. Maybe a third argument that takes a callback that is passed the i18n instance before init?

```tsx
export default appWithTranslation(MyApp, null, (i18n) => {
  i18n.on('failedLoading', handleFailedLoading)
});
```

Updating this

https://github.com/i18next/next-i18next/blob/a6affe3e0c5bf7471233e626ec2ce3d04ad1e4c4/src/createClient/browser.ts#L10-L15

To something like this:

```ts
  if (!instance.isInitialized) {
    config?.use?.forEach(x => instance.use(x))
    i18nCallback?.(instance)
    initPromise = instance.init(config)
  } else {
    i18nCallback?.(instance)
    initPromise = Promise.resolve(i18n.t)
  }
```

**Comment by adrai** [comment]
probably an optional hook function in the next-i18next.config file could work... will think about it tomorrow... going to bed now...

**Comment by adrai** [comment]
something like this:

```js
module.exports = {
  // https://www.i18next.com/overview/configuration-options#logging
  debug: process.env.NODE_ENV === 'development',
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
  // localePath,
  reloadOnPrerender: process.env.NODE_ENV === 'development',
  serializeConfig: false,
  onPreInitI18next: (i18n) => {
    i18n.on('failedLoading', handleFailedLoading)
  },
}
```

would this be ok?

**Comment by adrai** [comment]
Can you try with v12.1.0?

**Comment by awmottaz** [comment]
Thanks for the quick turnaround on this!

I think this will work for us, I will give it a try.

Handling the unserializable config is kind of a nuisance for us (we have several teams and lots of pages to deal with), but we can make that work. The reason I suggested adding it to the API of `appWithTranslation` was specifically to avoid handling an unserializable config. Is that something you would consider? Or does that go against the conventions of this package?

**Comment by adrai** [comment]
> Is that something you would consider?

Usually, if there is the need of listening to failedLoading events or other custom api, there is also a backend plugin like i18next-http-backend in use... this means the config is unserializable anyway.
btw: not only the appWithTranslation is affected, but also the serverSideTranslation call

**Comment by awmottaz** [comment]
This appears to be working well! Thanks again!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
