### ISSUE TITLE
Routing problems with default locale

### ISSUE THREAD

**Issue by Havrysh** [i18next/next-i18next#1964]
Hello everybody. Can you clearify for me is it possible to have default locale = 'en'. An when im on main page the route looks like this 'blabla.com'. Its ok, but when i go on another page the route is 'blabla.com/page/about. Can I have my default locale in me routing like this 'blabla.com/en/page/about' but still don't wanna see default locale on main page.

My desire is : 
en - defaultLocale 

blabla.com 
blabla.com/en/page/about

**Comment by adrai** [comment]
This is all habdled by Next.js directly, next-i18next has no direct influence on routing: https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by shaianest** [comment]
hi i wanted to do a trick in next documentation where /en is redirected to / and it adds locale default to list of locales which is a problem in your code you ignore locales in config and use the locales provided by router which looks for translations for default.json files.

**Comment by adrai** [comment]
don't know exactly what you mean, but there's https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale
