### ISSUE TITLE
Support for i18next ^22.0.0

### ISSUE THREAD

**Issue by belgattitude** [i18next/next-i18next#1965]
## 🚀 Feature Proposal

Support for latest i18next major release https://github.com/i18next/i18next/releases/tag/v22.0.0

## Motivation

Benefit from upstream typescript improvements.

## Proposal

next-i18next has an explicit dependency on [^21.9.1](https://github.com/i18next/next-i18next/blob/fcf9a5b67af46fd3b83e9a6cb654a53899218215/package.json#L132)

The easiest is to update to ^22.0.0. 

PR: https://github.com/i18next/next-i18next/pull/1966

That avoids situations where 2 instances would be installed (an currently make it hard to debug)

```
└─ nextjs-app@workspace:apps/nextjs-app
   ├─ i18next@npm:22.0.0 (via npm:22.0.0)
   └─ next-i18next@npm:12.1.0 [f054d] (via npm:12.1.0 [f054d])
      └─ i18next@npm:21.10.0 (via npm:^21.9.1)
```

As per i18next changelog there should not be breaking changes between the two versions. So it should be fine

PS: An alternative approach is to move i18next to peerDependencies with a range

```json
  "peerDependencies": {
    "i18next": "^21.9.1 || ^22.0.0"
  }
```

Installation instructions will need to be updated, ie: `yarn install next-i18next i18next`... (+ major would clarify the change)

Thanks for the amazing work

**Comment by adrai** [comment]
will be released in next major
