### ISSUE TITLE
Duplicates caused by @types/i18next-fs-backend 

### ISSUE THREAD

**Issue by belgattitude** [i18next/next-i18next#1982]
In preparation for https://github.com/i18next/next-i18next/pull/1966, I'd like to gather recommendations about

```bash
npm why i18next
```

![image](https://user-images.githubusercontent.com/259798/197175158-739b5f78-19f1-493f-9d76-01884cf01996.png)

Types lives in definitely typed: https://www.npmjs.com/package/@types/i18next-fs-backend

In theory It shouldn't impact users, but as we have it in our devDependencies it might help to keep clean

**Comment by adrai** [comment]
@pedrodurek ?

**Comment by adrai** [comment]
I'm not very familiar with these TypeScript issue, @rosskevin can you maybe advice?

**Comment by rosskevin** [comment]
I don't use next or the [i18next-fs-backend](https://github.com/i18next/i18next-fs-backend).  

My only feedback is to state that I strongly prefer we ship types directly from each repo instead of using external DefinitelyTyped which can lag behind.

**Comment by adrai** [comment]
v1.2.0 should now include the types directly for i18next < v22.0.0
and v2.0.0 should now include the types directly for i18next >= v22.0.0

**Comment by belgattitude** [comment]
Fixed

```
i18next@22.0.2 dev
node_modules/i18next
  dev i18next@"^22.0.2" from the root project
  peer i18next@">= 19.0.0" from react-i18next@12.0.0
  node_modules/react-i18next
    dev react-i18next@"^12.0.0" from the root project

```
