### ISSUE TITLE
{{lng}} localeStructure does not work

### ISSUE THREAD

**Issue by kasugasorata98** [i18next/next-i18next#1989]
## 🐛 Bug Report

I am trying to create this structure, public/locales/<lang>.json

No errors were shown yet the translations are empty.

## To Reproduce

```js
const path = require('path')
module.exports = {
    i18n: {
        locales: ['en', 'bm', 'id', 'zh', 'th'],
        defaultLocale: 'en',
    },
    localePath: path.resolve('public/locales/'),
    localeStructure: '{{lng}}',
    localeExtension: 'json',
}

and

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  };
}
```

## Expected behavior

I expect to see my translations appear.

## Your Environment

- *runtime version*: v16.14.2, chrome browser
- *i18next version*: 12.1.0
- *os*: Mac

**Comment by adrai** [comment]
Please provide a minimal reproducible example and compare it with this one: https://github.com/i18next/next-i18next/tree/master/examples/simple

**Comment by shaianest** [comment]
sorry about reproducible repo but i build on server and translations are gone my only defferent is localePath
which is a function in config but string in build.
