### ISSUE TITLE
How can I get locales from another source?

### ISSUE THREAD

**Issue by Havrysh** [i18next/next-i18next#1990]
In my project we don't wanna have static array of locales(that's why i18n doesn't work for us). We want to get them from server and determine one by algorithm. How can we implement this ?

**Comment by adrai** [comment]
On your own... or https://github.com/i18next/i18next-http-backend/tree/master/example/next

**Comment by Havrysh** [comment]
@adrai and how to make next js 'believe' that determined custom locale is that locale that comes fron context object? sort of rewrite next js locale (from context) with ours custom one

**Comment by adrai** [comment]
I have no idea what you actually mean... next-i18next knows fallbacks => https://github.com/i18next/next-i18next#fallback-locales

Sorry, but if you have questions regarding Next.js and the [Next.js i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing) you should ask at StackOverflow or similar...
This is the repository for next-i18next... if you found an issue with the existing next-i18next interface, create a reproducible example and open an issue. 🤷‍♂️
