### ISSUE TITLE
State of Layout is lost when using HOC appWithTranslation

### ISSUE THREAD

**Issue by thnam1410** [i18next/next-i18next#2001]
## 🐛 Bug Report

- HOC appWithTranslation cause Layout lost it own state

## To Reproduce

Setting next-i18next according the documentation:

1. Setup configuration
```js
//My next-i18next.config.js
module.exports = {
	i18n: {
		defaultLocale: "en",
		locales: ["en", "de"],
	},
};

//My next.config.js
const { i18n } = require("./next-i18next.config");

const nextConfig = {
	reactStrictMode: true,
	swcMinify: true,
	i18n,
};

module.exports = nextConfig;
```

2. Setup app with layout 
```js
// My _app.js
import "../styles/globals.css";

import { appWithTranslation } from "next-i18next";

const MyApp = ({ Component, pageProps }) => {
	const getLayout = Component.getLayout ?? ((page) => page);

	return <>{getLayout(<Component {...pageProps} />)}</>;
};

export default appWithTranslation(MyApp);
```

3. Create sample Layout
```js
import React from "react";

function Layout() {
	const [state, setState] = React.useState(0);
	return (
		<div>
			<div>LayoutState: {state}</div>
			<button onClick={() => setState(69)}>SetState</button>
		</div>
	);
}

export default Layout;

```

4. Setup 2 pages with layout switch between to watch the state is losing
```js
// index.js
import Link from "next/link";
import Layout from "../Layout";

export default function Home() {
	return (
		<div>
			<Link href="/another-page">Go to another page</Link>
		</div>
	);
}
Home.getLayout = (page) => {
	return (
		<>
			<Layout />
			{page}
		</>
	);
};
```

```js
// another-page.js
import React from "react";
import Layout from "../Layout";
function AnotherPage() {
	return <div>another-page</div>;
}

export default AnotherPage;

import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export const getServerSideProps = async ({ locale }) => {
	return {
		props: {
			...(await serverSideTranslations(locale ?? "en", ["common"])),
		},
	};
};

AnotherPage.getLayout = (page) => {
	return (
		<>
			<Layout />
			{page}
		</>
	);
};

```

## Existing code in project
This is my code in _app.tsx
![image](https://user-images.githubusercontent.com/62019809/199278716-74c3d1f3-b0fb-4820-a0a5-4fbb740502ef.png)

This is my test layout with state for this issue
![image](https://user-images.githubusercontent.com/62019809/199279024-2453431a-5a6d-488e-872f-ec682c00cc33.png)

Demo:
https://user-images.githubusercontent.com/62019809/199281870-b0185f24-f059-41a8-8ceb-5ec2466bf5c5.mp4

## Expected behavior

A state of layout will not change when switching route

## Environment

- *runtime version*: i.e. node v16
- *i18next version*: i.e. 12.1.0
- *os*:  Windows

**Comment by adrai** [comment]
Please create a minimal reproducible example that shows no issue without the use of next-i18next.

**Comment by thnam1410** [comment]
> Please create a minimal reproducible example that shows no issue without the use of next-i18next.

I attached the demo video including an example without using the appWithTranslation HOC

**Comment by adrai** [comment]
That's a video and not a reproducible example...
and additionally, it is not minimal... it seems to use hydration etc... stuff.

**Comment by thnam1410** [comment]
I updated the minimal reproducible example again, please help me check it out xD.
Besides, turn out i found that it was not caused from HOC appWithTranslation but the serverSideTranslations in this issue.

**Comment by adrai** [comment]
Currently afk.
Please create a new GitHub repository and add your code there, so I can clone it and test afterwards.

**Comment by thnam1410** [comment]
I found that this problem is not caused by AppWithTranslation HOC. 
It cause by serverSideTranslations when i'm passing it down to the current page and when i redirect into another page which i'm not using that serverSideTranslation function.

Btw, this is my repo for testing this problem: https://github.com/thnam1410/i18next-rerender-layout-test

**Comment by adrai** [comment]
Yes, using serverSideTranslation is correct.
But honestly, I don't know why it is not persisting the state when not using serverSideTranslation, in theory it should also persist the state.

**Comment by husseinraoouf** [comment]
@adrai can we reopen this issue, the same issue happens with me 
when there is two pages one with `serverSideTranslations` and the other is without `serverSideTranslations` the layout lose it's state when transition between the pages

**Comment by adrai** [comment]
> @adrai can we reopen this issue, the same issue happens with me 
> 
> 
> 
> when there is two pages one with `serverSideTranslations` and the other is without `serverSideTranslations` the layout lose it's state when navigating between the pages 

For sure we can reopen it, but still don't know how to solve this... 🤷‍♂️
