### ISSUE TITLE
404 (Not Found) index page when building multi-tenant app

### ISSUE THREAD

**Issue by patrik-simunic-cz** [i18next/next-i18next#2019]
## 🐛 Bug Report

I'm building a multi-tenant Next.js app. After adding `next-i18next` into the mix, the homepage (index page) started ending on 404 Not Found. All other pages work just fine, only index page gets 404. When I comment out `next-i18n` (the config in `next.config.js` in particular) everything starts just working again. See the prepared bug reproduction below

## To Reproduce

Here I've prepared a [minimal reproducible example of this problem](https://github.com/patrik-simunic-cz/bug-next-i18next-multitenant).

## Expected behavior

The `index` (home) page should load ok even with `next-i18next`.

## Your Environment

- *runtime version*: node v14.18.3
- *next-i18next version*: 12.1.0
- *next.js version*: 13.0.3
- *os*: MacOS

**Comment by adrai** [comment]
Seems not to be a next-i18next issue, but a Next.js issue with i18n.
proof https://github.com/patrik-simunic-cz/bug-next-i18next-multitenant/pull/1

Please open an issue at the Next.js repo or as at Stackoverflow.

**Comment by patrik-simunic-cz** [comment]
@adrai Oh.. alright... thanks for pointing me the right direction 😊

**Comment by patrik-simunic-cz** [comment]
@adrai actually, no. It does work. I just tried it with all the changes you made to my bug reproduction and works beautifully. This is most definitely an error with next-i18next.

**Comment by adrai** [comment]
https://github.com/patrik-simunic-cz/bug-next-i18next-multitenant/pull/1/files#diff-882b2c04b01b2e8b2cdcf1817c30ea503a8005f1c0d54cfff37053b6801fea85L5

**Comment by adrai** [comment]
next-i18next is not doing any routing etc... all is done by next.js

**Comment by adrai** [comment]
Feel free to investigate the code if you think there is something that could influence it: https://github.com/i18next/next-i18next/tree/master/src

**Comment by patrik-simunic-cz** [comment]
Well if I remove the config and leave all the rest (`appWIthTranslation`, `useTranslation`s and `serverSideTranslations`) I no longer get 404 on index page, but translations them self don't work, since now they don't know the location of locale file + I know that I'll need the config file to configure the locale files on Vercel (`localePath: path.resolve('./public/locales')`). Next-i18next may no be doing any routing itself, but the locale detection by domain is done via the config. So removing the config solves the 404 error, but introduces other problems since then `next-i18next` is not working properly.

**Comment by adrai** [comment]
I'm not saying you have to remove the config, I'm only saying, this issue is most probably not caused by next-i18next but by the Next.js i18n routing feature => https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by patrik-simunic-cz** [comment]
😅 ohhh... I see, now I get it. Well, thanks again :)
