### ISSUE TITLE
Trans component <a>[Object object]</a> instead of proper link

### ISSUE THREAD

**Issue by chojnackipiotr** [i18next/next-i18next#2022]
I got some error with interpolation in Trans component in next-i18next. Instead of proper link I get [Object object]. When I check the translation value in React Developers Tools I see that everything is ok.

Here is my usage of this component: `<Trans>{translation.key}</Trans>`

translation.key is already translated value with html tags in it. I tried many solutions but every time give me [Object object]

**Comment by adrai** [comment]
Please provide a reproducible example. Btw. this is probably not related to next-i18next directly, but to react-i18next: https://github.com/i18next/react-i18next

**Comment by belgattitude** [comment]
@chojnackipiotr I got hit in the past by a babel plugin (don't remember if it was emotion css). Without proper repo I can't say, but would check the babel config (or update the nextjs version if using swc / swcMinify). It might disappear
