### ISSUE TITLE
[Docs] Static HTML Export with i18n compatibility in Next.js Blog post

### ISSUE THREAD

**Issue by marinovl7** [i18next/next-i18next#2024]
## Documentation issue

I am just building a website with next-i18next which should be staticaly generated and I found the blog post and the example repo in your project, which I find really helpful. However there are no examples if this workoround can be used to actually fetch data from an external source and use the translations at the same time.  If yes then it will be extremely helpfull to see how you can do that in the example repo ( https://github.com/i18next/next-i18next/tree/master/examples/ssg ), if no then I think this should be mentioned in both the blog post ( https://locize.com/blog/next-i18n-static/ ) and the README in the example repo.

The problem is that it's unclear how you can use the `getStaticPaths` and `makeStaticProps` ( see step 4 of the blog post ) if you actually want to use them for data fetching in your `pages` folder

## Motivation

I think its important to show how you can fetch data, when using this workouround, because this is very specific and a simple example will do a favor to all developers, who want to use next-i18next with SSG and external APIs

**Comment by adrai** [comment]
This is normal React / Next.js know how and not really a next-i18next topic... but here you have it: https://github.com/i18next/next-i18next/commit/5a141b65efc07def88d935c80011b2a3c84ebd63
