### ISSUE TITLE
[v13] string properties complain about null return

### ISSUE THREAD

**Issue by Zerebokep** [i18next/next-i18next#2038]
It seems t()'s return type now includes null. This results in all string properties to complain about it:

e.g. <input>'s placeholder:

<img width="799" alt="Screenshot" src="https://user-images.githubusercontent.com/15731988/203619298-8b771332-319b-474d-9248-1c167f4be503.png">

**Comment by adrai** [comment]
https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by Zerebokep** [comment]
Thank you.

**Comment by AlexandreBourdeaudhui** [comment]
So, we need to wait the next release for stopping this warning ?
Or includes an interface into d.ts file ?

**Comment by adrai** [comment]
exactly
