### ISSUE TITLE
TFunctionDetailedResult<object>' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'

### ISSUE THREAD

**Issue by psionline-jliddell** [i18next/next-i18next#2040]
## 💥 Regression Report

A clear and concise description of what the regression is.

App will no longer compile with the following error.
Type 'TFunctionDetailedResult<object>' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'

Example template:
{t("systemCheckRetry.throughput.detail.0", state.failureDetails)}

Already added the types file definition for null | string error.

interface CustomTypeOptions {
    returnNull: false;

## Last working version

Worked up to version: X.X.X
"react-i18next": "^11.18.6"
"i18next": "^22.0.1"

Stopped working in version: Y.Y.Y
"react-i18next": "^12.0.0"
"i18next": "^22.0.6"

## To Reproduce

See above.

## Expected behavior

App should continue to compile

## Your Environment

Node 16

**Comment by adrai** [comment]
Please provide a minimal reproducible example. Like a little github repository.

**Comment by psionline-jliddell** [comment]
@adrai 
Here is an example repo.
https://github.com/psionline-jliddell/i18next-error

Issue appears to be that if the object being passed in has a type of any, the template error will exist.

**Comment by adrai** [comment]
That's not related to next-i18next but i18next (maybe react-i18next)...

Here an example on how you could solve it:
`<h2 className="h6-like">{t("EXAMPLE_KEY", state as {})}</h2>`

```ts
import React from "react";
import logo from "./logo.svg";
import "./App.css";
import i18n from "i18next";
import { useTranslation, initReactI18next } from "react-i18next";

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    // the translations
    // (tip move them in a JSON file and import them,
    // or even better, manage them via a UI: https://react.i18next.com/guides/multiple-translation-files#manage-your-translations-with-a-management-gui)
    resources: {
      en: {
        translation: {
          "Welcome to React": "Welcome to React and react-i18next",
          EXAMPLE_KEY: "example value {{someDetail}}",
        },
      },
    },
    lng: "en", // if you're using a language detector, do not define the lng option
    fallbackLng: "en",

    interpolation: {
      escapeValue: false, // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
    },
  });

interface AppState {
  someDetail: any;
}

function App() {
  const { t } = useTranslation();

  const [state, setState] = React.useState<AppState>({
    someDetail: "test-dynamic",
  });

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>

        <h2 className="h6-like">{t("EXAMPLE_KEY")}</h2>
        <h2 className="h6-like">{t("EXAMPLE_KEY", { someDetail: "test-dynamic" })}</h2>
        <h2 className="h6-like">{t("EXAMPLE_KEY", state as {})}</h2>
      </header>
    </div>
  );
}

export default App;
```

@pedrodurek maybe you have a better idea?

**Comment by adrai** [comment]
try with i18next v22.4.4

**Comment by elr0berto** [comment]
Had the same problem after upgrading.
Solved it by downgrading to 
"react-i18next": "^11.18.6"
"i18next": "^22.0.1"
