### ISSUE TITLE
How to deal with Large Page Data

### ISSUE THREAD

**Issue by mister-tang** [i18next/next-i18next#2047]
## 🚀 Feature Proposal
I'm having some issues, setting it returns two language versions
{
  _nextI18Next: {
    initialI18nStore: { zh: [Object], en: [Object] },
    initialLocale: 'zh',
    ns: [ 'common' ],
    userConfig: { i18n: [Object], default: [Object] }
  }
}

## Motivation

This setting will add a lot of data, which will affect page loading. How to set it to return a language

## Example
How to set default language hidden
{
  _nextI18Next: {
    initialI18nStore: { zh: [Object]},
    initialLocale: 'zh',
    ns: [ 'common' ],
    userConfig: { i18n: [Object], default: [Object] }
  }
}

**Comment by adrai** [comment]
default language / fallback language is always sent, that's the purpose of a fallbackLng
