### ISSUE TITLE
fetch language data via i18next-http-backend not working starting from v11.0.0

### ISSUE THREAD

**Issue by donghakang** [i18next/next-i18next#2048]
## 💥 Regression Report

A clear and concise description of what the regression is.
I was using i18next-http-backend plugin to fetch language key:value. I am trying to upgrade version of next-i18next and as you guessed it, it is not working.
My code looks like this.

```typescript
const HttpBackend = require('i18next-http-backend');
//...

module.exports = {
  i18n: {
    // this part does not matter I think...
    defaultLocale: // defaultLocale
    fallbackLng: // fallbackLng...,
    locales: // locales ,
    defaultNS: // defaultNS, 
    use: [ HttpBackend ],
  },

  use: [HttpBackend],
  backend: {
    loadPath: `{{lng}}`,
    request: (options, url, payload, callback) => {
      if (url === noLocale.localeCode) {
        callback(null, { status: 404, data: '' });
        return;
      }

      axiosFetcher(`http://localhost:8080/${localeCode}`)
        .then((res) => {
          callback(null, {
            status: res.status,
            data: JSON.stringify(res.data.data.translations),
          });
        })
        .catch((err) => {
          callback(err, err.response);
        });
    },
  },
  serializeConfig: false,
  react: {
    useSuspense: false,
  },
  // debug: true,
};
```

P.S. Not working means data is fetching via request but when it's used, translation data don't show (`t('login')`)

## Last working version

Worked up to version: 10.5.0

Stopped working in version: 11.0.0

## To Reproduce

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the results here
```

## Your Environment

- *next-i18next*: "^10.5.0",
- *next*: "12.3.3"
- *i18next-http-backend*: "^1.2.6",
- *os*: Mac

**Comment by adrai** [comment]
Seems to work... => https://github.com/i18next/i18next-http-backend/tree/master/example/next
Please provide a minimal reproducible example.

**Comment by donghakang** [comment]
I don't know if it is just small detail that I am missing or not.. 
The project is quite big to copy paste in here.. If I have a time I will try to make separate project to test out in detail... 

For now I will close this issue

**Comment by donghakang** [comment]
<SticCardPageWrapper>
