### ISSUE TITLE
Text content does not match server-rendered HTML.

### ISSUE THREAD

**Issue by skychavda** [i18next/next-i18next#2052]
## 🐛 Bug Report

I follow the same steps as per the documentation to add support of i18n but when I refresh my browser then Hydration error is coming
![image](https://user-images.githubusercontent.com/36260957/206725929-faf26576-af10-4d0f-820b-552c66077620.png)

## To Reproduce

Take a [pull](https://github.com/skychavda/google-account-page/tree/feat/i18n-integration) from repo
Run server with `npm run dev`
Check the terminal console and browser console

## Expected behavior

In `hero.jsx` file I have added one console that prints the value of `title` from `hero.json` but in a terminal, you can see that it only prints the key, not the value that's why this hydration error occurs.

![image](https://user-images.githubusercontent.com/36260957/206727333-2b3c28f1-de27-41e4-8746-bdac4f6e6815.png)

## Your Environment

- *runtime version*: i.e. node v14.18.1
- *i18next version*: i.e. 22.1.5
- *os*: Linux

**Comment by skychavda** [comment]
Thank you so much and sorry for may mistak

**Comment by ekenigs** [comment]
ESLint rule to catch this:
```json
"no-restricted-imports": [
  "error",
  {
    "paths": [
      {
        "name": "react-i18next",
        "importNames": ["useTranslation"],
        "message": "Please import 'useTranslation' from 'next-i18next' instead."
      }
    ]
  }
]
```
