### ISSUE TITLE
Error: Text content does not match server-rendered HTML.

### ISSUE THREAD

**Issue by jeniiik** [i18next/next-i18next#2054]
## 🐛 Bug Report

Hello,
I had this error last time too, but somehow it started working after I updated the library, so I have it again and I don't know how to fix it

Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.

![Snímek obrazovky 2022-12-10 v 20 48 00](https://user-images.githubusercontent.com/74861056/206872806-14c6e9aa-6508-472b-b9e4-9ba9edff732b.png)
![Snímek obrazovky 2022-12-10 v 20 48 53](https://user-images.githubusercontent.com/74861056/206872836-dfac88f6-23b9-4ef9-a8c5-e8cde970ec6c.png)

## To Reproduce

```js
const path = require('path');

module.exports = {
  i18n: {
    defaultLocale: 'cs',
    locales: ['cs', 'en'],
    localePath: path.resolve('./public/locales'),
  },
};
```

```js
export default function Home() {
  return (
    <>
      <Head>
        <title>Jan Haratek</title>
        <meta name="title" content="Jan Haratek" />
        <meta name="author" content="Jan Haratek" />
        <meta
          name="description"
          content="Jan Haratek, vývojář webových stránek. Potřebujete webové stránky? Neváhejte mně kontaktovat!"
        />
        <meta
          name="keywords"
          content="Web, Jan, Haratek, Jan Haratek, Webové stránky, Design"
        />
      </Head>
      <Hero />
      <Motivation />
      <Technology />
      <Testimonials />
      <Work />
      <Contact />
    </>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'hero',
        'motivation',
        'work',
        'contact',
        'technology',
        'contact-form',
        'footer',
        'header',
        'testimonials',
      ])),
    },
  };
}
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 22.2.0
- *i18n version*: i.e. 0.15.1
- *next-i18next version*: i.e. 13.0.0
- *react-i18next version*: i.e. 12.1.1
- *os*: Mac

**Comment by adrai** [comment]
Please provide a reproducible example... maybe also check if you are using the correct useTranslation hook, like https://github.com/i18next/next-i18next/issues/2052

**Comment by jeniiik** [comment]
@adrai Thank you so much, It was bad useTranslation hook I was importing react instead next!
