### ISSUE TITLE
importing `DefaultNamespace` even though it's not exported

### ISSUE THREAD

**Issue by maks-io** [i18next/next-i18next#2060]
Hi,

i saw that you're importing `DefaultNamespace` in https://github.com/i18next/next-i18next/blob/master/src/types.ts from `react-i18next` for the sake of re-exporting it, but it is actually not being exported from there: https://github.com/i18next/react-i18next/blob/v12.1.1/index.d.ts

I could create a PR for it, question is in which direction you guys wanna go.

Or maybe I'm missing something in general, but it seems off to me.

**Comment by adrai** [comment]
Seems you're right...
a PR is very welcome ;-)

**Comment by maks-io** [comment]
> Seems you're right... a PR is very welcome ;-)

Sure thing :)
https://github.com/i18next/next-i18next/pull/2061

**Comment by adrai** [comment]
should be fixed with v13.0.2
