### ISSUE TITLE
Text content does not match server-rendered HTML

### ISSUE THREAD

**Issue by MariuzM** [i18next/next-i18next#2062]
## 🐛 Bug Report
There are 2 issues I'm facing:
1. I have followed the guide but still getting the `Text content does not match server-rendered HTML` error.
![image](https://user-images.githubusercontent.com/36937039/207923011-1028dd2d-2b8d-44e3-b7eb-88e1e471d864.png)

2. For a breaf moment when page loads text flickers 
https://user-images.githubusercontent.com/36937039/207923064-37293968-8f79-4df5-9b79-10a3e1da7db1.mov

## To Reproduce
Created repo: https://github.com/MariuzM/i18/tree/main

**Comment by MariuzM** [comment]
Ok fixed that, did not realized i needed to use t in component section and not page. This fixed both issues.

**Comment by MariuzM** [comment]
I know this is off topic but if i can ask. When i was using React i had a button to change language
```
      <h1>Button Change: {t('Button Change')}</h1>
      <button onClick={() => i18next.changeLanguage('en')}>en</button>
      <button onClick={() => i18next.changeLanguage('de')}>de</button>
```

This does not seem to work with Next.js because i get this error
![image](https://user-images.githubusercontent.com/36937039/207927290-3083877a-4323-4cdf-b0de-f1eeecc0f845.png)

**Comment by adrai** [comment]
Yes, I recommend to change language via navigation... but the error occurs because of the wrong i18next instance...
use `i18n.changeLanguage('en')` coming from `const { t, i18n } = useTranslation()`

**Comment by NairiAreg** [comment]
I have the exact same problem, with text flickering etc, How did you fix it?
My problem appears when I use the "translation" from the context, somewhere in the code
<img width="749" alt="image" src="https://user-images.githubusercontent.com/51801223/232327993-a851f839-2406-4905-9f06-242bc42f633d.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/51801223/232328007-ae10961f-27c2-4cf1-95aa-381ad5fd2097.png">

If I uncomment the code the error will appear on refresh :/

**Comment by rumean** [comment]
If you have an error using react-i18next, please refer to this link

https://github.com/vercel/next.js/discussions/41319
