### ISSUE TITLE
Custom path issue

### ISSUE THREAD

**Issue by MariuzM** [i18next/next-i18next#2063]
## 🐛 Bug Report

My old path is:
`public/locales/en/common.json`
`public/locales/de/common.json`

And new one i want to use:
`public/locales/en.json`
`public/locales/de.json`

So then i set my config like so
```
  localePath: path.resolve('public/locales'),
  localeStructure: '{{lng}}',
  localExtension: null,
```

Everything works i get translations from my new path!

But as soon as i remove files from old path and especially path `en` `public/locales/en/common.json`, i stop getting translations.

**Comment by adrai** [comment]
because at least 1 namespace file is mandatory

**Comment by MariuzM** [comment]
Oh, no way to disable this?

**Comment by adrai** [comment]
currently not
