### ISSUE TITLE
hiphen breaks translation loading

### ISSUE THREAD

**Issue by darklight9811** [i18next/next-i18next#2066]
## To Reproduce

[https://codesandbox.io/s/next-i18n-bug-ybnoit?file=/pages/index.js](https://codesandbox.io/s/next-i18n-bug-ybnoit?file=/pages/index.js)
To test between `br` and `en-us` you can change both the locale (that is not being retrieved, I dont know why too) and the i18next config

## Expected behavior

Translation works serverside but not client side, causing a hydration issue

## Your Environment

- *runtime version*: node
- *i18next version*: 13.0.2
- *os*: Windows, Linux

**Comment by adrai** [comment]
try to rename everything from en-us to en-US
the locale format is standardized: https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by darklight9811** [comment]
@adrai it should be cool to add a warning if the value given is not correct then, I spent hours trying to debug without direction.

**Comment by adrai** [comment]
Feel free to tell this the Vercel team... it's a Next.js topic not a next-i18next topic
