### ISSUE TITLE
vscode does not show next-i18next `useTranslation` import, add an `index.d.ts`

### ISSUE THREAD

**Issue by ryanmr** [i18next/next-i18next#2069]
## 🚀 Feature Proposal

Recently I had an issue where I had to swap react-i18next imports for next-i18next imports, to prevent text mismatch errors.

```diff
-import { useTranslation } from "react-i18next";
+import { useTranslation } from "next-i18next";
```

I realized the reason I imported `react-i18next` is because vscode doesn't seem to list the `next-i18next` import during auto-import or auto-complete.

![Screen Shot 2022-12-29 at 11 17 01 AM](https://user-images.githubusercontent.com/13507/209987369-5c64e005-ae2f-4953-afdd-6752fdb466e8.png)

## Motivation

I think this would reduce errors and make it a bit nicer.

## Implementation

[`react-i18next` has an `index.d.ts`](https://github.com/i18next/react-i18next/blob/master/index.d.ts#L73) file, and I think that's what's providing vscode the hints it needs to handle the auto-imports. It should be pretty easy to reuse the same type here in this version of the library. I see the `useTranslation` is being [re-exported here](https://github.com/i18next/next-i18next/blob/master/src/index.tsx#L5).

Just something to think about.

Thanks!

**Comment by adrai** [comment]
Happy to review a PR.

**Comment by sanshao** [comment]
Same question

**Comment by KBeDevel** [comment]
@ryanmr Using the [code explorer](https://www.npmjs.com/package/next-i18next?activeTab=explore) of npmjs.com, you can see that under `next-i18next/dist/types` there IS an `index.d.ts`. Perhaps VS Code is resolving `react-i18next` because the declaration file is exporting it from the same package.

`next-i18next/dist/types/index.d.ts`:
```typescript
export { I18nContext, Trans, Translation, useTranslation, withTranslation, } from 'react-i18next';
export { appWithTranslation, globalI18n as i18n, } from './appWithTranslation';
```
