### ISSUE TITLE
next-i18next cant access translation

### ISSUE THREAD

**Issue by gunsela92** [i18next/next-i18next#2070]
I can access the translation on components folder but cant access translation on pages folder. I want to set document.title before page loads but its changing after page rendered. So seo is not working as expected. If i remove **i18next-http-backend** from config its working but if i remove it, i cant access the translations on components. If pages folder is working components not, and if components folder working pages not.

[I created a sandbox here.](https://codesandbox.io/p/sandbox/focused-noyce-eryxe0?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A16%7D%5D)

My config:

    const HttpBackend = require('i18next-http-backend');
    const detector = require("i18next-browser-languagedetector");
    /*const {initReactI18next} = require("react-i18next");*/
    
    module.exports = {
      debug: true,
      i18n: {
        defaultLocale: 'tr',
        locales: ['en', 'tr']
      },
      use: [
        detector,
        HttpBackend
        /*initReactI18next,*/
      ],
        /** To avoid issues when deploying to some paas (vercel...) */
      localePath:
        typeof window === 'undefined'
          ? require('path').resolve('./public/locales')
          : '/locales',
    
      reloadOnPrerender: process.env.NODE_ENV === 'development',
      serializeConfig: false,
      react: { useSuspense: false }
    }

_document.js:

    import { Html, Head, Main, NextScript } from 'next/document'
    import i18nextConfig from '../next-i18next.config'
    
    export default function Document(props) {
      const currentLocale = props.__NEXT_DATA__.locale ?? i18nextConfig.i18n.defaultLocale
    
      return (
        <Html lang={currentLocale}>
          <Head>
            <meta charSet="utf-8" />
          </Head>
          <body>
            <Main />
            <NextScript />
          </body>
        </Html>
      )
    }

_app.js:

    import store from "../redux/store";
    import {Provider} from "react-redux";
    import CustomThemeProvider, {AppContainerWrapper} from "../Providers/themeProvider";
    import Navbar from "../Components/Navbar";
    import nextI18NextConfig from '../next-i18next.config.js'
    import {appWithTranslation} from "next-i18next";
    import Alerts from "../Components/Alerts";
    import CookiePopupModal from "../Components/CookiePopup";
    import Footer from "../Components/Footer";
    import React, {useEffect, useState} from "react";
    import {useRouter} from "next/router";
    
    function App({ Component, pageProps }) {
      const router = useRouter();
      const [isHome, setIsHome] = useState(false);
    
      useEffect(() => {
        if (router?.pathname === "/") {
          setIsHome(true);
        }
      }, [router]);
    
      return (
          <Provider store={store}>
            <CustomThemeProvider>
              <Navbar />
              <Alerts />
              <AppContainerWrapper isHome={isHome}>
                <Component {...pageProps} />
              </AppContainerWrapper>
              <CookiePopupModal />
              <Footer />
            </CustomThemeProvider>
          </Provider>
      )
    }
    
    export default appWithTranslation(App, nextI18NextConfig)

cookie-policy/index.js (this is where the useTranslation not accessing before render):

        import React from "react";
        import { useTranslation } from 'next-i18next'
        import {CookiePolicyContainer} from "../../styles/cookie-policy/style";
        import PageWrapper from "../../Components/PageWrapper";
        import CookieServices from "../../Services/cookie.services";
        import Head from "next/head";
        
        export async function getServerSideProps({ locale }) {
      // Fetch data from external API
      const res = await CookieServices.fetchCookiePolicy()
      const data = await res?.data;
      const lang = {
        ...(await serverSideTranslations(locale, [
          'common',
          'pageTitles',
        ]))
      }
      return { props: { data, lang } }
        
        const CookiePolicy = ({data}) => {
          const {policyText} = data?.length > 0 ? data[0] : <></>;
          const {t} = useTranslation('pageTitles')
        
          return (
            <>
              <Head>
                <title>{t("cookiePolicy")}</title>
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
              </Head>
              <PageWrapper>
                <CookiePolicyContainer dangerouslySetInnerHTML={{ __html: policyText }} />
              </PageWrapper>
            </>
          );
        };
        
        export default CookiePolicy;

  [1]: https://codesandbox.io/p/sandbox/focused-noyce-eryxe0?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A45%2C%22endLineNumber%22%3A30%2C%22startColumn%22%3A45%2C%22startLineNumber%22%3A30%7D%5D

**Comment by adrai** [comment]
Your getServerSideProps function is wrong...
you need to adapt it like this:

here: https://codesandbox.io/p/sandbox/focused-noyce-eryxe0?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A13%7D%5D
```diff
-return { props: { lang } };
+return { props: { ...lang } };
```

and also make sure you use the correct namespace separator:
here: https://codesandbox.io/p/sandbox/focused-noyce-eryxe0?file=%2FComponents%2FcustomComponent.tsx&selection=%5B%7B%22endColumn%22%3A65%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A3%2C%22startLineNumber%22%3A6%7D%5D
```diff
-return <div>Custom Component : {t("common.commonTest")}</div>;
+return <div>Custom Component : {t("common:commonTest")}</div>;
```

and here: https://codesandbox.io/p/sandbox/focused-noyce-eryxe0?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A29%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A28%7D%5D
```diff
-<code className={styles.code}>{t("pageTitles.titleone")}</code>
+<code className={styles.code}>{t("pageTitles:titleone")}</code>
```
<img width="428" alt="image" src="https://user-images.githubusercontent.com/1086194/210132005-a03bd563-44c3-4d81-9c85-a65cb2a8625f.png">

**Comment by gunsela92** [comment]
I removed the http-backend and language detector modules. Now im getting `Hydration failed because the initial UI does not match what was rendered on the server.` error.

**Comment by adrai** [comment]
Please check your logs... this is probably because you're rendering a div (custom component) in a p element...

**Comment by gunsela92** [comment]
Damn. Thank you
