### ISSUE TITLE
next-i18next.config.cjs not loaded automatically

### ISSUE THREAD

**Issue by maxmellen** [i18next/next-i18next#2074]
## 🐛 Bug Report

User config is not found automatically if using a `.cjs` (or `.mjs`) extension, it only seems to work if using the `.js` extension, i.e. `next-i18next.config.js`.

This would add convenience/remove confusion for users of projects such as [`create-t3-app`](https://github.com/t3-oss/create-t3-app) which inits all of its config files with either `.cjs` or `.mjs` extensions being explicit on whether they use ESM or CommonJS syntax.

I am aware the config could be passed in manually, but I think the developer experience would still benefit from these additional supported defaults.

## To Reproduce

Here's two CodeSandboxes showcasing the issue.

One with the `.js` config file working as expected: https://codesandbox.io/p/sandbox/next-i18next-demo-good-zm88ok
One with the `.cjs` extension failing to start: https://codesandbox.io/p/sandbox/next-i18next-demo-bad-vdi3x5

<details><summary><strong>Full error message</strong></summary>

```
error - Error: next-i18next was unable to find a user config
    at _callee$ (/project/sandbox/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:92:19)
    at tryCatch (/project/sandbox/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/project/sandbox/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/project/sandbox/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/project/sandbox/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/project/sandbox/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at /project/sandbox/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at /project/sandbox/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12
    at serverSideTranslations (/project/sandbox/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:156:17)
    at getServerSideProps (webpack-internal:///./pages/index.tsx:29:113)
    at Object.renderToHTML (/project/sandbox/node_modules/next/dist/server/render.js:507:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (/project/sandbox/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/project/sandbox/node_modules/next/dist/server/base-server.js:828:28)
    at async /project/sandbox/node_modules/next/dist/server/response-cache/index.js:83:36 {
  page: '/'
}
```

</details>

## Expected behavior

User config should be automatically loaded regardless of whether it is named `next-i18next.config.js` or `next-i18next.config.cjs`. Ideally `next-i18next.config.mjs` should also be supported

## Your Environment

Initially found on my machine with the following environment

- *runtime version*: node v16.17.1, Firefox Developer Edition 109.0b8
- *i18next version*: 22.4.8
- *os*: macOS 13.1
- found when trying to add `next-i18next` to `create-t3-app@6.12.0`

**Comment by adrai** [comment]
feel free to provide a PR to address this

**Comment by maxmellen** [comment]
Hi @adrai!
Thanks for reaching back out so fast :)
Any pointers as to where I can find the relevant code for this?

**Comment by adrai** [comment]
@maxmellen https://github.com/i18next/next-i18next/blob/master/src/serverSideTranslations.ts#L12

**Comment by MadaShindeInai** [comment]
Any news about this? Still an issue

**Comment by adrai** [comment]
Feel free to provide a PR

**Comment by belgattitude** [comment]
@maxmellen @MadaShindeInai 

My 2 cents about this: Explicitly pass the `next-i18next.config.[js|cjs|mjs]`. 

- The pro of this approach if it works in all situations and is insentive to where the package hoist the next-i18next package (ie: monstly in monorepos). 

Related to what @adrai mentionned above 

> https://github.com/i18next/next-i18next/blob/master/src/serverSideTranslations.ts#L12


- The cons you'll have to maintain the wrapper (a little) whenever a next-i18next version changes the signature of [serverSideTranslations()](https://github.com/i18next/next-i18next/blob/master/src/serverSideTranslations.ts)


How to:

1. in _app.tsx

   ```tsx
   // _app.tsx
   import type { AppProps } from 'next/app'
   import { appWithTranslation } from 'next-i18next'
   import nextI18NextConfig from '../next-i18next.config.cjs'   /// <- cjs here
   const MyApp = ({ Component, pageProps }: AppProps) => (
     <Component {...pageProps} />
   )
   export default appWithTranslation(MyApp, nextI18NextConfig)
   ```

2. For `getServerSideProps()` and `getStaticProps()` the recommended approach is
   to wrap our [serverSideTranslations()](https://github.com/i18next/next-i18next/blob/master/src/serverSideTranslations.ts) in a separate file where you can inject the
   configuration.

   ```typescript
   // ie: ./lib/i18n/getServerTranslations.ts
   import type { Namespace } from 'i18next';
   import type { SSRConfig, UserConfig } from 'next-i18next'
   import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
   import nextI18nextConfig from '../../next-i18next.config.cjs' // <- cjs

   type ArrayElementOrSelf<T> = T extends Array<infer U> ? U[] : T[];

   export const getServerTranslations = async (
     locale: string,
     namespacesRequired?: ArrayElementOrSelf<Namespace> | undefined,
     configOverride?: UserConfig,
     extraLocales?: string[] | false
   ): Promise<SSRConfig> => {
     const config = configOverride ?? nextI18nextConfig
     return serverSideTranslations(locale, namespacesRequired, config,  extraLocales)
   }
   ```

   And use it instead of `serverSideTranslations`:

   ```typescript
   import { getServerTranslations } from '@/lib/i18n';
   const i18nNamespaces = ['demo'];

   export default function DemoRoute(
      props: InferGetStaticPropsType<typeof getStaticProps>
   ) {
     // ...
   }

   export const getStaticProps: GetStaticProps<Props> = async (context) => {
      const { locale } = context;
      return {
        props: {
          ...(await getServerTranslations(locale, i18nNamespaces)),
        },
      };
   };
   ```

See also https://github.com/i18next/next-i18next/blob/master/TROUBLESHOOT.md#how-to-explicitly-pass-the-config

**Comment by belgattitude** [comment]
@adrai in the light of https://github.com/i18next/next-i18next/pull/2084, I might rewrite https://github.com/i18next/next-i18next/blob/master/TROUBLESHOOT.md#how-to-explicitly-pass-the-config. Haven't seen the PR. Wdyt ?

**Comment by intpp** [comment]
@maxmellen you could use the latest version of the package `13.2.2` and fix your issue by environment variable `I18NEXT_DEFAULT_CONFIG_PATH`

```dotenv
I18NEXT_DEFAULT_CONFIG_PATH=./next-i18next.config.cjs
```

I have forked your example and updated the package, then added .env with the path, and it works.
https://codesandbox.io/p/sandbox/next-i18next-demo-bad-forked-0mr39m?file=%2F.env

More: https://github.com/i18next/next-i18next#custom-next-i18nextconfigjs-path

**Comment by adrai** [comment]
> @adrai in the light of #2084, I might rewrite https://github.com/i18next/next-i18next/blob/master/TROUBLESHOOT.md#how-to-explicitly-pass-the-config. Haven't seen the PR. Wdyt ?

yes, feel free @belgattitude

**Comment by maranomynet** [comment]
I can't believe it's mid 2024 and `next-i18next` doesn't work in esm projects (with `pkg.type === 'module'`).

Fixing this should be as easy as using dynamic `import()` to load load the config instead of old-school `require()`

**Comment by adrai** [comment]
I can write this also a third time: "feel free to provide a PR to address this" ;-)

**Comment by maranomynet** [comment]
I can't believe it's mid 2024 and `next-i18next`at version 15 doesn't work in esm projects (with `pkg.type === 'module'`).

It seems that [this dynamic `import()`](https://github.com/i18next/next-i18next/blob/master/src/serverSideTranslations.ts#L47) gets incorrectly transpiled into this:

<img width="536" alt="image" src="https://github.com/i18next/next-i18next/assets/86827/47e9e0d8-a9f4-47d6-b221-db591920e390">

which breaks things.

I'm running Nextjs 14.2.4 and the latest of everything, and still this broken commonjs version of serverSideTranslations.js is being loaded.

Fixing this requires more than just following a casual link to line 12 of `serverSideTranslations.ts` and making edits there. There's obviously more to it.

**Comment by maranomynet** [comment]
So, the root of the problem is maybe not so much the lack of support for other config file suffixes (that's more of a symtom), but rather the lack of support for the config file's module syntax being allowed to follow the rest of the parent project.

The source code is already doing The Right Thing, by using `import()` (which will ingest both module formats without a hitch).

What's failing seems to be the project's transpilation strategy, and changing that would IMO normally involve the participation of a project maintainer/owner, not some rando making blind-stab PRs.

**Comment by adrai** [comment]
@belgattitude do you have some time to look into that?

**Comment by maranomynet** [comment]
FWIW, here's the workaround I'm using, and seems to work:

My package.json has 

```json
  "type": "module",
```

I have a `next-i18next.config.cjs` and at the top I add this:
```js
process.env.I18NEXT_DEFAULT_CONFIG_PATH = __filename;
```

In `next.config.js` I import the i18n config like this:
```js
const { i18n } = await import('./next-i18next.config.cjs').then((mod) => mod.default);

```

Not exactly pretty, but hey! 🤷
