### ISSUE TITLE
I'm redirected to the localization json /fr/_next/data/development/fr/spaces.json instead the page

### ISSUE THREAD

**Issue by Steffi3rd** [i18next/next-i18next#2077]
## 🐛 Bug Report

Sometimes, I'm a change url from one to another, I'm not redirected to good url, instead I'm redirect to the localization file of the page. This bug exists in dev and also production mode. I don't understand how but it's not 100% the behavior. 90% of the time is OK, I reach the page I want, 10% of the time, I reach the localization use by the page. 

Click on a link and redirect using `router.push(url)` or `window.location.href = url`

## To Reproduce

<img width="1624" alt="Capture d’écran 2023-01-11 à 11 10 35" src="https://user-images.githubusercontent.com/814410/211783728-25057344-2637-480b-b685-70f87b593b19.png">

## Expected behavior

I excepted to always reach the page.

## Your Environment

-  "next": "11.1.0",
- "next-i18next": "8.10.0",
- *os*: Mac

**Comment by adrai** [comment]
Hard to investigate without a minimsl reproducible example.
