### ISSUE TITLE
Alternative Solution for getServerSideProps

### ISSUE THREAD

**Issue by innonguyen** [i18next/next-i18next#2086]
## 🐛 Bug Report

To use next-i18next, we need to call `serverSideTranslations ` during `getStaticProps` or  `getServerSideProps` depends on the use case.

When it comes to `getServerSideProps`, the NextJS `getServerSideProps` had a very slow loading for the first time as described in https://github.com/vercel/next.js/discussions/12447

I would like to avoid `getServerSideProps` in my dynamic pages but it's required if we want to use `serverSideTranslations`

Do we have other ways to get serverSideTranslations instead of `getServerSideProps`?

Please do not that, moving from `getServerSideProps` to `getStaticProps` is not a solution.

**Comment by adrai** [comment]
I don't know of any other alternative... sorry.
