### ISSUE TITLE
Switching between languages breaks and triggers infinite network calls when using useSuspense: true, and client-side-only translations

### ISSUE THREAD

**Issue by danielmarcano** [i18next/next-i18next#2095]
## 🐛 Bug Report

Switching between languages by using Next.js built-in internationalized routing is breaking and triggering infinite Network calls if:

- We set `{ react: { useSuspense: true } }` inside the `next-i18next.config.js` file's configuration object
- We load our translations on the client-side by following [this guide](https://github.com/i18next/i18next-http-backend/tree/master/example/next#client-side-loading-of-translations-via-http), and set: `backendOptions: [{ expirationTime: 0 }]` (in development, to prevent caching translations if we are manipulating them while developing the app) inside the `next-i18next.config.js` file

## To Reproduce

A [codesandbox](https://codesandbox.io/p/github/danielmarcano/next-i18next-use-suspense-error/main?workspaceId=9297ae8a-8175-4748-8b30-6d300126bb95&file=%2Fsrc%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D) that reproduces the error

In short, we can reproduce this bug by:

- Adding client-side-only translations by following [this guide](https://github.com/i18next/i18next-http-backend/tree/master/example/next#client-side-loading-of-translations-via-http) and adding all necessary packages
- Adding `{ react: { useSuspense: true } }` and `backendOptions: [{ expirationTime: 0 }]` to the `next-i18next.config.js` object

```js
// next-i18next.config.js

const HttpBackend = require("i18next-http-backend/cjs");
const ChainedBackend = require("i18next-chained-backend").default;
const LocalStorageBackend = require("i18next-localstorage-backend").default;

const ONE_HOUR_IN_MILISECONDS = 60 * 60 * 1000;

module.exports = {
  backend: {
  backendOptions: [{ expirationTime: process.env.NODE_ENV === 'production' ? ONE_HOUR_IN_MILISECONDS : 0 }],
    backends:
      typeof window !== "undefined" ? [LocalStorageBackend, HttpBackend] : [],
  },
  serializeConfig: false,
  use: typeof window !== "undefined" ? [ChainedBackend] : [],
  i18n: {
    locales: ["en", "es"],
    defaultLocale: "en",
  },
  defaultNs: "common",
  react: {
    useSuspense: true,
  },
};

```

- Passing such object to `appWithTranslation` inside the `_app.tsx` file
- Wrapping our app with `Suspense`

```tsx
import { Suspense } from "react";
import type { AppProps } from "next/app";
import { appWithTranslation, UserConfig } from "next-i18next";

import i18nConfig from "$/../next-i18next.config";

function App({ Component, pageProps }: AppProps) {
  return (
    <Suspense fallback="Loading...">{<Component {...pageProps} />}</Suspense>
  );
}

export default appWithTranslation(App, i18nConfig as UserConfig);

```

- Trying to switch between languages from a page of our app that uses translations (without adding a `getStaticProps` nor a `getServerSideProps` function)

```tsx
// src/views/HomeView.tsx

import Link from "next/link";
import { useTranslation } from "next-i18next";

export function HomeView() {
  const { t } = useTranslation("common");

  return (
    <div>
      <div>
        <Link href="/" locale="en">
          next/link: {t("changeLanguageToEnglish")}
        </Link>
      </div>
      <div>
        <Link href="/" locale="es">
          next/link: {t("changeLanguageToSpanish")}
        </Link>
      </div>
      <p>{t("mission")}</p>
    </div>
  );
}

```

```tsx
// src/pages/index.tsx

import { HomeView } from "$/views/Home";
import { NextPage } from "next";

const Home: NextPage = () => {
  return <HomeView />;
};

export default Home;

```

- When trying to switch to a language different than the one automatically detected by Next.js as explained [here](https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection), we get infinite Network calls (we can only stop them by clicking on the language detected by Next.js, as shown in the video):

https://user-images.githubusercontent.com/93147810/220634644-4a89e68f-2a54-4999-96dc-fc2a1cd7b4f3.mov

## Expected behavior

- As far as I have understood, and being unable to find more information regarding this matter on the docs, it should be possible to set `expirationTime` to `0` in development, and not having the app break when switching between languages

## Your Environment

- *runtime version*: node v16.18.1, Chrome 110.0.5481.100
- *next-i18next version*: "13.1.5"
- *i18next version*: "22.4.10"
- *i18next-chained-backend version*: "4.2.0"
- *i18next-http-backend version*: "2.1.1"
- *i18next-localstorage-backend version*: "4.1.0"
- *os*: macOS 13.2

P.S. Thank you all for your great work!

## Workaround

I have realized that by simply passing that `ONE_HOUR_IN_MILISECONDS` to the `backendOptions.expirationTime` regardless of the environment, the issue is solved.

```ts
// const ONE_HOUR_IN_MILISECONDS = 60 * 60 * 1000;

// ...
  backendOptions: [{ expirationTime: ONE_HOUR_IN_MILISECONDS }],
// ...
```

We were using it so that the development translations were always the most recent ones, so as to always have the latest translation changes while developing on `localhost` since caching the translations is not something that we want/need in this environment.

I wonder if, somehow, we can keep this functionality without breaking the app when switching between languages...

**Comment by danielmarcano** [comment]
I have realized that by replacing that `0` with a `60 * 60 * 1000`, just like in the client-side-only translations [guide](https://github.com/i18next/i18next-http-backend/tree/master/example/next#client-side-loading-of-translations-via-http), the issue is solved!

**Comment by adrai** [comment]
Never use Suspense with next.js so far, seems like Next.js renders the page in the infinite loop in that case.
I would suggest you use the lazy-reload approach instead of the pure client-loading approach (even better in newer Next.js versions): https://github.com/i18next/i18next-http-backend/commit/efb1aba69d41275c518c40b8df7bd955a073c3d4

**Comment by danielmarcano** [comment]
Thanks for the information, @adrai! I will try that other approach.

**Comment by loristns** [comment]
AFAIK, if you want to keep some pages rendered entirely client-side, you may not be able to use the lazy-load approach as it requires calling getServerSideProps, getStaticProps (and getAllPaths if the route is dynamic). In such cases, pure client-side loading seems preferable.

**Comment by adrai** [comment]
If someone knows of how that infinite loop could be prevented... (basically prevent Next.js to render that page infinitely)... feel free to contribute... it might also be a bug in Next.js?
