### ISSUE TITLE
Add strict typing to locale when using const { locale } = useRouter()

### ISSUE THREAD

**Issue by sunknudsen** [i18next/next-i18next#2098]
## 🚀 Feature Proposal

Created a `i18next.d.ts` file so that `t` is strictly typed… wonderful.

Now, when using `const { locale } = useRouter()` to get current locale, would be amazing if type of `locale` was set to type of `locales` configured in ` next-i18next.config.js` (`"en" | "fr"` for following config).

```javascript
module.exports = {
  i18n: {
    defaultLocale: "fr",
    locales: ["en", "fr"],
    reloadOnPrerender: process.env.NODE_ENV === "development",
  },
}
``` 

```tsx
const { locale } = useRouter()
```

Current type of `locale` is `string | undefined`… would be amazing if type was `"en" | "fr"` so one could use `locale` as index.

**Comment by adrai** [comment]
Feel free to provide a PR if you know of an approach to achieve this.

**Comment by sunknudsen** [comment]
Hey @akshitkrnagpal, thanks for helping out… code snippet is an amazing workaround.

**Comment by sunknudsen** [comment]
Thanks to @akshitkrnagpal’s feedback and https://stackoverflow.com/a/75562135/4579271, I was able to put together following which appears to work.

**next-i18next.config.js**

```javascript
const defaultLocale = /** @type {"en" | "fr"} */ ("fr")
const locales = /** @type {(typeof defaultLocale)[]} */ (["en", "fr"])

module.exports = {
  i18n: {
    defaultLocale: defaultLocale,
    locales: locales,
    reloadOnPrerender: process.env.NODE_ENV === "development",
  },
}
```

**next-router.d.ts**

```typescript
import { NextRouter } from "next/router"
import { i18n } from "../next-i18next.config"

declare module "next/router" {
  export type Locale = typeof i18n.defaultLocale
  export function useRouter(): Omit<NextRouter, "locale" | "locales"> & {
    locale: Locale
    locales: Locale[]
  }
}
```
