### ISSUE TITLE
Must provide all namespaces in ns option if using a function as localePath

### ISSUE THREAD

**Issue by Arjan-Zuidema** [i18next/next-i18next#2102]
## 🐛 Bug Report

Unclear error: `Error: Must provide all namespaces in ns option if using a function as localePath`

Am I doing something wrong? If so, the docs are very unclear about how to use this.

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
module.exports = {
  i18n: {
    defaultLocale: 'nl',
    locales: ['nl', 'en'],
  },
  localePath: (locale, namespace) => {
    return `./public/locales/${namespace}/${locale}.json`;
  }
}
```

## Expected behavior

Load the locales

## Your Environment

- *runtime version*: Node 16
- *i18next version*: 22.4.10
- *os*: Mac

**Comment by adrai** [comment]
Just do what the error says.

```js
module.exports = {
  i18n: {
    defaultLocale: 'nl',
    locales: ['nl', 'en'],
  },
  localePath: (locale, namespace) => {
    return `./public/locales/${namespace}/${locale}.json`;
  },
  ns: ['ns1', 'ns2']
}
```

**Comment by Arjan-Zuidema** [comment]
Alright, that seems to fix that error. Error message is not really clear about that tbh.

But now the next error:
```
SerializableError: Error serializing `._nextI18Next.userConfig.localePath` returned from `getServerSideProps` in "/invoices".
Reason: `function` cannot be serialized as JSON. Please only return JSON serializable data types.
```

```js
module.exports = {
  i18n: {
    defaultLocale: 'nl',
    locales: ['nl', 'en'],
  },
  localePath: (locale, namespace) => {
    return `./public/locales/${namespace}/${locale}.json`;
  },
  ns: ['common', 'invoices']
}
```

I can fix this by using `localeStructure` instead of `localePath` but I think the config about should work, right? 
```js
module.exports = {
  i18n: {
    defaultLocale: 'nl',
    locales: ['nl', 'en'],
  },
  localeStructure: '{{ns}}/{{lng}}',
  ns: ['common', 'invoices']
}
```

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next#unserializable-configs

**Comment by Arjan-Zuidema** [comment]
Alright, case closed then. Error still unclear about that ns option. Maybe that can be fixed (using a link to some docs)
