### ISSUE TITLE
next-i18next breaks Next.js 13.2 app pages with dynamic segments

### ISSUE THREAD

**Issue by dmgawel** [i18next/next-i18next#2103]
## 🐛 Bug Report

When next-i18next is added to the Next.js 13.2 project, pages inside the app directory with [dynamic segments](https://beta.nextjs.org/docs/routing/defining-routes#dynamic-segments) (`[slug]`, etc.) stop working and return 404 error.

Please note, that it's not about when next-i18next is actually used inside the app directory. It's just the existence (adding it to the config file) that breaks the site.

The issue was not present in Next.js 13.1.

## To Reproduce

Minimal reproducible example: https://codesandbox.io/p/sandbox/stupefied-knuth-efwp5f?file=%2Fnext.config.js

It's a create-next-app with added next-i18next. Disable next-i18next in `next.config.js` to see the `/blog/test` page is working.

## Expected behavior

Adding next-i18next to the project should not break the `app/` directory. It should be possible to use next-i18next inside the `pages/` directory, until the `app/` support is added.

## Your Environment

- *runtime version*: node v14
- *i18next version*: 13.1.6
- *os*: Mac
- Next.js version: 13.2.1

**Comment by adrai** [comment]
This looks to not be a direct issue of next-i18next but a Next.js issue. Please open an issue at https://github.com/vercel/next.js
