### ISSUE TITLE
[Feature] Support experimental Next.js app dir and server components

### ISSUE THREAD

**Issue by jamsinclair** [i18next/next-i18next#2105]
## 🚀 Feature Proposal

I hope you don't mind me prematurely creating this issue 🙇 . Just wanted to start a discussion around the new Next.js App dir and potential support with i18next. This doesn't have to be built anytime soon but could be a chance to crowd-source information of potential approaches to adding support. 

## Motivation

Next.js v13+ includes an experimental app directory that aligns with the future of the React framework.

https://nextjs.org/blog/next-13#new-app-directory-beta 

## Example

_To be revisited once understanding of what is needed_

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/discussions/1993#discussioncomment-4337519

**Comment by adrai** [comment]
https://locize.com/blog/next-13-app-dir-i18n/
