### ISSUE TITLE
If the route is exact as language it ignores route sitename/en/en/ => sitename/en/

### ISSUE THREAD

**Issue by noidar** [i18next/next-i18next#2107]
## 🐛 Bug Report

Hello,
I am using next-i18next as i18n solution, my page structure is pages[country].
therefore the URL will be [http://localhost:3000/de[language]/de[country]/otherpage](http://localhost:3000/de%5Blanguage%5D/de%5Bcountry%5D/otherpage)
router.push('de/otherpage') it swaps de URL to http://localhost:3000/de/otherpage but should be http://localhost:3000/de/de/otherpage

## To Reproduce

here is the example:
https://github.com/noidar/next-18next-router-problem/blob/master/pages/index.js#L22

## Your Environment

- Node v16, 
- "i18next": "^22.4.10",
- "next": "latest",
- "next-i18next": "^13.2.1",
- Windows

**Comment by adrai** [comment]
This is probably an issue of the Link (next/link) component.

this should work:

```jsx
                <a href="/de/de/home?ReturnUrl=dasd">
                    /de/home?ReturnUrl=dasd
                </a>
```

You may open an issue at the [vercel/next.js](https://github.com/vercel/next.js) repo

**Comment by mainaani** [comment]
@adrai please have a look at my issue: https://stackoverflow.com/questions/75669684/why-my-next-i18next-isnot-working-and-even-though-translated-content-is-written

**Comment by adrai** [comment]
@mainaani do not pollute other issues on github! Create a minimal reproducible example repository and a new issue.

**Comment by mainaani** [comment]
@adrai sure will do

**Comment by noidar** [comment]
Found a temporary solution https://github.com/vercel/next.js/discussions/38414
