### ISSUE TITLE
You will need to pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by imsamdez** [i18next/next-i18next#2108]
## 🐛 Bug Report

I know this issue has been already reported, but since i'm having it even after following the setup steps on a fresh `npx create-next-app`, i'd like to make sure i'm not missing something.

## To Reproduce

https://github.com/imsamdez/issue.next-i18next
This is a fresh project created with `npx create-next-app`, followed by the setup of next-i18next.
After running `npm run dev`, we can see that the warning is there.

## Expected behavior

Setup should be correct and should not return a warning.

## Your Environment

- *runtime version*: node16
- *i18next version*: 13.2..1
- *os*: Mac

**Comment by adrai** [comment]
Where do you call serverSideTranslations?


<img width="602" alt="image" src="https://user-images.githubusercontent.com/1086194/223636293-509a2988-81c6-4592-961f-9e814c473810.png">

**Comment by adrai** [comment]
btw: the warning during the compilation can't be removed if t function is used in layout components...

**Comment by adrai** [comment]
To prevent it you could do https://github.com/i18next/next-i18next/issues/1917#issuecomment-1193339399 if it disturbs you:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/1086194/223637829-400a4e76-ab2d-497e-88f7-ec210bacbc26.png">

**Comment by imsamdez** [comment]
Hey Adrai,

Thanks for the answers.

Since I was trying to translate something in the `Nav` component which is not at the page level I didn't think that I still had to set the `getStaticProps` on the page itself.
Works better with it in fact!
