### ISSUE TITLE
_error.tsx, initReactI18next & i18nextReactModule not initialized with getServerSideProps

### ISSUE THREAD

**Issue by other-yuka** [i18next/next-i18next#2110]
## To Reproduce
<img width="869" alt="image" src="https://user-images.githubusercontent.com/13997484/223853852-02000df5-b68e-4274-b739-c01a80195987.png">

https://user-images.githubusercontent.com/13997484/223856770-6371c53a-972c-4a6e-b88d-038540b5390e.mp4

use getServerSideProps, initReactI18next & i18nextReactModule is not initialized and an error is generated.
In the example above, 500 errors were forced when approaching `pages/second-page.tsx`.

https://github.com/other-yuka/next-i18next/tree/master/examples/simple

```js
import React from 'react';
import {Trans, useTranslation} from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import {GetServerSideProps} from "next";

const Error = () => {
  const { t } = useTranslation('footer')
  return (
    <div>
      <p>{t('description')}</p>
      <Trans i18nKey="helpLocize" t={t}>
        With using
        <a href="https://locize.com" target="_new">
          locize
        </a>
        you directly support the future of
        <a href="https://www.i18next.com" target="_new">
          i18next
        </a>
        .
      </Trans>
    </div>
  );
};

export default Error;

export const getServerSideProps: GetServerSideProps = async ({
                                                              locale,
                                                            }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? 'en', [
      'common',
      'footer',
    ])),
  },
})

```

## Expected behavior

initReactI18next & i18nextReactModule should pass normally.

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: node v16.19.0
- *i18next version*: 22.4.10
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
sorry, but I don't understand....
why are you throwing here: https://github.com/other-yuka/next-i18next/blob/master/examples/simple/pages/second-page.tsx#L43 ?
This is causing the issue...

**Comment by other-yuka** [comment]
Code to cause 500 errors on a part.

**Comment by adrai** [comment]
Sorry, I still don't understand....
Please explain why you are throwing that error, and what you expect to happen and why?

**Comment by other-yuka** [comment]
1. If the React code used in Next.JS generates a 500 error
2. If there is an error not caught by getServierSideProps

It is assumed that an uncaptured error occurs.

**Comment by adrai** [comment]
I don't think such an error should be handled automatically...
Remove the next-i18next usage and you will see it behaves the same.

I always get this:
<img width="996" alt="image" src="https://user-images.githubusercontent.com/1086194/223866703-8a7b705b-f0cc-4769-b76c-218f7add40b0.png">

Sorry, I'm not able to help you. Will going to sleep now.

**Comment by other-yuka** [comment]
`yarn build && yarn start`

this error occurs in production.

**Comment by adrai** [comment]
fyi: the getServerSideProps function in your _error.tsx file will never run. Only getInitialProps will work on that error page.
For more detail information about that behaviour you need to ask vercel/next.js
As long as the getServerSideProps function is ignore, there nothing we can do here.

**Comment by other-yuka** [comment]
404 error is a bug that works fine but does not work with 500 error.
`getServerSideProps` function in the `_error.tsx `file works fine.

https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-500-page
