### ISSUE TITLE
Support use of Turbopack

### ISSUE THREAD

**Issue by SoftMemes** [i18next/next-i18next#2113]
## 🚀 Feature Proposal

I'm not clear on whether this would require changes to next-i18next, to Turbopack in core Next, or both but currently turbopack refuses to load any configuration that contains extra bits beyond the very core settings, which includes the i18n property. If I remove this from the config, I am currently then getting a runtime error when attempting to run with turbopack: ```Error: Cannot find module 'next-i18next'```

I appreciate that Turbopack is in alpha, but would love to be able to use it as it has the potential to significantly speed up the local development experience.

## Motivation

Turbopack is most likely the future for local Next development and addresses my main concern with Next atm.

## Example

This has the potential to speed up the local development experience for anyone working on Next apps that use i18n!

**Comment by adrai** [comment]
Sorry, I don't know... never investigated.
Feel free to start a PR...

**Comment by laakal** [comment]
[Unsupported](https://github.com/vercel/turbo/issues/4859) Next.js configuration option(s) (next.config.js)
- i18n.locales
- i18n.defaultLocale

**Comment by ristomatti** [comment]
Those are not on the exclusion list on Next.js 14.2. We are however using `next-translate-routes` and it definitely doesn't play together with Turbpack.
