### ISSUE TITLE
Wrapper around _app.tsx not working 

### ISSUE THREAD

**Issue by enyelsequeira** [i18next/next-i18next#2115]
## 🐛 Currently I have a turborepo setup and I am using next-i18next, but I am getting the following error around typescript 

![image](https://user-images.githubusercontent.com/50872387/224381346-f6b48554-14da-42a9-ab10-d9918f908638.png)
![image](https://user-images.githubusercontent.com/50872387/224381731-9d113b67-8768-49fc-81c3-9d5f4b0f46b5.png)

## My package.json looks like this 
![image](https://user-images.githubusercontent.com/50872387/224381536-d4f78e7f-0480-4230-86e6-8054bcb8c7cb.png)

**Comment by adrai** [comment]
@belgattitude do you have experience with turborepo?

**Comment by enyelsequeira** [comment]
@adrai  I was reading upon this, and found this, it works right away but, not sure if this would be a good way or if there are any drawbacks to this though  https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1372144595

**Comment by adrai** [comment]
Sorry, I'm not a TS expert but maybe @pedrodurek can advice?

**Comment by belgattitude** [comment]
A bit of experience, does not look related to turbo. pnpm is always tricky. I'll see what I can do.

@enyelsequeira pnpm version ? settings you set in your .npmrc ?

**Comment by enyelsequeira** [comment]
@belgattitude  this is my `.npmrc`

```
auto-install-peers = true
node-linker = hoisted
```

I added this line and fixed the issue, though  as I commented above, not sure if this is the right way to go though 
and regarding `pnpm` version this is the one 

![image](https://user-images.githubusercontent.com/50872387/224447683-ca3d078e-f631-424c-b12b-4e5c902f264c.png)

**Comment by belgattitude** [comment]
Thanks. I don't think you need `node-linker=hoisted` anymore with pnpm 7.29.1. I'll update the doc.

Can you update your npmrc.

```
## PNPM related ###############
## https://pnpm.io/next/npmrc #
###############################

# Not always possible to be strict
# https://pnpm.io/next/npmrc#strict-peer-dependencies
strict-peer-dependencies=false

# Helps with size but generally don't work. It's the future anyway.
# https://pnpm.io/npmrc#auto-install-peers
auto-install-peers=false

# Helps locating duplicates, default in v8
# https://pnpm.io/next/npmrc#use-lockfile-v6
use-lockfile-v6=true

# Will fix duplicates due to peer-dependencies (>=7.29.0), default in v8
# https://github.com/pnpm/pnpm/releases/tag/v7.29.0
dedupe-peer-dependents=true

# Helps with peer-deps (>=7.23.0), default in v8
# https://pnpm.io/npmrc#resolve-peers-from-workspace-root
resolve-peers-from-workspace-root=true
```

Then run 

```
pnpm i
pnpm dedupe
```

That should avoid using.`node-linker=hoisted` (defeats pnpm advantages)

**Comment by enyelsequeira** [comment]
this seems to have fixed the issue, with the types. Thank you! interesting to see how each package manager handles different cases

**Comment by belgattitude** [comment]
Thanks for confirming @enyelsequeira ! PNPM was always tricky I'm glad they're moving forward.

@adrai I suggest we close this issue. I've added some notes in https://github.com/i18next/next-i18next/pull/2119. This kind of issue will disappear with upcoming pnpm v8.
