### ISSUE TITLE
Supporting subdirectories with `nsSeparator`

### ISSUE THREAD

**Issue by jimmy-e** [i18next/next-i18next#2121]
## 🐛 Bug Report

Hi, I want to use subfolders in my i18 files. I am trying to do that with the `nsSeparator` and the `keySeparator` configs. I am able to access the `common.yml` file, which is not a subfolder, however, when I try to access the value in `buttons/label.yml`, I am not returned a value. Please see the below screenshot. How can I use `nsSeparators` and `keySeparators` to support subdirectories in a namespace? Thank you!

![image](https://user-images.githubusercontent.com/25621956/224807935-699e20d0-faa5-4dd5-8d15-d56364015a5d.png)

## To Reproduce

To reproduce, please go to [this repository](https://github.com/jimmy-e/i18_debug), and do the following:

1. Run `npm install`
2. Run `npm run dev`
3. Open your browser to `http://localhost:3000/`

Relevant Code:

**next-i18next.config.js**
```js
module.exports = {
  defaultNS: false,
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  interpolation: {
    escapeValue: false,
  },
  keySeparator: '.',
  localeExtension: 'yml',
  localePath: './copy/',
  localeStructure: '{{ns}}',
  ns: ['common', 'legal', 'ui', 'button'],
  nsSeparator: '::',
};
```

**pages/index.tsx:**
```js
import React from 'react';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
        'ui',
      ])),
    },
  };
}

const Home: React.FC = () => {
  const { t } = useTranslation(['common', 'ui']);

  return (
    <>
      <h1>Common</h1>
      <p>{t('bar', { ns: 'common' })}</p>
      <h1>UI</h1>
      <p>{t('label', { ns: 'ui::button '})}</p>
    </>
  );
};

export default Home;
```

## Expected behavior

`t('label', { ns: 'ui::button '})` returns the value "Click Me"

## Your Environment

- *runtime version*: node 19.6.0, npm 9.4.0
- *i18next version*: ^22.4.11
- *os*: Mac Ventura 13.0

**Comment by adrai** [comment]
Sorry, maybe I'm not getting what you want to achieve, but your localeStructure option always needs to contain both parts, lng and ns => `{{lng}}/{{ns}}`
nsSeparator and keySeparator should not influence this... if so does your setup work with the default nsSeparator and default keySeparator?
Beside that, you may provide a minimal reproducible example to show exactly what you want to achieve and what you expect and what you get instead.

**Comment by jimmy-e** [comment]
Thanks, I provided a link to a minimal reproducible example, you can also find it [here]([this repository](https://github.com/jimmy-e/i18_debug)), I'm hoping it is really simple and straightforward, and the screenshot should point out that I am not getting the value I want in the red.

Currently, I do not need support for my namespaces to handle for different languages. That will happen to my codebase in about a year from now, but we still want to use this infrastructure.

In the meantime, we want have various folders, like below:
```
ui/
  |- buttons.yml
  |- inputs.yml
pages/
  |- homePage.yml
  |- userPage.yml  
```

And then a react component can do something like the below:

```
const Home: React.FC = () => {
  const { t } = useTranslation('ui');

  return (
      <p>{t('label', { ns: 'ui::button '})}</p>
  );
};
```

**Comment by adrai** [comment]
ahh now I undestand...
No, that's not possible.

**Comment by jimmy-e** [comment]
Thanks, I'm assuming I can do something like this however?

```
i18n/
  common/
    components/
      en.json
      es.json
    pages/
      en.json
      es.json
```

`t('common:components.button');`

**Comment by adrai** [comment]
only if "common" is fix and there's nothing else next to it....
So this would not work:

```
i18n/
  other/
    things/
      en.json
      es.json
  common/
    components/
      en.json
      es.json
    pages/
      en.json
      es.json
```

**Comment by jimmy-e** [comment]
hmm ok thanks 👍🏻 well, I'm working in a monorepo ... so I may try breaking these out to separate i18 instances with separate directories. 🫡

**Comment by EvilaMany** [comment]
Damn, but why it's not possible? I think it's a such a "default" behaviour to resolve namespace recoursively. In large project there are appears big mess if leave all translation files in one directory. I don't think it's a such hard task to add supporting it

**Comment by adrai** [comment]
> Damn, but why it's not possible? I think it should be "default" behaviour to resolve namespace recoursively. In large project there are appears big mess if leave all translation files in one directory. I don't think it's a such hard task to add supporting it 

Feel free to contribute with a PR, by maintaining also the compatibility with the existing ecosystem if you think it's not such a hard task to support it 🤷‍♂️

**Comment by EvilaMany** [comment]
In general it appears possible to pass custom resolver of namespace files to support this. But I should provide ns: [] property for reason I can't understand. It means every time I add new file of localization, I have to not forget add it to ns property, that may be confusing. Why can't the library just call the resolver when I try to load some namespace, and then load it with resolved path? Eventually I declare namespaces in getServerSideProps in each page
