### ISSUE TITLE
Translation is not working in component - displays key instead of value

### ISSUE THREAD

**Issue by damyco** [i18next/next-i18next#2122]
I have followed the docs and tried to use it in exactly the same way as in the example.

I have a Card component that uses:

```
import {useTranslation} from 'next-i18next';
const {t} = useTranslation('common');
```

then trying to use it as a text on the button:
`<button>{t('read_more')}</button>`

common.json file:
`{
  "read_more": "Button text!"
}`

I'm really not sure what I'm doing wrong... it will display the text as 'read_more' on the button rather than 'Button text!' I tried so many different things and have no clue why this is happening.

<img width="173" alt="image" src="https://user-images.githubusercontent.com/25842807/225027126-ef47d916-0241-410f-84de-8820f3486d15.png">

I'm using the translations from home.json on my index page and had no issues, the Card component is on that page.

```
export async function getStaticProps({previewData, locale}) {
    const client = createClient({previewData});

    const articles = await client.getAllByType('article', {limit: 3});

    return {
        props: {
            articles,
            ...(await serverSideTranslations(locale, [
                'home',
                'common',
            ] ))
        },
    };
}
```

I understand I could pass it to the component itself but I want a default value from translations on that component if it's not passed.

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next#translate-in-child-components

**Comment by damyco** [comment]
> https://github.com/i18next/next-i18next#translate-in-child-components

Yes, I'm trying to do point 3. but it's not working...

**Comment by adrai** [comment]
create a minimal reproducible example

**Comment by adrai** [comment]
here it seems to work: https://github.com/i18next/next-i18next/blob/e6b5085b5e92004afa9516bd444b19b2c8cf5758/examples/simple/components/Footer.tsx#L6

**Comment by damyco** [comment]
This is what leaves me confused if it works on your example, it's literally the same thing what I've got.

Here is minimal example, it doesn't work even as simple page :( 
```
import {serverSideTranslations} from 'next-i18next/serverSideTranslations';
import {useTranslation} from 'next-i18next';

export default function Test() {
    const {t} = useTranslation('common');
    return <p>{t('read_more')}</p>
}

export async function getStaticProps({locale}) {
    return {
        props: {
            ...(await serverSideTranslations(locale, ['common']))
        },
    };
}
```
<img width="200" alt="image" src="https://user-images.githubusercontent.com/25842807/225039265-975db9e9-2a58-4648-9e83-a05fa912cb7a.png">

**Comment by adrai** [comment]
This is not a reproducible example, this is just a code snippet, but try to set the debug option to true and check the logs for more information.

**Comment by adrai** [comment]
sorry, can't help without a reproducible example.... I suspect your config is wrong.

**Comment by damyco** [comment]
config:

```
module.exports = {
    i18n: {
        defaultLocale: 'en-GB',
        locales: ['en-GB', 'de-DE'],
    },
}
```
![image](https://user-images.githubusercontent.com/25842807/225044629-76582714-a051-4b2f-8973-26940e43a119.png)

Nothing out of ordinary here... mind you translations on index page are working fine, contained in home.json - I'll try to produce minimal example at some point later

**Comment by damyco** [comment]
@adrai 
All right, I got this sorted - looks like it was an issue with cache in dev or something, not sure why this happened though!

Before setting up an example for you I decided to test it on stackblitz - I forked my repo and it displayed the button text correctly - so to fix this I removed .next directory from my project and restarted the dev server.
