### ISSUE TITLE
Text content does not match server-rendered HTML

### ISSUE THREAD

**Issue by Ellathet** [i18next/next-i18next#2128]
## 🐛 Bug Report

When a use `t` function inside a component, next return to me, this error:
![image](https://user-images.githubusercontent.com/76699403/227313269-8f636fa9-0f94-4808-8b77-e81d80bdc6da.png), have any aformation about that?

## To Reproduce

I'm using [ChakraUI](https://chakra-ui.com), and Next with typescript, inside my component file a had this code:

```tsx
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { GetStaticProps } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'react-i18next'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { t } = useTranslation('common')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {t('title')}
      </main>
    </>
  )
}

export const getStaticProps : GetStaticProps = async ({locale}) => {
  const lang = {
    ...(await serverSideTranslations(locale ?? 'en', ["common"])),
  };
  return { props: { ...lang } };
}
```
## Your Environment

- *runtime version*: v16.16.0
- *next version*:v13.2.4
- *i18next version*: v22.4.13
- *os*: Windows

**Comment by adrai** [comment]
I suspect somewhere the serverSideTranslations call is missing.

Please create a minimal reproducible example repository.

**Comment by Ellathet** [comment]
Oh, of course:
https://stackblitz.com/edit/nextjs-vdsybj?file=pages/index.js
This the same version, and code...

**Comment by adrai** [comment]
I don't know exactly why, but your setup seems not to automatically load the config.
So by doing this, it should work:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1086194/227440892-46284c87-90da-4bab-95ef-e634b21d0442.png">

**Comment by IvanTC95** [comment]
I think the problem is that you are using `useTranslation` from `react-i18next`, and you should be using it from `next-i18next`

**Comment by adrai** [comment]
> I think the problem is that you are using `useTranslation` from `react-i18next`, and you should be using it from `next-i18next`

Yes, for sure this is an issue.

**Comment by andrejoaquim-dc** [comment]
Hey @adrai! Sorry for bringing this up again but why do we need to import `useTranslation` from `next-i18next`? I'm building a component library for React and Next.js applications and I'd like to always import from `react-i18next`.

**Comment by adrai** [comment]
You need to always import it from next-i18next to ensure the correct instance is taken.

**Comment by lucasalmeida92** [comment]
Maybe this tutorial should be updated to import `useTranslation` from `next-i18next` ?
https://locize.com/blog/next-13-app-dir-i18n/

**Comment by adrai** [comment]
@lucasalmeida92 That tutorial does not use next-i18next... it does not use the pages setup of Next.js but the new app router approach.

**Comment by lucasalmeida92** [comment]
So do you have any ideias on how do I solve the problem? I'm receiving same error as Ellathet.

`Warning: Text content did not match. Server: "Practice account" Client: "Conta real"`

`on-recoverable-error.js:21 Uncaught Error: Text content does not match server-rendered HTML.`

`Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.`

**Comment by adrai** [comment]
If it's not the wrong import statement, please provide a minimal reproducible example repository and create a new issue.

**Comment by lucasalmeida92** [comment]
Just found this in Nextjs docs:
![image](https://github.com/i18next/next-i18next/assets/5767871/de0f5eef-22a5-4d63-ae17-a7686209b717)
And in Locize tutorial:
![image](https://github.com/i18next/next-i18next/assets/5767871/de9a8cd7-6b1c-49df-a99b-0dc8fad89e57)

Maybe thats is the problem?

**Comment by adrai** [comment]
You're still mixing Next.js pages and Next.js app router setups.
These are 2 completely different setups.
For the pages setup use next-i18next for the app router setup follow https://locize.com/blog/next-13-app-dir-i18n/

If you still have problems create a minimal reproducible example and create a new github issue.

**Comment by mateo2181** [comment]
@adrai I am experiencing the same issue using pages setup. Do you know I am doing anything wrong? 

`next-i18next.config.js`
```javascript
/** @type {import('next-i18next').UserConfig} */
module.exports = {
  i18n: {
    defaultLocale: 'es',
    locales: ['en', 'es'],
  },
  localePath: typeof window === 'undefined' ? require('path').resolve('./public/locales') : '/locales',
}
``` 

`pages/index.tsx`
```typescript
import Maincontent from '@/components/MainContent'
import Features from '@/components/Features'
import WaitingListForm from '@/components/WaitingListForm'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import nextI18nextConfig from '../../next-i18next.config'

export default function Home() {
  return (
    <>
      <Maincontent />
      <WaitingListForm />
      <Features />
    </>
  )
}

export async function getStaticProps({ locale }: { locale: any }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common']), nextI18nextConfig, ['en', 'es']),
      // Will be passed to the page component as props
    },
  }
}
``` 

`components/MainContent.tsx`
```typescript
import React from 'react'
import Image from 'next/image'

import forestImage from '@/assets/forest1.jpeg'
import Container from '@/components/Container'
import { useTranslation } from 'next-i18next'


export default function Maincontent() {

  const { t } = useTranslation('common')

  return (
    <Container>
      <section className="grid lg:grid-cols-2 place-items-center pt-8 pb-8 md:pt-12 md:pb-12">
          <h1 className="text-5xl lg:text-6xl xl:text-7xl font-bold lg:tracking-tight xl:tracking-tighter">
            {t('title')}
          </h1>
      </section>
    </Container>
  )
}
```

### Environment
Node: v20.10.0
Next: 14.0.3
i18next: 23.8.2
next-i18next: 15.2.0
react-i18next: 14.0.5

**Comment by adrai** [comment]
@mateo2181 please provide a complete but minimal reproducible example repository, not just code snippets

**Comment by mateo2181** [comment]
@adrai you can see the example here: https://codesandbox.io/p/live/fe44db84-d827-46b8-9365-cc11e557884f

**Comment by adrai** [comment]
You passed the arguments to the serverSideTranslations function in the wrong way...

```diff
export async function getStaticProps({ locale }: { locale: any }) {
  return {
    props: {
-      ...(await serverSideTranslations(locale || "es", ["common"]),
+       ...(await serverSideTranslations(locale || "es", ["common"],
      nextI18nextConfig,
-      ["en", "es"]),
+      ["en", "es"])),
      // Will be passed to the page component as props
    },
  };
}

```


and also remove the resourcesToBackend part here:

```diff
/** @type {import('next-i18next').UserConfig} */

module.exports = {
  debug: process.env.NODE_ENV === "development",
  i18n: {
    defaultLocale: "es",
    locales: ["en", "es"],
  },
  // localePath: typeof window === 'undefined' ? require('path').resolve('./public/locales') : '/locales',
  react: {
    useSuspense: false,
  },
-  resourcesToBackend: (language, namespace) =>
+  //resourcesToBackend: (language, namespace) =>
-    require("path").resolve(`./public/locales/${language}/${namespace}.json`),
+    //require("path").resolve(`./public/locales/${language}/${namespace}.json`),
  // webpack5: true,
  // webpack: (config) => {
  //   config.resolve.fallback = { fs: false, path: false };
  //   return config;
  // },
};

```

**Comment by mateo2181** [comment]
Thank you so much @adrai! It's working with those changes. :raised_hands:

**Comment by mmmmd233** [comment]
> i have a same problem, my project using react-i18next, how to solve problem if i still using react-i18next, or i have to change to next-i18next? tks

Hello, have you solved this problem?tks

**Comment by Ellathet** [comment]
> > i have a same problem, my project using react-i18next, how to solve problem if i still using react-i18next, or i have to change to next-i18next? tks
> 
> Hello, have you solved this problem?tks

Yes, just import from next-i18next instead react-i18next

**Comment by mislavmiocevic** [comment]
I have same issue when using Trans component and only on mobile devices.

```
import { Trans, useTranslation } from 'next-i18next';

<Trans
  ns="tos"
  i18nKey="1.1"
  components={{
    strong: <strong />,
  }}
/>
```

```
"i18next": "~23.11.5",
"next": "~14.2.13",
"next-i18next": "~15.3.0",
```

`Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

`​Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`
