### ISSUE TITLE
404 Page issue

### ISSUE THREAD

**Issue by kilofeq** [i18next/next-i18next#2134]
## 🐛 Bug Report

There is an issue with 404 pages with the deployed app on Vercel. xyz.com/404 is working perfectly and static translations are working well. Unfortunately, when you're trying to access a "real" 404 page like /asdasd translations are visible only for a fraction of a second and then fallback keys are shown.

## To Reproduce

Create a Next.js app, and then create a custom 404.tsx page with the getStaticProps translations fetcher. Then try to access a non-existing page.

```js
export async function getStaticProps (pageContext: NextPageContext) {
	const locale = pageContext.locale
	return {
		props: {
			...(await serverSideTranslations(
				locale,
				config.languageNamespaces,
				nextI18NextConfig
			))
		}
	}
}
```

## Expected behavior

Not disappearing translations on 404 pages.

## Your Environment

- *runtime version*: i.e. node v16
- *i18next version*: i.e. 22.4.9
- *deploy*: vercel

**Comment by adrai** [comment]
If it works locally, please ask in the vercel/next.js repo.
