### ISSUE TITLE
`i18n` is `null` in getServerSideProps on app startup

### ISSUE THREAD

**Issue by arishoham** [i18next/next-i18next#2136]
## 🐛 Bug Report

When starting up our nextjs app, we import `i18n` to be used in getServerSideProps, however, the module does not exist initially, and returns null.

How do we wait for/account for this prior to starting the app?

![image](https://user-images.githubusercontent.com/48421483/230480594-70e10c72-15fa-4564-a359-49669bd32182.png)

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
import { i18n } from 'next-i18next';

export const getServerSideProps = async ({ locale }) => {
  const t = i18n.getFixedT(locale);
  return { props: {} }
}
```

## Expected behavior

No error, and `getFixedT` exists on the i18n object

## Your Environment

- *runtime version*: i.e. node v18.12.1
- *i18next version*: 22.4.9
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
#2079

**Comment by arishoham** [comment]
@adrai so no fix/workaround right now?

**Comment by arishoham** [comment]
Are there any other fixes/workarounds that you know of? @adrai
