### ISSUE TITLE
Change language without locale router

### ISSUE THREAD

**Issue by flashgrimmie** [i18next/next-i18next#2137]
## 🚀 Feature Proposal

I am gonna implement i18n without having locale routes in url. By default it adds locale routing like `https://mywebsite.com/en`

## Motivation

I don't want to mess up my website routes.

## Example

I hope I can change the language without using locale routing. I can change it inside app by having toggle or selection.
i.e. https://gopluslabs.io/

**Comment by flashgrimmie** [comment]
Btw, do you have any support or community channels? It's a bit hard to find any of your team contacts to reach out and get help ...

**Comment by flashgrimmie** [comment]
Saw this [blog](https://iamsannyrai.medium.com/i18n-in-next-js-without-sub-path-or-domain-routing-2443c1a349c6) but it uses `ni18n`

**Comment by adrai** [comment]
No, next-i18next is based on Next.js feature of internationalized routing.

**Comment by adrai** [comment]
fyi: with app directory setup: https://github.com/i18next/next-13-app-dir-i18next-example/issues/12#issuecomment-1500917570

**Comment by jmcannon** [comment]
I want the same thing. I noticed on gopluslabs.io, you managed route without the language suffix in your urls @flashgrimmie - what was your solution?
