### ISSUE TITLE
Weird problem with nexti18 and input placeholder

### ISSUE THREAD

**Issue by Andrzej-Marek** [i18next/next-i18next#2138]
## 🐛 Bug Report
Hello, I'm using [next-i18next](https://github.com/i18next/next-i18next) with a Next.js v12 in my app. All translations work completely fine, except one weird problem. My app start on a `/login` page, and everything is translated, except input placeholders. It is not different is it a native input or custom component.

If I add to my component 
```js
  if (typeof window === "undefined") {
    return null;
  }
```
Then is working fine.

**Have you ever had a problem like that?**

## config

```js
  i18n: {
    defaultLocale: "en",
    locales: ["en", "pl"],
    localePath: path.resolve("./public/locales"),
  },
```

## login page SSP (nextjs)

```js
export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale!, ["auth", "common"])),
    },
  };
};
```

## Your Environment

- *next*:  12.1.0
- *react*:  17
- *next-i18next*: "13.2.2",
-  *i18next*: "22.4.14",

**Comment by adrai** [comment]
Please provide a minimal reproducible example.
