### ISSUE TITLE
Include html tags in a translation 

### ISSUE THREAD

**Issue by franktronics** [i18next/next-i18next#2139]
According to the documentation the only way to include tags is to use the component Trans. but it does not work in component server with Next.js

**Comment by adrai** [comment]
For sure this works: https://github.com/i18next/next-i18next/blob/592c790c12b630ca51eedff7c02e61d87a54aca7/examples/simple/pages/index.tsx#L39

**Comment by aronmal** [comment]
I also tried these settings in my config as ChatGPT suggested:
```
  react: {
    useSuspense: false,
  },
  useHtmlString: true,
```

But also didn't work

**Comment by adrai** [comment]
The example proves the normal usage of the [Trans component](https://react.i18next.com/latest/trans-component) works: [next-i18next/examples/simple/pages/index.tsx](https://github.com/i18next/next-i18next/blob/592c790c12b630ca51eedff7c02e61d87a54aca7/examples/simple/pages/index.tsx#L39)

So please provide a minimal reproducible example repository that shows your issue

**Comment by aronmal** [comment]
In my site.tsx, I have:

```
import { Trans, useTranslation } from "next-i18next"

...
            <Trans i18nKey="driving_experience" />
...
```

The `locals/de/common.json`:
```
{
  "driving_experience": "Das <b>Fahrgefühl</b> ist ..."
}
```

The next-i18next.config.js
```
// @ts-check

/**
 * @type {import('next-i18next').UserConfig}
 */
module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "de"],
  }
}
```
But on my /de/site page, I get `Das <b>Fahrgefühl</b> ist ...` instead of bold text. 

With `t()` from `useTranslation` and/or `useHtmlString` no other result.

**Comment by adrai** [comment]
the <b> element is not part of transKeepBasicHtmlNodesFor
<img width="801" alt="image" src="https://user-images.githubusercontent.com/1086194/233084622-7fd58f4f-05dd-499b-a7d8-eeb2fe10813e.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/1086194/233084657-02945613-79dc-43b3-8b9b-924045f92371.png">
https://react.i18next.com/latest/trans-component#usage-with-simple-html-elements-like-less-than-br-greater-than-and-others-v10.4.0

So use <strong> or define your own transKeepBasicHtmlNodesFor, i.e.

```js
module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "de"],
  },
  react: {
      transKeepBasicHtmlNodesFor: ['br', 'strong', 'i', 'p', 'b']
  }
}
```

**Comment by aronmal** [comment]
No, sry. I am on a train right now and the page was loading poorly. Must have missed it. Thanks.

**Comment by k-zakhariy** [comment]
@adrai this works fine `<Trans i18nKey="blog.appDir.answer"> `

but i'm trying to have another use case, with namespaces.
I added in simple example examples/simple/pages/second-page.tsx:

`<Trans i18nKey="footer:helpLocize">With using <a href="test">locize</a> you directly support the future of <a href="/">i18next</a>.</Trans>`

And it works, but i have an **TS** error for the **i18nKey**

Type '"footer:helpLocize"' is not assignable to type 'string & (ParseKeys<"common", {}, undefined> | ParseKeys<"common", {}, undefined>[] | undefined)'.ts(2322)
second-page.tsx(30, 8): The expected type comes from property 'i18nKey' which is declared here on type 'IntrinsicAttributes & { children: (string | Element)[]; i18nKey: string; } & { children?: TransChild | readonly TransChild[]; components?: readonly ReactElement<...>[] | ... 1 more ... | undefined; ... 10 more ...; t?: TFunction<...> | undefined; }'


Could you give an advice what i'm doing wrong ?

Thanks in advance

**Comment by adrai** [comment]
Pass the namespace vi ns property: 

`<Trans ns="footer" i18nKey="helpLocize">`
