### ISSUE TITLE
SSG default locale to be without subfolder prefix

### ISSUE THREAD

**Issue by Kureyko** [i18next/next-i18next#2143]
## SSG

Is there an option to have `defaultLocale`, let's say `en` to be directly in `out` folder?

**Goal is to get rid of locale prefix for default language:**
- `en` home `example.com`
- `en` about `example.com/about`
- `de` home `example.com/de`
- `de` about `example.com/de/about`

**But currently it's like:**
- `en` home `example.com/en`
- `en` about `example.com/en/about`
- `de` home `example.com/de`
- `de` about `example.com/de/about`

### SSG output example
- out
    - _next
    - 404
    - de
        - index.html
        - about.html
    - it
        - index.html
        - about.html
    - en <-- this folder should be extracted directly to the `out` folder
    - index.html <-- `en` home
    - about.html <-- `en` about

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/blob/master/examples/ssg/pages/index.js

**Comment by adrai** [comment]
Then adapt the switcher logic to use / instead of /en if locale === 'en'

**Comment by robbiecren07** [comment]
Do you mean something like this:
`
if (locale === 'en') {
    href = rest.href ? `/${rest.href}` : pName
  } else {
    href = rest.href ? `/${locale}${rest.href}` : pName
  }
`

**Comment by adrai** [comment]
not verified (afk) but yes
