### ISSUE TITLE
Retrieve `t()` translation in `getStaticProps`?

### ISSUE THREAD

**Issue by benmvp** [i18next/next-i18next#2144]
(first off thanks for putting this library together! 🙏🏾  it's much better than having to roll my own framework combining `react-i18n` and Next.js. very much appreciated.)

## Documentation issue

I've been searching through the docs, closed issues, and examples, but cannot seem to find an answer. Even ChatGPT doesn't have a workable solution 😆 

I need to call `t()` function _within_ `getStaticProps`. We have the `locale` within `getStaticProps` so is it possible to construct a `t()`?

## Motivation

I want to pre-render a page within an object that is retrieved async and has a translation in it. That way I don't have to render a blank/loading page and retrieve the object client-side.

We can document whether or not this works either in the main docs or at least stored in this issue.

## Example code

```tsx
// categories/[slug].tsx

interface PageProps {
  activeCategory?: CategoryData | null;
  departments?: CategoryData[];
}

export const getStaticProps: GetStaticProps<
  PageProps,
  { slug: string }
> = async ({ locale = 'en-US', params }) => {
  const translations = await serverSideTranslations(locale, ['common']);

  // is it possible to get `t()` from `translations`??

  // pass `t()` here
  const activeCategory = await getCategory(t, params?.slug || '');
  const departments = await getDepartments(t, { count: 8 });

  return {
    props: {
      ...translations,

      // `null` indicates that the category was not found
      activeCategory: activeCategory || null,
      departments,
    },
  };
};

const Page: NextPage<PageProps> = ({ activeCategory, departments }) => {
  // want to avoid having to call `getCategory` and `getDepartments` here 

  if (!activeCategory || !departments) {
    return;
  }

  if (activeCategory === undefined) {
    return <Loading />;
  }

  if (activeCategory === null) {
    return <NotFound />;
  }

  // render page and such...
};
```

**Comment by adrai** [comment]
You can try to do something like this:

```js
import { createInstance } from 'i18next'
//...

export const getStaticProps: GetStaticProps<Props> = async ({
  locale,
}) => {
  const tr = (await serverSideTranslations(locale ?? 'en', [
    'common',
    'footer',
  ]))
  const i18n = createInstance({
    lng: tr?._nextI18Next?.initialLocale,
    ns: tr?._nextI18Next?.ns,
    resources: tr?._nextI18Next?.initialI18nStore,
  })
  i18n.init()
  console.log(i18n.t('h1', { ns: 'common' }))

  return {
    props: {
      ...tr,
    },
  }
}
```

**Comment by benmvp** [comment]
This worked perfectly! I did have to spread in `tr?._nextI18next?.userConfig` into `createInstance like:

```ts
const i18n = createInstance({
  ...nextI18Next?.userConfig,
  lng: nextI18Next?.initialLocale,
  ns: nextI18Next?.ns,
  resources: nextI18Next?.initialI18nStore,
});
```

I needed it mainly to pull in my custom `interpolation`.

I also used this pattern to manually create a wrapper `I18nextProvider` around Jest tests with `@testing-library/react`. For anyone else curious, something like:

```ts
// since this a mock omit the namespace filtering
const translations = await serverSideTranslations(mockLocale);

const { _nextI18Next: nextI18Next } = translations
const i18n = createInstance({ ... });

i18n.init();

render(<MyComponentWithTranslations />, {
  wrapper: ({ children}) => (
    <I18nextProvider i18n={i18n}>
      {children}
    </I18nextProvider>
  ),
});
```

Thank you, thank you, thank you for the quick response and direction @adrai! 🙏🏾

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
