### ISSUE TITLE
use `i18next-http-backend` not working

### ISSUE THREAD

**Issue by yuuk** [i18next/next-i18next#2147]
## 🐛 Bug Report

No `loadPath` api requested after running the project

## To Reproduce

here is a example repo

https://github.com/yuuk/next-i18n-backend-demo

dependencies

```js
"dependencies": {
    "i18next": "latest",
    "i18next-http-backend": "latest",
    "next": "latest",
    "next-i18next": "latest",
    "react-i18next": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
```

next-i18next.config

```js
const HttpBackend = require("i18next-http-backend/cjs");

const isDev = process.env.NODE_ENV === "development";

module.exports = {
  debug: isDev,
  backend: {
    loadPath: "http://localhost:3000/api/locales?lng={{lng}}&ns={{ns}}",
    addPath: "http://localhost:3000/api/locales?lng={{lng}}&ns={{ns}}",
    requestOptions: {
      mode: "no-cors",
      cache: "default",
    },
  },
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },
  serializeConfig: false,
  use: [HttpBackend],
};

```

## Expected behavior

Can load resources from api

- *runtime version*: node v14.18.0

**Comment by adrai** [comment]
You need to define also the ns option, to "preload" the namespaces:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/1086194/234840658-592e64d8-41ad-4fe7-acc9-5412586a60ac.png">

and the returned namespace json should be correct:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/1086194/234840756-9d5ab34a-d742-4462-99a6-2cb4ee7ad256.png">

**Comment by yuuk** [comment]
> You need to define also the ns option, to "preload" the namespaces: <img alt="image" width="791" src="https://user-images.githubusercontent.com/1086194/234840658-592e64d8-41ad-4fe7-acc9-5412586a60ac.png">
> 
> and the returned namespace json should be correct: <img alt="image" width="858" src="https://user-images.githubusercontent.com/1086194/234840756-9d5ab34a-d742-4462-99a6-2cb4ee7ad256.png">

Thanks~
