### ISSUE TITLE
Is there any ways to override translations when use `serverSideTranslations` ?

### ISSUE THREAD

**Issue by yuuk** [i18next/next-i18next#2149]
## 🚀 Feature Proposal

For some reason, I  cannot use `i18next-http-backend` to load remote translations, such as I cannot obtain environment variables in  `next-i18next.config.js` to distinguish development or production (we create environment variables in CD).

## Motivation

Can load translations from backend in `serverSideTranslations`.

## Example

```js
export const getServerSideProps = async (ctx) => {
    const locales = await fetchLocalesApi(); // load translations from backend
    const i18nProps = await serverSideTranslations(ctx.locale, ['common', 'edit', 'boarding'], {
        ...nextI18nextConfig,
        serializeConfig: true,
        resources: {
            ...locales
        },
    });
    return {
        props: {
            ...i18nProps,
        },
    };
};
```

**Comment by adrai** [comment]
Sorry, I don't understand...
You can modify the return value of serverSideTranslations however you like... it's just a prop 🤷‍♂️

**Comment by yuuk** [comment]
> Sorry, I don't understand... You can modify the return value of serverSideTranslations however you like... it's just a prop 🤷‍♂️

Thx for your prompt reply. modifying  `initialI18nStore` prop  right?

**Comment by adrai** [comment]
yes, just try
