### ISSUE TITLE
import { i18n } from "next-i18next"; works on apis/functions, but not when built

### ISSUE THREAD

**Issue by nibblesnbits** [i18next/next-i18next#2150]
## 🐛 Bug Report

With the work-around from [this comment](https://github.com/i18next/next-i18next/issues/462#issuecomment-832793454), I'm able to get i18n to work great *on the server side* when running a Next project with `next dev`, but after `next build`, the `i18n` object coming out of `import { i18n } from "next-i18next";` is `null`.

## To Reproduce

A [minimal reproducible example](https://github.com/nibblesnbits/next-i18next-demo).

```js
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { i18n } from "next-i18next";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const t = i18n?.isInitialized ? i18n.t : await i18n!.init();
  res.status(200).json({ message: t("api") as string });
}

```

## Expected behavior

I expect the output of `t("api")` to be the text "api" in my demo code.

```jsson
{ "message": "api" }
```

## Actual behavior

`i18n` is null, but **ONLY** when the project is built, NOT when running via `next dev`.

## Your Environment

- *runtime version*: node 18.x
- *i18next version*: 22.4.15
- *os*: Mac
- *next-i18next version*: 13.2.2

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/issues/2079#issuecomment-1386970151
https://github.com/i18next/next-i18next/issues/2136

**Comment by nibblesnbits** [comment]
Neither of these things really address the core issue.  Something is obviously different in the built version of the code.  Why would it work perfectly fine when running in Dev mode, but not when built?

**Comment by adrai** [comment]
because dev mode runs a webserver so i18next is probably initialized

**Comment by nibblesnbits** [comment]
So as many have asked before, is the an actual reliable way of using this lib on the backend?  Is it even intended to be used that way?  If not, is there an approach outside this lib that works for the backend you're aware of?

**Comment by adrai** [comment]
fyi: your example works also when built...
I run npm run build and then npm start and it seems to work

**Comment by adrai** [comment]
alternatively, do something like this:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/1086194/235480201-adf98bd9-9910-4e6a-9976-3655b66cc1e8.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/1086194/235480280-739d3e64-d516-451e-99c4-11de9d5f1ef5.png">

**Comment by nibblesnbits** [comment]
So that seems to pull in the i18n properly, BUT it's not pulling in the resources.  The result of the `t()` call just returns the identifier. Again, works in dev, but not after a build.

**Comment by Zhukreal** [comment]
> dev

the same for me (( 
it works locally, but not after deploying to Vercel
