### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by rakhmonovbekzod** [i18next/next-i18next#2156]
./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:34:0
Module not found: Can't resolve 'fs'

**Comment by adrai** [comment]
Please check the other issues and provide a minimal reproducible example.
https://github.com/i18next/next-i18next/discussions/1810
https://github.com/i18next/next-i18next/issues/935
https://github.com/i18next/next-i18next/issues/1401
https://github.com/i18next/next-i18next/issues/980
https://github.com/i18next/next-i18next/issues/1010

**Comment by benetche** [comment]
I think it occurs when you try to use something like this:

```ts
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export async function getServerSideProps({ locale = 'en' }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
      ])),
    },
  };
}
```
inside a file which is not in the ```src/pages/``` path. \
You will need to add this structure to your page-level component.
