### ISSUE TITLE
Cannot use appWithTranslation  on app/layout.tsx

### ISSUE THREAD

**Issue by 2531800823** [i18next/next-i18next#2158]
## Documentation issue

  "next": "13.4.1",  "next-i18next": "^13.2.2",   
## Motivation
Cannot use appWithTranslation  on app/layout.tsx
Please outline the motivation for the proposal.

**Comment by adrai** [comment]
If you use the new app directory setup, please follow this: https://locize.com/blog/next-13-app-dir-i18n/
like also adviced in the readme:
![image](https://github.com/i18next/next-i18next/assets/1086194/933ab5cc-be1d-46bb-bb15-f762d38f8c76)

and also here: https://next.i18next.com/
