### ISSUE TITLE
getNamespaces function does not includes localeStructure

### ISSUE THREAD

**Issue by MarcARoberge** [i18next/next-i18next#2161]
I am currently looking into the code because our `localeStructure` config was not working without `ns` config and I found that the `getNamespaces` function inside the `createConfig` file is not taking the localeStructure option. Maybe we can improve it with something like:

`combinedConfig.localeStructure.split("{{ns}}"}` to then add it to the `localePath`

I can create a PR if it seems reasonable

**Comment by adrai** [comment]
I don't know exactly what you mean... Maybe first create a minimal example that explains exactly what you want?

**Comment by adrai** [comment]
btw: at least 1 namespace is necessary

**Comment by MarcARoberge** [comment]
What I meant is if the user change the `localeStructure` config, the function `getNamespaces` does not work since it assumed the path is going to be: `localePath/locale`. 

Let say you have a folder structure like this:

```
home
    - en.json
    - fr.json
error
    - en.json
    - fr.json
```
and a config with `localeStructure: "{{ns}}/{{lng}}"`, the function will not work since `localePath/locale` does not exist.

Then, theses lines will not work 

```
const namespacesByLocale = locales.map(locale =>
            getLocaleNamespaces(
              path.resolve(process.cwd(), `${localePath}/${locale}`)
            )
          )
```

**Comment by adrai** [comment]
feel free to try a PR
