### ISSUE TITLE
route locale subpath disappear when currentLanguage is defaultLanguage

### ISSUE THREAD

**Issue by stark-eth** [i18next/next-i18next#2163]
## 🚀 Feature Proposal

I want to make the locale subpath always in route

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by adrai** [comment]
https://nextjs.org/docs/pages/building-your-application/routing/internationalization#prefixing-the-default-locale

<img width="684" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/910dfe06-9ebd-47cf-81b4-1ec53b9d6ace">


```diff
  i18n: {
-    defaultLocale: 'en',
-    locales: ['en', 'de'],
+    defaultLocale: 'default',
+    locales: ['default', 'en', 'de'],
  },

```
