### ISSUE TITLE
Duplicate content on defaultLocale

### ISSUE THREAD

**Issue by ricoxor** [i18next/next-i18next#2165]
Is it possible to redirect the defaultLocale path to the root domain to avoid duplicate?

Currently the defaultLocale is displayed with these two paths :
- domain.com/
- domain.com/fr

Same for the deep pages :
- domain.com/game/game-one
- domain.com/fr/game/game-one

Is there a way to avoid this and always redirect the /fr to no lang path ?

next-i18next.config.js :

```
/** @type {import('next-i18next').UserConfig} */

module.exports = {
    i18n: {
        defaultLocale: 'fr',
        locales: ['fr', 'en', 'de', 'it', 'es', 'nl', 'he', 'sv', 'da', 'ja', 'nb', 'tr'],
    },
};
```

Thank you in advance

**Comment by adrai** [comment]
That's a next.js feature, not an next-i18next feature...
https://github.com/i18next/next-i18next/issues/2163#issuecomment-1565469128
