### ISSUE TITLE
404 translation not work with middleware next-i18next nextjs

### ISSUE THREAD

**Issue by roninaruka** [i18next/next-i18next#2166]
Translation work on all pages but only on 404 page after 1 sec only translation var prints 

## To Reproduce
Reproduce [Github](https://github.com/roninaruka/next-i18next-404-middleware-issue-recreate)
Reproduce [Vercel](https://next-i18next-404-middleware-issue-recreate.vercel.app/)

issue only come when i use middleware
without middleware its working fine

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/issues/2134#issuecomment-1491543987

**Comment by roninaruka** [comment]
@adrai Thanks for reply 
can you please write solution here

**Comment by adrai** [comment]
The solution is to ask the Vercel team, since locally it seems to work.

**Comment by roninaruka** [comment]
when we run using "npm run build && npm run start" is also issue not only vercel server

**Comment by adrai** [comment]
Ahh you mean the translations are not coming...
Yes, that's the nature of how next.js handles not existing pages...
The getStaticProps function is not executed for those inexisting routes.... that's why there are no translations.
This could be a workaraound: https://github.com/roninaruka/next-i18next-404-middleware-issue-recreate/pull/1/files

**Comment by adrai** [comment]
```tsx
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetStaticProps } from "next";
import { useTranslation, SSRConfig, i18n as globali18n } from "next-i18next";
import Link from "next/link";
import { useState, useEffect } from 'react';

export default function Page404Component(props) {
    const [ lastData, setLastData ] = useState<SSRConfig>()
    useEffect(() => {
        if (!props._nextI18Next) {
            if (lastData) {
                Object.keys(lastData._nextI18Next.initialI18nStore).forEach((l) => {
                    Object.keys(lastData._nextI18Next.initialI18nStore[l]).forEach((n) => {
                        globali18n.addResources(l, n, lastData._nextI18Next.initialI18nStore[l][n])
                    })
                })
                globali18n.changeLanguage(lastData._nextI18Next.initialLocale)
            }
            return
        }
        setLastData(props)
    }, [props])

    const { t } = useTranslation("common");

    return (
        <>
            <h2>{t("NotFoundTitle")}</h2>
            <p>{t("NotFoundBelow")}</p>
            <Link href="/">Home</Link><br />
            <Link href="/about-us">About us</Link><br />
            <Link href="/en">en</Link><br />
            <Link href="/fr">fr</Link>
        </>
    );
}


// import { getStaticProps } from "./index";
// export { getStaticProps };
type Props = {};
export const getStaticProps: GetStaticProps<Props> = async ({ locale }) => {
    console.log('serverSideTranslations... ' + locale)
    return {
        props: {
            ...(await serverSideTranslations(locale ?? "en", ["common"])),
        },
    }
};
```

**Comment by roninaruka** [comment]
@adrai Thanks for your solution but now one more issue in that is not work with level 2 object key 
https://github.com/roninaruka/next-i18next-404-middleware-issue-recreate/commit/05b9306dc028d41028871f45c11e35228349bc1b

**Comment by adrai** [comment]
try addResourceBundle, instead: https://github.com/roninaruka/next-i18next-404-middleware-issue-recreate/pull/2
<img width="806" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/143f0d18-deb8-4102-865b-840370c7b763">

**Comment by roninaruka** [comment]
@adrai thanks solution work fine with my all pages
