### ISSUE TITLE
Support for architectural adjustments in Next v13.4.4

### ISSUE THREAD

**Issue by ashlyWeiting** [i18next/next-i18next#2170]
## 🐛 Bug Report

With the architectural changes in Next v13.4.4, the entry point has been changed from pages/_app.tsx to app/layout.tsx. As a result, next-i18next is no longer functioning properly.

## To Reproduce
1. Create v13.4.4 next repo
2. Setup next-i18next
4. i18n not working

## Your Environment
- node: v16.19.1
- next: v13.4.4
- i18next: 22.5.0
- next-i18next: 13.3.0
- react-i18next: 12.3.1

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/issues/2158#issuecomment-1556205214
