### ISSUE TITLE
`reloadOnInterval` feature similar to `reloadOnPrerender`

### ISSUE THREAD

**Issue by theabdulmateen** [i18next/next-i18next#2173]
## 🚀 Feature Proposal

Related to https://github.com/i18next/i18next-fs-backend/issues/38

Would it be possible to have a `reloadOnInterval` similar to `reloadOnPrerender`? 

I am interested in fetching the latest locales after the cache expires (Please refer to `expirationTime` in the cache setup mentioned in the issue above.). From my understanding, the only way we can refetch the locales with `i18next-http-backend` is to make use of `reloadOnPrerender`.

Which would [reload the translations whenever `serverSideTranslations` is called](https://github.com/i18next/next-i18next#reloading-resources-in-development) 
- what does this mean exactly? Does it fetch locales from fs and store it in-memory given cache has not expired yet?
- How does it affect the performance overall?

## Motivation

To make use of a cache layer with `expirationTime` e.g. in `i18next-fs-backend`

## Example

This will be used to fetch the latest locales after the cache expires. It would go hand in hand with `expirationTime` of the cache layer.

**Comment by adrai** [comment]
update the i18next-chained-backend dependency and try to set the reloadInterval like here: https://github.com/locize/next-i18next-locize/blob/local-caching/next-i18next.config.js/node.js#L9

**Comment by theabdulmateen** [comment]
That does it. It's exactly what I was looking for, thank you again for the insanely fast response and updates. I really appreciate it.
