### ISSUE TITLE
Warning: Text content did not match. Server: "heroTitle1" Client: "Get your DApp"

### ISSUE THREAD

**Issue by happycodeweb3** [i18next/next-i18next#2178]
## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

Repo reference:
https://github.com/MakeWeb3/MakeWeb3.io

1. open console
2. warning exists

https://github.com/i18next/next-i18next/assets/135591894/137ef952-3281-459d-92d3-50f711d517cb

<img width="251" alt="Screenshot 2023-06-18 at 4 26 10 PM" src="https://github.com/i18next/next-i18next/assets/135591894/e17fd660-760b-464b-86b8-532a04089eb2">

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v16
- *i18next version*: i.e. "^23.0.2",
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Instead of `import { useTranslation } from 'react-i18next'`
-> `import { useTranslation } from 'next-i18next'`

https://github.com/i18next/next-i18next#usetranslation
![image](https://github.com/i18next/next-i18next/assets/1086194/719e5b4a-beb3-477e-be9b-93c83ff006bc)

**Comment by happycodeweb3** [comment]
Thanks!
