### ISSUE TITLE
It occurs error when returning only footer when using serverSideTranslations

### ISSUE THREAD

**Issue by ey920911** [i18next/next-i18next#2180]
## 🐛 Bug Report

I have common.json, footer.json  files on  publice/locales/${lang} directory
And I want to use only  footer.json file like below.

`export default function MyComponent() {
  const { t, i18n } = useTranslation('footer')`

First, i return just 'footer'  like  ...(await serverSideTranslations(locale, ['footer'])),   
But it occured "Error: Text content does not match server-rendered HTML."

It's work well that return  ['common', 'footer'] 
```

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

  export async function getStaticProps({ locale }) {
    return {
      props: {
  +    ...(await serverSideTranslations(locale, ['common', 'footer'])), // Success  
  -    ...(await serverSideTranslations(locale, ['footer'])),   // Error
      },
    };
  }
```

Is it impossible just return one file that I using except common file ?

**Comment by adrai** [comment]
Please provide a complete reproducible example repository.

If you're using our simple example, that is giving an error because the common namespace is used, so it is required.

ServerSideTranslations will load all namespaces that are used on a page... also translations used un a subcomponent...
