### ISSUE TITLE
Usage example for ESM

### ISSUE THREAD

**Issue by nick4fake** [i18next/next-i18next#2185]
When you use ESM you get this error:

````
Error: require() of ES Module /app/next-i18next.config.js from /app/....../next-i18next/dist/commonjs/serverSideTranslations.js not supported.
````

Relevant issue:
https://github.com/i18next/next-i18next/issues/1505

**Comment by nick4fake** [comment]
After changing import to:

````typescript
import { serverSideTranslations } from "next-i18next/dist/esm/serverSideTranslations";
````

It shows another error:

````
SyntaxError: Cannot use import statement outside a module
````

**Comment by nick4fake** [comment]
Looks like this module doesn't use "exports" field, and "module" field is not supported officialy:
https://nodejs.org/api/packages.html#exports

**Comment by adrai** [comment]
I suspect also having an exports field would not fix the problem...
Next.js is somehow always trying to load the commonjs build...
https://github.com/vercel/next.js/issues/39375

If you know of a solution that will work for all environments feel free to provide a PR... I was not able to solve this :-(

**Comment by nick4fake** [comment]
This also might be the reason:
https://github.com/i18next/next-i18next/blob/master/serverSideTranslations.js

When importing next-i18next/serverSideTranslations it always uses commonjs format

**Comment by adrai** [comment]
> This also might be the reason: https://github.com/i18next/next-i18next/blob/master/serverSideTranslations.js
> 
> When importing next-i18next/serverSideTranslations it always uses commonjs format

no, I also tried to change that... the main problem is that Next.js wants the exports to be with .mjs ending... and that does not work with modules imported conditionally for browser order node.js side...

**Comment by nick4fake** [comment]
Ah, I seee. So far I've tried lots of options, including (putting here for reference):

Forcing mainFields (looks like it is already by default) [ref](https://github.com/vercel/next.js/issues/5616):
````typescript
config.resolve.mainFields = isServer
     ? ["module", "main"]
     : ["browser", "module", "main"];
````

Making package external (just to test):
````typescript
config.externals = [...config.externals, "next-i18next"];
````

Directly including the file:
````typescript
import { serverSideTranslations } from "next-i18next/dist/esm/serverSideTranslations.js";
````

Rewriting alias:
````typescript
config.resolve.alias = {
      ...config.resolve.alias,
      "next-i18next$": "PATH_TO_MODULE/dist/esm/index.js",
};
````

So far I haven't foudn even a workaround, unfortunately.

**Comment by adrai** [comment]
yes, there's a way:

1. rename `next.config.js` to `next.config.cjs`
2. rename `next-i18next.config.js` to `next-i18next.config.cjs` 
3. if you have some imports in your code for the next-i18next.config or next.config adapt them to the .cjs variant

**Comment by nick4fake** [comment]
@adrai Chaning Sorry, forgot about the simplest option :)

Yeah, thanks. BTW, we don't need to change next-i18next.config.js if we simply don't include next-i18next.config.cjs there (duplicating i18n config).

**Comment by nick4fake** [comment]
Though now I have a different issue:

````
Error: Text content does not match server-rendered HTML.

Warning: Text content did not match. Server: "KEY_IN_TRANSLATION" Client: "REAL_TRANSLATION_VALUE"

See more info here: https://nextjs.org/docs/messages/react-hydration-error
````

Only occures on initial page load in dev mode, hmr fixes it (basically on any first change error goes away). Will looking into it, probably not related to this ticket.

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next#usetranslation

import useTranslation from next-i18next, not from react-i18next

**Comment by nick4fake** [comment]
@adrai thanks, edited comment just in time :)

Thanks a lot for your help, though there should be some doc note about ESM. I'll create PR some day later

**Comment by Chriskuiper1** [comment]
I can't get my nextjs app working running on type Module.

Does anyone have an example? 

I run into problems not being able to add the .cjs file to the _App main component or to my next.config file. I tried it all night long and it just doesnt work. Even having a next.config.cjs file in combination with next-i18next.config.cjs and a default path overwrite. 

I18NEXT_DEFAULT_CONFIG_PATH=./next-i18next.config.cjs 

I get the error: error - Error: Invalid locale returned from getStaticPaths for /[[...slug]], the locale nl is not specified in next.config.js

It just doesn't read my next.config location in the right way. 

The config file's are in order and do have nl as local.

module.exports = {
  i18n: {
    locales: ['en', 'nl'],
    defaultLocale: 'en',
    // localePath: './public/locales',
    // ns: ['common']
  }}
  
  please help me out!
