### ISSUE TITLE
The Context is reset when routing page.

### ISSUE THREAD

**Issue by lequangkhanh2901** [i18next/next-i18next#2187]
## 🐛 Bug Report

I create a `ThemeContext` for my `nextjs app`. but when routing, the `context` is reset.

## To Reproduce

I create an `WrapLayout.tsx` with context: 

```tsx
interface ThemeData {
  theme: GlobalTheme
  setTheme: (data: GlobalTheme) => void
}

export const ThemeContext = createContext<ThemeData>({
  theme: GlobalTheme.LIGHT,
  setTheme: () => {
    //
  },
})

export const useThemeContext = () => useContext(ThemeContext)

function WrapLayout({ children }: { children: ReactElement }) {
  const [theme, setTheme] = useState<GlobalTheme>(GlobalTheme.LIGHT)

  return (
    <ThemeContext.Provider value={{ theme, setTheme }}>
      <div id="theme-layout" data-theme={theme} className="text-txt-primary">
        {children}
      </div>
    </ThemeContext.Provider>
  )
}

export default WrapLayout

```
The `theme` have 2 value: `light` (default) and `dark`.

This is `_app.tsx`
```tsx
function App({ Component, pageProps }: AppProps) {

  return (
    <Provider store={store}>
      <WrapLayout>
        <Component {...pageProps} />
      </WrapLayout>
    </Provider>
  )
}

```

I have 2 page `/` and `/manager`.
When I'm in `/manager`. I change theme to `dark`:  the `theme` is reset to `light`.

That because I use `next-i18next` in `/manager`.

```ts
export async function getServerSideProps({ locale }: { locale: string }) {
  try {
    return {
      props: {
        ...(await serverSideTranslations(locale, ['common'])),
      },
    }
  } catch (error) {
    return {
      props: {
        ...(await serverSideTranslations(locale, ['common'])),
      },
    }
  }
}
```

If I remove `i18`, the `theme` is not reset.

`i18n` cause `unmount` whole app.

## Expected behavior

The `context` is not reset when routing when using `next-i18next`.

## Your Environment

- *runtime version*: node v18.12.1, browser Brave
- *i18next version*: 14.0.0
- *os*: ubuntu 20.04
- *nextjs*: 13 with pages dir

**Comment by adrai** [comment]
Please provide a minimal reproducible example repository showing your issue.

**Comment by sinau123** [comment]
i dont know, but it's like when we call serverSideTranslations in getServerSideProps and  then pass it value to props, the _app.tsx component is re-mounted @adrai

**Comment by sinau123** [comment]
but it's only happen when the next route is not calling serverSideTranslations in getServerSideProps and vice versa

**Comment by adrai** [comment]
waiting for a minimal reproducible example repository or similar
