### ISSUE TITLE
Redirects in loop

### ISSUE THREAD

**Issue by TangoPJ** [i18next/next-i18next#2190]
I have a problem with redirects in loop instead of redirect to the 404 page. I tried the example with SSG. But created my own landing page, redirects etc are the same as in the examples/ssg folder. The problem occured in production mode only, locally all ok! Please help

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/issues/2095

**Comment by adrai** [comment]
you need to provide a minimal reproducible example or investigate yourself...

**Comment by TangoPJ** [comment]
> you need to provide a minimal reproducible example or investigate yourself...

It was a problem on the server side, devops fixed it. Thank you:) I'm going to close this issue

**Comment by iDVB** [comment]
@TangoPJ any chance you could report back on what the server side issue was? 
We're having the exact same issue with it working local and looping in prod [open-next](https://open-next.js.org/)
