### ISSUE TITLE
issue case: next-i18next stopped working with ISR/SSR on AWS Amplify and Vercel

### ISSUE THREAD

**Issue by konhi** [i18next/next-i18next#2192]
> ⚠️ this is not a bug report per se, doesn't necessarily mean there's specific issue with next-i18next, and so there's no minimal reproduction steps. the goal is to report an problem that i've occurred on production, so it might possibly help someone that struggles something similar :)

1. Next.js 13 App with Pages Directory with next-i18next suddenly started to not translate properly, but only on ISR/SSR pages — SSG worked as expected, which meant problem happens on Functions/Lambda side. This problem occurred with code that was working for a year, so it was probably infrastructure specific. The issue was present both on Vercel and AWS Amplify

<img width="1512" alt="image" src="https://github.com/i18next/next-i18next/assets/61631665/c818f0a7-5acb-47f0-80c4-92e50cf28d35">

2 After enabling debugging in next-i18next config, it seemed that it can’t load the files. There was info about missing keys, and the `"loadPath": "./public/locales/{{lng}}/{{ns}}.json"` seemed to be only appropriate for website.
3. Using path.resolve fixed the problem, and changed the loadPath.

<img width="1485" alt="image" src="https://github.com/i18next/next-i18next/assets/61631665/e5503204-d6df-4214-b735-2d5e29ff75ae">

**Comment by adrai** [comment]
This is a known issue and documented here: https://github.com/i18next/next-i18next#vercel-and-netlify
