### ISSUE TITLE
serverSideTranslations not working with getServerSideProps on production

### ISSUE THREAD

**Issue by natashasq** [i18next/next-i18next#2194]
## 🐛 Bug Report

When I use serverSideTranslations and getServerSideProps on local, everything works fine. But, the **t** function doesn't work when I run my code on the production.

 This is my page:
 
 
import Head from 'next/head';
import Link from 'next/link';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

const Links = (props) => {
  const { t } = useTranslation;
  return (
    <div>
      <Head>
        Links <link rel="icon" href="/nextjs-ssr/links/public/favicon.ico" />
      </Head>
      <div className="pt-20 px-5 flex flex-col justify-center items-center">
        <h1 className="text-xl mb-3 mt-10">Links Page</h1>
        <h3 className="mb-10 text-lg">
          {t('WELCOME')}
        </h3>
        <div className="bg-white rounded-lg border border-gray-200 w-56 text-gray-900 text-sm font-medium ml-5 mt-5">
          {data.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className="text-xs block px-4 py-2 border-b border-gray-200 w-full rounded-t-lg hover:text-white hover:bg-btn_blue cursor-pointer"
            >
              {item.label}
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

export async function getServerSideProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'en', ['common'])),
      data: [
        { href: '/', label: 'Home' },
        { href: 'https://www.wikipedia.org/', label: 'Wikipedia' },
        { href: 'https://nextjs.org/', label: 'Next.js' },
      ],
    },
  };
}
export default Links;

this is next-i18next.config.js file:

`const path = require('path');

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'fr'],
  },
  reloadOnPrerender: process.env.NODE_ENV === 'development',
  localePath: path.resolve(__dirname + './locales'),
};
`
I tried without "localePath" option, but no change. 

If you have any ideas, I'll appreciate the help. 
Thank you!

**Comment by adrai** [comment]
Please provide a complete but minimal reproducible example, not just code snippets.
And compare with this example: https://github.com/i18next/next-i18next/blob/d4aea294d70f7ff8645b2aa494f918299a1e84da/examples/simple/pages/second-page.tsx#L40
if it works locally but not when deployed, there might be an issue there...

**Comment by natashasq** [comment]
Hey @adrai, thank you for the super fast reply. 

I found the issue, it was the "localePath" prop in my next-i18next.config.js file. I didn't add the option when the window is "undefined", like in the example that you sent me, and that is why my SSR pages didn't work, on the production. 

So instead of:
`localePath:  `require('path').resolve('./locales')`

now, I have: 

`
  localePath:
    typeof window === 'undefined'
      ? require('path').resolve('./public/locales')
      : '/locales',
`

Everything is working fine. 
Thank you again, so much!

**Comment by mr-rony356** [comment]
> Hey @adrai, thank you for the super fast reply.
> 
> I found the issue, it was the "localePath" prop in my next-i18next.config.js file. I didn't add the option when the window is "undefined", like in the example that you sent me, and that is why my SSR pages didn't work, on the production.
> 
> So instead of: `localePath: `require('path').resolve('./locales')`
> 
> now, I have:
> 
> `localePath: typeof window === 'undefined' ? require('path').resolve('./public/locales') : '/locales',`
> 
> Everything is working fine. Thank you again, so much!

Life Saving Words
I have been suffering with this Issues For last 2 days Finally Fixed after `localePath: typeof window === 'undefined' ? require('path').resolve('./public/locales') : '/locales',` using this
