### ISSUE TITLE
feat: can add base JSON to useTranslation hook.

### ISSUE THREAD

**Issue by hoseinsoleymani** [i18next/next-i18next#2199]
`
const { t } = useTranslation("header")
<h1>{t("title")}</h1>
`
and the result will be:

header.title

**Comment by adrai** [comment]
Sorry, I have no idea what you mean.

**Comment by hoseinsoleymani** [comment]
sorry for my delay.
I mean about namespace.
for example my JSON file is:
{
   "header": {
      "title": "This is my title",
      "desc": "This is my description."
   }
}

and for usage I want do like that:

`function App() {
const { t } = useTranslation("header")

return (
<div>
   <h1>{t("title")}</h1>
   <p>{t("desc")}</p>
</div>
)
}`
but now we can provide namespace for useTranslation like above code.

@adrai

**Comment by adrai** [comment]
Sorry, I stil not understand. And btw. header is not a namespace but a nested key.

**Comment by hoseinsoleymani** [comment]
Would u pls provide me a solution?
how can I put header in useTranslation?

**Comment by adrai** [comment]
header needs to be an own json file (a namespace) => https://www.i18next.com/principles/namespaces
