### ISSUE TITLE
namespacesRequired in serverSideTranslations is not type-safe anymore

### ISSUE THREAD

**Issue by t-ondrej** [i18next/next-i18next#2201]
## 💥 Regression Report

`namespacesRequired` type in `serverSideTranslations` is not constrained by the `Namespace` anymore. Type-safety achieved by overriding `CustomTypeOptions` in `i18next.d.ts` is lost and any string is accepted now.

The change was introduced in [this commit](https://github.com/i18next/next-i18next/commit/d14fc0dd8124af10911ac9d25d0bcd2ef8741c2e). 

Note: Don't know the typescript error that the commit fixed, but shouldn't the `ElementArrayOrSelf` have the following type 
```Typescript
type ArrayElementOrSelf<T> = 
  T extends Array<infer U> 
    ? U[] 
    : T; // <-- Not T[] because it's not an identity of T
```

## Last working version

Worked up to version: 13.3.0

Stopped working in version: 14.0.0

## Expected behavior
`serverSideTranslations.namespacesRequired` accepts namespaces only. If no namespace is defined, any string is valid.

**Comment by adrai** [comment]
Would you like to provide A PR to address this?

**Comment by adrai** [comment]
Can you try with v14.0.2 ?

**Comment by t-ondrej** [comment]
Thank you for the quick response. Unfortunately, it still didn't work. I have provided a PR that fixes it.
