### ISSUE TITLE
Add NextI18NextProvider and deprecate appWithTranslation

### ISSUE THREAD

**Issue by abdulqdaer-q** [i18next/next-i18next#2206]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

following the new way of "next-redux-warpper"

## Example

I am happy to implement the feature if you approve it

**Comment by adrai** [comment]
I don't know exactly what you mean and why this is useful, and what the benefits are, but yes you can try a PR.
But I would not deprecate the appWithTranslation from the beginning... if your provider approach gets more accepted we can then start to deprecate it.

**Comment by zeropaper** [comment]
I think it has to do with the [new app router of NextJS](https://nextjs.org/docs/app).

I am not sure if the "pages" routing is considered deprecated but the new routing significantly differs because "pages" in the "app router" can be rendered server side. 
And that makes the `appWithTranslation` practically useless / unwanted in that case.

I stumbled here because I was looking for a "Provider" specially designed for the new app router.

**Comment by adrai** [comment]
<img width="861" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/9daecb42-2be9-4b3a-bc03-8a22a31dc6d4">
https://locize.com/blog/next-13-app-dir-i18n/
https://github.com/i18next/next-i18next/discussions/1993#discussioncomment-5758143

**Comment by abdulqdaer-q** [comment]
Oh I was considering this as a first step for app directory

**Comment by quyphan97** [comment]
@adrai How to get current lng

**Comment by adrai** [comment]
> @adrai How to get current lng

i18next.resolvedLanguage or i18next.language or i18next.languages[0] // depends on your needs: https://www.i18next.com/overview/api#resolvedlanguage

**Comment by quyphan97** [comment]
![image](https://github.com/i18next/next-i18next/assets/59947963/270cc7c9-ed60-4367-af9c-815b46f2ee9b)
Well thank you very much. Can you help me configure this image?
I got an error that kept calling back the page when there was a config.matcher.

**Comment by adrai** [comment]
you may ask the Next.js team... that is not directly related to next-i18next or i18next

**Comment by rs-guian** [comment]
Guide has been moved here : https://www.locize.com/blog/next-app-dir-i18n
