### ISSUE TITLE
useTranslation type inference arguments and return type doesn't take namespace into account

### ISSUE THREAD

**Issue by andreiciceu** [i18next/next-i18next#2207]
## 💥 Regression Report

Type inference for useTranslation hook arguments and return type seems to not be parametrised anymore:

- expected type for the key given to the translation function is not inherited anymore from the useTranslation hook (namespace must be provided):
```tsx
const {t} = useTranslation('common');
console.log(t('testKey')); // this worked before, but now throws a Type error
console.log(t('common:testKey')); // is required now
console.log(t('app:testKey2')); // this does not throw a type error, even though the app namespace is not available
```

- return type for nested keys is always string:
```jsonc
// common.json
{
  "nestedKey": {
      "title": "Test",
      "items:": ["one", "tow"]
  }
}
```
```tsx
const {t} = useTranslation('common');
// this worked before, but now throw a type error, as the return type is always string
console.log(t('nestedKey').title, t('nestedKey').items[0]); 
```

## Last working version

Worked up to version: 13.3.0 (next-i18-next), 12.2.1 (react-i18next), 22.5.1 (i18next)

Stopped working in version: 14.0.0

## Your Environment

- *runtime version*: i.e. browser, nextJS
- *os*: Mac
```json
{
   "i18next": "^23.5.1",
    "next": "^13.4.19",
    "next-i18next": "^14.0.3",
    "react-i18next": "^13.2.2"
}

**Comment by adrai** [comment]
have you set returnNull to true? https://www.i18next.com/overview/typescript
in the i18next.d.ts file and in your init options?
The default value for returnNull was changed in the last major update: https://www.i18next.com/misc/migration-guide#changed-default-value-for-returnnull-option-to-false

**Comment by andreiciceu** [comment]
> have you set returnNull to true? https://www.i18next.com/overview/typescript
> in the i18next.d.ts file and in your init options?
> The default value for returnNull was changed in the last major update: https://www.i18next.com/misc/migration-guide#changed-default-value-for-returnnull-option-to-false

Hi @adrai, thanks!
I've tried with that too, but it solves none of the points in my previous post:
(namespace is still needed
![image](https://github.com/i18next/next-i18next/assets/9255607/e94966aa-8924-4798-a6fb-65e9370a9894)

That's how i18next.d.ts looks:
```tsx
import 'i18next'
// import all namespaces (for the default language, only)
import app from '../public/locales/en/app.json'
import common from '../public/locales/en/common.json'
import landing from '../public/locales/en/landing.json'
import auth from '../public/locales/en/auth.json'
import pricing from '../public/locales/en/pricing.json'
import legal from '../public/locales/en/legal.json'

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common'
    returnNull: false
    resources: {
      app: typeof app
      auth: typeof auth
      common: typeof common
      landing: typeof landing
      pricing: typeof pricing
      legal: typeof legal
    }
  }
}
```

**Comment by adrai** [comment]
Sorry, I didn't want to write returnNull, but returnObjects.
returnObjects needs to be set to true.
Beside that the namespace prefix should not be necessary. Here you see it works: https://github.com/i18next/next-i18next/blob/085c8df5847e7242143495290bc66c8ba941d6b6/examples/simple/pages/index.tsx#L42

**Comment by andreiciceu** [comment]
@adrai thanks; managed to find out why: our project has this in *tsconfig.json*
```json
{
    "strict": false,
    "strictNullChecks": false
}
```

Removing those two lines makes the t function usable without providing the namespace, but the whole project needs refactoring to fix other errors caused by removing them (so at the moment, it's not possible to upgrade :/).

Do you have any insight/idea into why this is happening and why on previous version it worked?

**Comment by adrai** [comment]
<img width="791" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/6c0c1e63-5b71-473e-b1b0-f8382a0861e6">
https://www.i18next.com/overview/typescript

sorry, no
