### ISSUE TITLE
Multiple translations downloads

### ISSUE THREAD

**Issue by williamisnotdefined** [i18next/next-i18next#2213]
Every single time I change route in my app, the translations are being downloaded, again and again.
Plus my localStorage are not storing my translations as I was expecting.

As we can see in this Network console:
![image](https://github.com/i18next/next-i18next/assets/9591024/d90ffead-8b86-4265-949d-c6defe62b19d)

Now goes a print of my localStorage, with nothing related to translations:
![image](https://github.com/i18next/next-i18next/assets/9591024/8f5d238b-aab5-46bb-8135-99baa6b0dff9)

Here is my next-i18next.config.js

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const ChainedBackend = require("i18next-chained-backend").default;
const HttpBackend = require("i18next-http-backend").default;
const LocalStorageBackend = require("i18next-localstorage-backend").default;
const path = require("path");

const isBrowser = typeof window !== "undefined";

module.exports = {
  // debug: true,

  i18n: {
    defaultLocale: "en",
    locales: ["pt-BR", "en"],
  },

  localePath: isBrowser ? path.resolve("./public/locales") : "/locales",

  backend: {
    backends: isBrowser ? [LocalStorageBackend, HttpBackend] : [HttpBackend],
    backendOptions: [
      {
        expirationTime: 7 * 24 * 60 * 60 * 1000,
        prefix: "i18next_res_",
        version: {},
        store: isBrowser ? window.localStorage : null,
      },
      { loadPath: "/public/locales/{{lng}}/{{ns}}.json" },
    ],
  },

  partialBundledLanguages: true,
  defaultNS: ["common"],
  ns: ["common"],

  serializeConfig: false,

  reloadOnPrerender: false,

  use: isBrowser ? [ChainedBackend] : [],
};

```

and here we can check my next.config.js:

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const dotEnv = require("dotenv");
/**
 * we need to use this plugin to transpile the sitesProject aliases
 */
const withTM = require("next-transpile-modules")(["sitesProject"]);
const path = require("path");
// const selectorNamespace = require("postcss-selector-namespace");
const { parsed: localEnv } = dotEnv.config({
  path: path.resolve(process.cwd(), `.env.${process.env.NODE_ENV}.local`),
});

const { i18n } = require("./next-i18next.config");

/**
 * @type {import('next').NextConfig}
 */

const nextConfig = withTM(
  {
    env: {
      ...localEnv,
    },

    images: {
      remotePatterns: [
        {
          protocol: "https",
          hostname: "cdn.myDomain.com",
        },
        {
          protocol: "https",
          hostname: "cdn-admin-static.myDomain.com",
        },
      ],
      imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
      deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    },

    swcMinify: true,

    webpack(config) {
      config.module.rules.push({
        test: /\.svg$/,
        use: ["@svgr/webpack", "url-loader"],
      });

      return config;
    },

    i18n,

    poweredByHeader: false,
    reactStrictMode: true,

    compiler: {
      styledComponents: true,
    },
    sassOptions: {
      includePaths: [
        path.join(__dirname, "src/design-system/**/*.scss"),
        path.join(__dirname, "src/layouts/**/*.scss"),
        path.join(__dirname, "src/screens/**/*.scss"),
      ],
    },
  },
  ["sitesProject"],
);

module.exports = nextConfig;

```

Now we can check my _app.tsx:

```js
import { NextPage } from "next";
import { SessionProvider } from "next-auth/react";
import { appWithTranslation } from "next-i18next";
import { AppProps } from "next/app";
import NextNprogress from "nextjs-progressbar";
import { lazy, ReactNode, Suspense, useEffect, useState } from "react";
import { RecoilEnv, RecoilRoot } from "recoil";

import { DEFAULT_QUERY_CONFIG } from "@/core/reactQueryConfig";
import CurrentBreakpoint from "@/ds/debug/CurrentBreakpoint";
import DefaultLayout, { PageComponentType } from "@/layouts/AppLayout";
import nextI18NextConfig from "@/root/next-i18next.config";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import "@/styles/globals.scss";

RecoilEnv.RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED = false;

const queryClient = new QueryClient({
  defaultOptions: DEFAULT_QUERY_CONFIG,
});

const ReactQueryDevtoolsProduction = lazy(() =>
  import("@tanstack/react-query-devtools/build/lib/index.prod.js").then(
    (d) => ({
      default: d.ReactQueryDevtools,
    }),
  ),
);

type WindowWithDevTools = Window & { toggleDevtools: () => void };

// eslint-disable-next-line @typescript-eslint/ban-types
type Page<P = {}> = NextPage<P> & {
  getLayout?: (page: ReactNode) => ReactNode;
};

type GetLayoutType = (
  pageComponent: PageComponentType,
  props: any,
) => ReactNode;

type MyAppProps = AppProps & {
  Component: Page;
  asPath?: string;
};

function MyApp({
  Component,
  pageProps: { session, ...pageProps }, // asPath,
}: MyAppProps) {
  const [showDevtools, setShowDevtools] = useState(false);
  const getLayout = (Component.getLayout ||
    DefaultLayout.getLayout) as GetLayoutType;

  useEffect(() => {
    (window as unknown as WindowWithDevTools).toggleDevtools = () =>
      setShowDevtools((isOpen) => !isOpen);
  }, []);

  return (
    <SessionProvider session={session}>
      <QueryClientProvider client={queryClient}>
        <RecoilRoot>
          <NextNprogress
            color="rgb(var(--color-yellow-90))"
            showOnShallow={false}
          />
          <CurrentBreakpoint />

          {getLayout(Component as PageComponentType, pageProps)}

          <ReactQueryDevtools />

          {showDevtools && (
            <Suspense fallback={null}>
              <ReactQueryDevtoolsProduction />
            </Suspense>
          )}
        </RecoilRoot>
      </QueryClientProvider>
    </SessionProvider>
  );
}

export default appWithTranslation(MyApp, nextI18NextConfig);

```

I think the expected behavior would be the translations to be downloaded just 1 time (at least is what I need) and in order to cache them, they could be stored in the localStorage.

Sorry if I misunderstood something, the thinks are a bit confuse to me at this point.

Environment info:
node version: 18.16.0-alpine
linux fedora 38

package.json libs versions:
"i18next": "23.5.1",
"i18next-chained-backend": "4.5.0",
"i18next-http-backend": "2.2.2",
"i18next-localstorage-backend": "4.2.0",
"next-i18next": "14.0.3",
"react-i18next": "13.2.2",

If I miss some information, please, let me know so that I can share with you guys.
Thank you very much in advance!

**Comment by adrai** [comment]
I'm not able to reproduce it with the simple example in this repository...
Maybe it's because of the partialBundledLanguages option...
Please provide a minimal reproducible example repository.

**Comment by williamisnotdefined** [comment]
the same behavior happens if we comment this line

**Comment by williamisnotdefined** [comment]
it's weird because my code is very simple straightforward, there are no big complexities..
I honestly have no idea what I'm missing, or doing wrong.

**Comment by williamisnotdefined** [comment]
Im going to provide a git repo with example, in next hours, but my will be fake like:
"i18nexus pull -k PUT_YOUR_KEY_HERE", is that enough for you?

**Comment by adrai** [comment]
Why are you using i18nexus? Why don't you use the service that officially sponsors i18next and ensures the future of i18next? The creators of i18next are also the founders of [locize](https://locize.com).

**Comment by adrai** [comment]
btw: I just updated this example: https://github.com/i18next/i18next-http-backend/tree/master/example/next and It seems to work as expected

**Comment by williamisnotdefined** [comment]
Yeah, sure!
It wont be a problem for me to change i18nexus for locize, but first I need to ensure my translations won't be downloaded every route change and they will be in the localStorage.

One more information, when I add the debug flag to true, in each route change the event languageChange is fired and I have no idea why it is happening..

I'm working in provide you the example you asked, and again, that's fine to us change for locize!
Thank you one more time for help us.

**Comment by williamisnotdefined** [comment]
@adrai 
here is my code: https://github.com/williamisnotdefined/i18next-test

it was pretty straightforward to reproduce the behavior in other project, please have a look in this printscreen:

![image](https://github.com/i18next/next-i18next/assets/9591024/367d586a-3a1b-4739-abb7-7b9d688f1d3d)

each time o change route it download the translation again, in both enviroment dev or production.

**Comment by williamisnotdefined** [comment]
is it happening because the serverSideTranslations?

**Comment by williamisnotdefined** [comment]
Every time i change the routes in my example with debug flag set to true the languageChanged is fired:
![image](https://github.com/i18next/next-i18next/assets/9591024/13e16351-d181-40a7-a389-d9da50781d7e)

I have also noticed my translations now are no longer working.

I can see a warning in my browser console as image below:
![image](https://github.com/i18next/next-i18next/assets/9591024/5a05dcea-85f6-488d-920a-e3e1a52a021d)

is something I am missing?

**Comment by williamisnotdefined** [comment]
I made a commit fixing the i18n (https://github.com/williamisnotdefined/i18next-test).

- The translations are being displayed
- The warning in the console is no longer there

unfortunately these errors are still there:
- no cache being stored in localStorage
- every change route my the previously downloaded translation is being downloaded again

**Comment by williamisnotdefined** [comment]
Sorry my repository was private, now i setted up as public!

**Comment by adrai** [comment]
It seems you did not follow the readme: https://github.com/i18next/i18next-http-backend/tree/master/example/next#alternative-usage-the-preferred-way
and the blog post: https://locize.com/blog/next-i18next/

Your example does not load any translations on client side, all your pages are server side (first) so there is no need to load them on client side.

Here you see I added 2 additional pages that shows how to "trigger" client side translation loadings: https://github.com/williamisnotdefined/i18next-test/pull/1/files

**Comment by williamisnotdefined** [comment]
But my complain is about the excessive translation json download in the browser as my screenshot shows:
![image](https://github.com/i18next/next-i18next/assets/9591024/41d15c5f-1001-4723-81d2-abc07f0f724b)

since we have already downloaded a certain translation, there is no why to do it again.

**Comment by williamisnotdefined** [comment]
Actually I hadn't commited but I did read and see the link, by using the lazy-reload the localStorage is filled successfully! Now my only concern is about the massive json downloads.. Are those repeated downloads the right behavior? Is there some way to avoid them?

**Comment by adrai** [comment]
These are not translation downloads done by i18next, but page props fetches done by Next.js
I suspect this happens only on dev mode... if not please ask the Next.js team. That's not related to i18next.

**Comment by adrai** [comment]
https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props#runs-on-every-request-in-development

https://stackoverflow.com/questions/74969914/i-use-the-getstaticprops-function-the-props-change-every-time-the-page-is-refre

**Comment by williamisnotdefined** [comment]
Sure, thank you for all support in this issue!
