### ISSUE TITLE
useTranslation is not working for placeholder

### ISSUE THREAD

**Issue by gabrielsoaresgsm** [i18next/next-i18next#2216]
The key "franchise.type Your ZipCode" is translated into Brazil and Mexico. In the placeholder it is only being applied to Brazil. It is not being changed for when countryCode is MEX.

I left an h1 below so you can see that it works normally, but in the placeholder of some input it doesn't. can you help me?

I'm using material ui, next js and next-i18next 10.5.0

![codeprint](https://github.com/i18next/next-i18next/assets/77764654/8cfc6927-b013-494b-9114-b636e774a6ec)

![image](https://github.com/i18next/next-i18next/assets/77764654/2456fe1f-86cc-48d5-ad9b-bc8b2c7a2e94)

**Comment by adrai** [comment]
Please provide a reproducible example
