### ISSUE TITLE
next-18next not comaptible with turbopack

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [i18next/next-i18next#2222]
## 🐛 Bug Report

If you turn on the --turbo flag (with the app router) it does not work

## To Reproduce

Add the --turbo flag to the a next-i18next project

## Expected behavior

It should work and don't give errors

## Your Environment

- *i18next version*: i.e. 14.0.3
- *os*: Windows

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/issues/2113#issuecomment-1551599297

**Comment by FleetAdmiralJakob** [comment]
Is there a fix incoming for next-i18next?

**Comment by adrai** [comment]
fyi: please update your next.js version to a newer v14 version and next-i18next to v15.1.0
