### ISSUE TITLE
When use "-" in locales, it crash. For Example: 'pt-br', 'zh-cn' will Crash, but 'ptbr', 'zhcn' is OK

### ISSUE THREAD

**Issue by cml98** [i18next/next-i18next#2229]
## 🐛 Bug Report

locales doesn't seem to support '-' because when I use 'zh-cn' instead of 'cn', it can cause a crash. The problem of reproducing this is simple, just change the "de" in Simple Demo to "zh-cn". 

I guess this is caused by not supporting '-'.

## To Reproduce

```js
❌ is will crash by show Error: Service Text dismatch Client Text
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en','zh-cn'],
  },
}

✔
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en','cn'],
  },
}
```

## Your Environment
  "i18next": "^23.6.0",
  "next": "14.0.1",
  "next-i18next": "^15.0.0",
  "react": "^18",
  "react-i18next": "^13.3.1",

**Comment by adrai** [comment]
try zh-CN

**Comment by adrai** [comment]
en-GB de-CH etc.. works
