### ISSUE TITLE
I'm using nextjs 13 (pages directory) In my dynamic pages (SSR) It can't load i18n translation and just show the kyes in server. but it's ok in development mode.

### ISSUE THREAD

**Issue by VahidRouzbahani** [i18next/next-i18next#2231]
I'm using nextjs 13 (pages directory) In my dynamic pages (SSR) It can't load i18n translation and just show the kyes in server. but it's ok in development mode.

It's ok in dev mode but when i deploy my project in AWS server (Amplify) it encountered with problem. (Just for dynamic pages, in static pages it's ok)

**Comment by adrai** [comment]
Please provide a minimal reproducible example repository.
Are you using the useTranslation hook of react-i18next or of next-i18next?

**Comment by VahidRouzbahani** [comment]
I'm using next-i18next useTranslation hook.

export async function getServerSideProps(context: Context) {
  const {
    locale,
    params: { id },
  } = context;

  return {
    props: {
      ...(await serverSideTranslations(locale)),
      
    },
  };
}

**Comment by adrai** [comment]
Please provide a complete example repository.

**Comment by Shiro1995** [comment]
> Please provide a minimal reproducible example repository. Are you using the useTranslation hook of react-i18next or of next-i18next?

I have the same problem. my folder path
public/locales/en/common.js
I use next-i18next and don't know how to set up server-side for now.
Currently, I still show the key as the above guy.

**Comment by adrai** [comment]
Please provide a complete example repository.

btw it's common.json not js

**Comment by Shiro1995** [comment]
> Please provide a complete example repository.
> 
> btw it's common.json not js

Hi Adrai, It works with the index in page default, but when I push to some other page, I just get the key.
I already tried to use getServerSideProps and get StatisProps at the bottom of file, but not work.

**Comment by adrai** [comment]
I really need a minimal but reproducible example repository. I have no idea right now what the issue could be. Sorry.

**Comment by Shiro1995** [comment]
I will send asap.

**Comment by Shiro1995** [comment]
it works now, We have to add the getServerSideProps at index.ts file, sorry for that.

**Comment by SolijonovDev** [comment]
next-i18next.config.js

const path = require('path');

module.exports = {
  debug: false,
  i18n: {
    defaultLocale: 'uz',
    locales: ['uz', 'ru'],
    localeDetection: false,
    localePath: path.resolve('./public/locales'),
  },
};

**Comment by belgattitude** [comment]
@SolijonovDev for the `localePath` I'd suggest to setup the path based on runtime (browser or nodejs). 

```typescript
// @ts-check

/**
 * @type {import('next-i18next').UserConfig}
 */
module.exports = {
  debug: process.env.NODE_ENV === 'development',
  i18n: {
    defaultLocale: 'uz',
    locales: ['uz', 'ru'],
  },
  localePath:
    typeof window === 'undefined'
      ? require('path').resolve('./public/locales')
      : '/locales',
  // allows hot reload / fast refresh in dev
  reloadOnPrerender: process.env.NODE_ENV === 'development',
}
```
