### ISSUE TITLE
Bug: the entire Next app unmounts and remounts on SSG pages with fallback: true or fallback: 'blocking'.

### ISSUE THREAD

**Issue by felixmeziere** [i18next/next-i18next#2236]
## 🐛 Bug Report

When using `next-i18next` on SSG pages with `fallback: true` or `fallback: 'blocking'` in `getStaticPaths` (one of the main benefits of next.js, allowing to build pages on the fly which is needed for websites with a lot of product pages like [ours](https://www.greengo.voyage)), the app will be unmounted and remounted every time the page is loaded, which causes among others :

- performance issues
- issues with anything relying on `useEffect` being called once on page load (like analytics) : `useEffect` is called twice.
- ...

## To Reproduce

I have forked the repo [here](https://github.com/GreenGoTech/next-i18next/pull/1) and slightly modified the `ssg` example to reproduce the problem. To do so :

```sh
git clone git@github.com:GreenGoTech/next-i18next.git
cd next-i18next
git checkout fix-unmount-remount-on-fallback-true-ssg-bug
cd examples/ssg
npm install
npm run dev
```

then :

- open your browser and its console
- navigate to http://localhost:3000/en/second-page/
- see 2 renders and 1 useEffect
- navigate to http://localhost:3000/en/some-random-not-prebuilt-slug/
- see 3 renders and **2 `useEffect`** (instead of 1 `useEffect` which is standard and expected Vanilla Next.js behaviour).

**Likely cause :** I have dug in the library a bit. I see that the provider in appWithTranslation is added by a ternary :

```ts
return i18n !== null ? (
      <I18nextProvider i18n={i18n}>
        <WrappedComponent {...props} />
      </I18nextProvider>
    ) : (
      <WrappedComponent key={locale} {...props} />
    )
```

this causes the whole app to be unmounted/remounted whenever i18n goes from null to nonnull. A pattern that would work instead of this would be to always have the provider but have it accept a null i18n instance, propagating the consequences of that down the component tree. I quickly saw that this goes deeper into the react-i18next library so I figured I wouldn't be the one best indicated to solve this as it seems to require quite a deep understanding of the i18next ecosystem.

## Expected behavior

The app should be mounted only once on SSG pages with `fallback: true | 'blocking'` as in vanilla Next.js. The initial `useEffect` should only be called once.

## Your Environment

- *runtime version*: node v18.17.0
- *i18next version*: 23.6.0
- *os*: Mac

**Comment by adrai** [comment]
yes, that's normal if you set fallback to true, because next.js generates a "fallback" page that does not contain page props etc..
alternatively, you could pass in the nextI18NextConfig to appWithTranslation, but that would probably result in a client  hydration warning (client and server text not matched...)

```js
import nextI18NextConfig from '../next-i18next.config.js'
// ...
export default appWithTranslation(MyApp, nextI18NextConfig)
```

**Comment by felixmeziere** [comment]
Ok, the thing is: vanilla next.js does not have this issue, it does only one useEffect even when fallback is true. What happens when fallback is true is 2 renders : one without props and then one with props.
Wouldn't it be possible to have the same thing with i18next: a first render without props (and no translations), and then a re-render with the props; but without doing a full remount of the app?

**Comment by adrai** [comment]
That's basically, what is happening [here](https://github.com/i18next/next-i18next/blob/f189d3bfc5c8cb82352fb2468fe489459d3ff58e/src/appWithTranslation.tsx#L112) , but if you think there's a better possibility to do so, feel free to try a PR.

**Comment by felixmeziere** [comment]
Yes that's what's happening where you are pointing: there is a full remount of the app because of the ternary that gets triggered when i18n goes from null to nonnull.
What would avoid this full remount is to instead allow for 18n to be null within the provider (which goes into the `react-i18next` library, not just `next-i18next`), and that null to propagate down to the translations themselves, just displaying the translation keys instead of the actual translations while i18n is null.

This seems like a quite big refactoring for someone who has never touched both libraries, but I thought the impact of the problem would maybe motivate someone from the core team to look into it? Basically this means performance issues and unreliable use of useEffect on every SSG'd without `fallback: false`, which is one of the core features of next.js.

Am I maybe overstating the importance of the issue?

**Comment by adrai** [comment]
Like said, you can simulate this, by passing i18n || an uninitialized i18next instance for example (would show empty keys), but that would result in more errors/warnings (like said before)

**Comment by felixmeziere** [comment]
Ok thanks, I will try and report back in a day or two.

**Comment by felixmeziere** [comment]
Thanks for merging my documentation PR!

Out of curiosity, what would be the drawbacks of always having this empty empty initial i18next config instead of an `undefined` instance that causes these remounts? Wouldn't it make people apply good practices of not displaying undesired translation keys to users anyway?

**Comment by adrai** [comment]
Normally, the config is found automatically, so for normal setups this is not necessary.
You need that for example if you have an unserializable config: https://github.com/i18next/next-i18next#unserializable-configs
