### ISSUE TITLE
App loses translations on page transition if namespaces are split between pages

### ISSUE THREAD

**Issue by ckruppe** [i18next/next-i18next#2240]
## 🐛 Bug Report

I use the pages router in next and found an problem with the i18next provider. For background:
The app i am building is really big and has many translations. (80 pages minimal and all have massive translation files)
So i split the namespaces after routes to not let the user load all translations for pages he may never see. (did speed up the
loading times also quite a bit)

Now the problem is on page change with the "serverSideTranslations" function i only inklude the namespaces relevant for that
page. And on page transition the currently loaded page loses its translations the second you click the link.

## To Reproduce

I made you guys an example page. The transition is extra long so you can see the problem better.
https://codesandbox.io/p/devbox/next-js-forked-dn5jrg

## Expected behavior

I would expect the page not to lose the namespaces already loaded and instead having the appWithTranslation HOC remember all already loaded namespaces and only add to them if new ones get loaded. As it is now its impossible to use next-i18next for some big projects as it forces me to load all translations (needed or not) in advance. This makes it not feasable also from an SEO standpoint as these pages get real big and start to load "really" long if i need all the translations.

## Your Environment

- runtime version: node v20, Any Browser
- i18next version: 23.7.8
- react-i18next version: 13.5.0
- next-i18next version: 14.0.3
- os: Mac, Windows, Linux

**Comment by adrai** [comment]
Just update next-i18next to the newest version...

**Comment by ckruppe** [comment]
Thank you very much the problem did happen on the newest version 10 days ago and i did not see there is a new one. Thanks and sorry for the inconveniance.
