### ISSUE TITLE
Error when using the Trans tag with next/link: "Multiple children were passed to <Link>"

### ISSUE THREAD

**Issue by getsnoopy** [i18next/next-i18next#2241]
## 🐛 Bug Report

When using the `<Trans>` tag with `next/link`, `next/link` throws the following error:
```
Error: Multiple children were passed to <Link> with `href` of `/terms-and-conditions` but only one child is supported https://nextjs.org/docs/messages/link-multiple-children Open your browser's console to view the Component stack trace.
```

## To Reproduce

The JSX code I'm using:
```jsx
<Trans t={t} i18nKey="payment.agreement.terms">I agree with the <Link href="/terms-and-conditions">terms &amp; conditions</Link> and the <Link href="/return-policy">return policy</Link>.</Trans>
```

The translation JSON file:
```json
{
    "payment.agreement.terms": "I agree with the <1>terms and conditions</1> and the <3>return policy</3>."
}
```

## Expected behaviour

For this not to happen, and for it to render properly.

It seems like this is happening because `next/link` is running a check on its `children` to see whether there is only 1 child passed in (using [React's `Children.only` function](https://react.dev/reference/react/Children#children-only)), which actually happens to be the case in this instance. However, the implicit second check that it does is that it's a *React*(-extended) element, which is apparently not the case in this instance, but a mere `Array` of a single node in each `<Link>`'s case.

The child (text node in this case) should be passed directly as a plain string (as it is normally when this markup is outside of the `<Trans>` tag), or as an array of children which are React-extended.

## Your Environment

- *runtime version*: Node `v14.21.3`
- *next-i18next version*: `15.1.1`
- *i18next version*: `23.7.9`
- *os*: Linux

**Comment by adrai** [comment]
just tried to reproduce it in this example: https://github.com/i18next/next-i18next/blob/master/examples/simple/pages/index.tsx#L37

<img width="592" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/345a786c-4b01-49cd-a2b2-3833fcf51596">
<img width="468" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/38f76be0-136d-403a-b244-46942761c06a">
<img width="1115" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/b5d6b8e7-f1c0-41d5-86cb-3f7ca814d588">

But I can't see any error

**Comment by getsnoopy** [comment]
Hmm...interesting. I guess the next question I should ask is: which version of Next.js were you running in the demo? I'm running Next.js `12.3.4`.

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/blob/master/examples/simple/package.json#L19

**Comment by Programmer-Dost** [comment]
Is this repo inactive? It have so little engagement

**Comment by adrai** [comment]
> Is this repo inactive? It have so little engagement
> 
> 

Why are you saying this?
Waiting for a minimal reproducible example... 🤷‍♂️

**Comment by Programmer-Dost** [comment]
> > Is this repo inactive? It have so little engagement
> > 
> > 
> 
> Why are you saying this?
> Waiting for a minimal reproducible example... 🤷‍♂️

No I meant there are so many repos in which PR never gets reviewed so I thought if the situation is same in this one.

**Comment by adrai** [comment]
Which PRs are you referring to?
Only some TypeScript related topics are pending because there is no good solution and deeper Ts know-how is necessary... feel free to contribute
