### ISSUE TITLE
Config Setup not working on nextjs

### ISSUE THREAD

**Issue by fxmb** [i18next/next-i18next#2243]
I simply cannot seem to get i18next to run on my system. I follow the **exact** instructions of the setup but when I run this:

```
  const { t, i18n, ready } = useTranslation("checkout")
  console.log( t, i18n, ready)
```

I simply get:

`[Function: notReadyT] {} false`

This is my setup:

**next-i18next.config.js**

```
const path = require("path")

/** @type {import('next-i18next').UserConfig} */
module.exports = {
  i18n: {
    defaultLocale: "de",
    locales: ["en", "de"],
    localePath: path.resolve("./public/locales"),
  },
}
```

**My _app.tsx:**

```
import { appWithTranslation } from "next-i18next"

function App({
  Component,
  pageProps,
}: AppPropsWithLayout<{ dehydratedState?: unknown }>) {
  const getLayout = Component.getLayout ?? ((page) => page)

  return (
                <AccountProvider>
                  {getLayout(<Component {...pageProps} />)}
                </AccountProvider>
  )
}

export default appWithTranslation(App)
```

**My next.config.**

```

const path = require("path")
const { i18n } = require("./next-i18next.config")

module.exports = withStoreConfig({
  i18n,

....
```

**I have my translations in e.g. `/public/locales/de/checkout.json`**

I know this is not a 100% reproducible example, I find it hard to reproduce it in a repo, it simply does not work with above config. I have no idea what is going on and after hours of research I decided to post here.

**I did the following:**
1. I cleared the .next cache => no success
2. I reinstalled all packages => no success

    "next-i18next": "^15.1.1",

Any help would be highly appreciated 🙏

**Comment by adrai** [comment]
Please try to reproduce it based on a simple example like this one: https://github.com/i18next/next-i18next/tree/master/examples/simple
not really able to help without a reproducible example

**Comment by fxmb** [comment]
Yes I did,:

https://github.com/fxmb/replicate-i18n-issue/tree/main

Here I do the import: https://github.com/fxmb/replicate-i18n-issue/blob/main/src/pages/index.tsx#L9

It just logs to the console:

```
XY (k, optsOrDefaultValue) => {
      if (typeof optsOrDefaultValue === 'string') return optsOrDefaultValue;
      if (optsOrDefaultValue && typeof optsOrDefaultValue === 'object' && typeof optsOrDefaul… {} false
```

I have wrapped my App in _app, I import the settings and the path to the locales is correct (I logged it and cd into it).

I must be missing something basic

**Comment by adrai** [comment]
seems you missed the getStaticProps (or getServerSideProps) part: https://github.com/i18next/next-i18next?tab=readme-ov-file#serversidetranslations

<img width="600" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/6f8af989-fc69-4eec-88a8-c33314373781">
