### ISSUE TITLE
Locale is not changing in dynamic route

### ISSUE THREAD

**Issue by gunsela92** [i18next/next-i18next#2246]
## 🐛 Bug Report

I can change the language and see the ctx.locale is changed in getServerSideProps if the page is not dynamic like `pages/test` but if page is dynamic ctx.locale is not changing like `pages/users/[id]`.

I created a reproducable repo. The link is below.

## To Reproduce

[Stackblitz](https://stackblitz.com/edit/nextjs-mnacqm)

## Expected behavior

To see ctx.locale changed

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
https://stackblitz.com/edit/nextjs-yvy23a?file=pages%2Findex.js,pages%2Fusers%2F[id].js
<img width="561" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/446d35be-e4d3-49ea-a859-eb06e3e14ee1">
<img width="650" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/5f396889-c8ed-4571-aca9-91c9d553968e">

**Comment by gunsela92** [comment]
@adrai thanks for response but in stackblitz i did everything same as my project. Unfortunately i cant make it work in my project. Only dynamic pages are the problem. ctx.locale is not changing when the locale changes. It changes only once. Then it doesnt

**Comment by adrai** [comment]
the stackblitz fork example I provided seems to work on every change... so waiting for another reproducible example

**Comment by gunsela92** [comment]
i cant reproduce. it everything is same but its not working in my project lol

**Comment by gunsela92** [comment]
Problem occurs because of custom middleware. I fixed it by removing it. Related issue: [nextjs repo](https://github.com/vercel/next.js/issues/54217)
