### ISSUE TITLE
Hydration error in dynamic route.

### ISSUE THREAD

**Issue by JanMolcik** [i18next/next-i18next#2258]
## 🐛 Bug Report

When navigating to an internationalized dynamic nextjs sub-route (_/en/some-page/[slug]_) manually, or on manual page refresh, there is an issue with [react-hydration-error](https://nextjs.org/docs/messages/react-hydration-error).

## To Reproduce

I have created [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-j8ncfl) to showcase this issue.

1. Go to [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-j8ncfl)
2. Open in New Tab
4. Switch to en (using language switch or by appending _/en_ in url)
5. Navigate to _/en/admin/slug_ page
6. Reload page

Navigation to _/en/admin/slug_ sub-route with `Link` works as expected. However, if you refresh the page or navigate manually (by browser's address bar), I get error :
```
Error: Text content does not match server-rendered HTML.

Warning: Text content did not match. Server: "Invoice" Client: "admin.invoice"

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```
Seems like there is some timing error, on the server it is correctly translated but on the client seems the translation config is missing at the time of rendering. Weird thing is that it does not happen for the default _cs_ language, only for _en_.

## Expected behavior

There should not be the react hydration error.

## Your Environment

- *runtime version*: node v18.17.1, Brave browser version 1.62.156 Chromium: 121.0.6167.139 (Official Build) (x86_64)
- *i18next version*: 23.7.19
- *os*: Mac Sonoma 14.2.1 (23C71)

**Comment by JanMolcik** [comment]
Ok I have used the alternative approach and refactored the example but the issue persists.

_admin/[slug]/index.tsx_ page
```js
import { GetStaticPaths, GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useEffect } from 'react';

// If you go to this page "/en/admin/slug" manually
// (open in New Tab) react hydration error appears
function Admin({ locale }: { locale?: string }) {
  const { t, i18n } = useTranslation('common', {
    bindI18n: 'languageChanged loaded',
  });

  // bindI18n: loaded is needed because of the reloadResources call
  // if all pages use the reloadResources mechanism, the bindI18n option can also be defined in next-i18next.config.js
  useEffect(() => {
    i18n.reloadResources(i18n.resolvedLanguage, 'common');
  }, []);

  return (
    <div className="flex mx-2">
      <span>{t('admin.invoice')}</span>
    </div>
  );
}

export const getStaticPaths: GetStaticPaths = async ({ locales = [] }) => {
  const paths = [
    {
      params: { slug: 'slug' },
    },
  ];
  return {
    paths,
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps = async ({
  locale,
  defaultLocale,
}) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? defaultLocale ?? 'cs', [
        'common',
      ])),
      locale,
    },
  };
};

export default Admin;

```

<img width="1390" alt="image" src="https://github.com/i18next/next-i18next/assets/19672954/929596e6-3b2d-4c5e-b5c8-a4d242a902fb">

**Comment by adrai** [comment]
probably because of the fallback option

**Comment by JanMolcik** [comment]
Unfortunately according to [nextjs documentation](https://nextjs.org/docs/pages/building-your-application/routing/internationalization#dynamic-routes-and-getstaticprops-pages) the fallback option needs to be there for internationalized dynamic routes.

However, I have found that I included the locale into `{ params: { ..., locale } }`, but it should be on the **same level** `{ params: { ... }, locale }`
```ts
export const getStaticPaths: GetStaticPaths = async ({ locales = [] }) => {
  const paths = locales.map((locale) => ({
    params: { slug: 'slug' },
    locale,
  }));
  return {
    paths,
    fallback: true,
  };
};
```

This solved my issue. Thanks for your time and suggestions.

**Comment by khanakia** [comment]
I have the same error but i am not using it locally I have custom routes `/product/[slug]/s/[listingid] `

Both items have different titles but they have the same [slug]=test-123 however the [list-id] is different but still gets error
```
http://localhost:2302/product/test-123/s/lxj8cjuot6uhoek2q9
http://localhost:2302/product/test-123/s/ldjhm1fpqim5q1efwa
```

```
Text content did not match. Server: "Test" Client: "Test11"
```

@JanMolcik  Any solution ?

**Comment by Linuhusainnk** [comment]
Same Issue in static routes also
<img width="1134" alt="Screenshot 2024-05-11 at 6 02 01 PM" src="https://github.com/i18next/next-i18next/assets/80395697/587babe8-bcce-494d-9ea2-fcde3d3a2191">

Any solution

**Comment by KKzLEO** [comment]
There's a crtical bug, why this issue got closed? ISR totally not working on Next14 with i18n-next.

the steps to reproduce
1. navigate url with locale and ISR, like `/zh-CN/[id]`
2. we will see en version of html fisrt, and got cn version when hydrating
3. hydration error

**Comment by monolithed** [comment]
Here's what worked for me:

```diff
import i18next from 'i18next';
import {initReactI18next} from 'react-i18next';
import resourcesToBackend from 'i18next-resources-to-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

const SSR = typeof window === 'undefined';

i18next.isInitialized || i18next
    .use(initReactI18next)
    .use(LanguageDetector)
    .use(resourcesToBackend(loader))
    .init({
+         lng: undefined,
          preload: SSR ? locales : []
    });

```
