### ISSUE TITLE
Translation keys flickering issue under specific language setting logic (example provided)

### ISSUE THREAD

**Issue by Pudge1996** [i18next/next-i18next#2261]
## 💥 Regression Report

Translation keys always appear on the first visit to the website. However, after manually switching languages or navigating to another route, everything works normally.

## Last working version

- next: 13.0.6
- next-i18next: 15.2.0
- i18next: 23.8.2
- react: 18.2.0

### Video

https://github.com/i18next/next-i18next/assets/22073891/df8b1309-97cf-4086-bf2a-f830eef93505

### Repository

https://github.com/Pudge1996/NEXT.LRD.IM/tree/i18Next-min

Or Online

https://next-lrd-ltv0ieztc-pudge1996.vercel.app/

### Key File Paths

My method of setting i18n.changeLanguage: utils/useLanguageSetting.js
My language switcher: components/common/SwitchLanguages
Homepage: pages/index

## Expected behavior

The console does not report "i18next::translator: missingKey", and the flickering of Translation keys does not occur at any time.

### Logic

My multi-language solution is different from the default provided by Next:

- I have set `localeDetection: false` and used a custom Hook useLanguageSetting to set the user's default language (based on the browser language with some processing);
- When retrieving namespaces on the server side, the definition of server language is processed from the Accept-Language in the HTTP headers, to avoid hydration issues between server and client languages.

#### getServerSideProps

I've included the corresponding namespaces in `getServerSideProps`, but this did not help fix the error (file path pages/index):

```
return {
    props: {
      ...(await serverSideTranslations(finalLocale, 'common', nextI18NextConfig)),
    },
  };
```

#### Using `ready`

This did not help fix the error.

```
const Index = () => {
  const { ready } = useTranslation();

  if (!ready) {
    return <div>Loading...</div>;
  }

  return (
      <Project />
  );
};

export default Index;
```

## Your Environment

- next: 13.0.6
- next-i18next: 15.2.0
- i18next: 23.8.2
- react: 18.2.0

**Comment by adrai** [comment]
The backendOptions are wrong: https://github.com/Pudge1996/NEXT.LRD.IM/pull/2

**Comment by Pudge1996** [comment]
> The backendOptions are wrong: [Pudge1996/NEXT.LRD.IM#2](https://github.com/Pudge1996/NEXT.LRD.IM/pull/2)

Sincerely thank you for your help.
Your solution works perfectly in the localhost environment, but surprisingly, the issue reoccurred after deploying on Vercel. Is there any way to solve this?


https://github.com/i18next/next-i18next/assets/22073891/c0d987b7-c3db-45f4-94e4-1eb2c3e581e4

**Comment by adrai** [comment]
Try to add the loadPath like here: https://github.com/i18next/next-i18next/blob/master/examples/simple/next-i18next.config.js#L14

**Comment by Pudge1996** [comment]
> Try to add the loadPath like here: https://github.com/i18next/next-i18next/blob/master/examples/simple/next-i18next.config.js#L14

Thank you for the quick response and direction @adrai! 

This solution works perfectly in any environment.

However, I'm currently facing a dilemma with a page that requires fetching local resources via getStaticProps, which makes it impossible to use getServerSideProps for the same page. 

A typical example is a blog listing page that uses MDX for blog posts, where some static text on the page needs to support multiple languages, while the list of blog posts is fetched using getStaticProps.

Here is the complete code for the blog page in my repository: https://github.com/Pudge1996/NEXT.LRD.IM/blob/2d3089b67d6bec9bf27dde49188dc77b37de012d/pages/blog.js#L126

And here's another page that doesn't use getStaticProps and displays content normally: https://github.com/Pudge1996/NEXT.LRD.IM/blob/2d3089b67d6bec9bf27dde49188dc77b37de012d/pages/index.js#L11
