### ISSUE TITLE
Hydration error when using `lang` option of `t` function

### ISSUE THREAD

**Issue by yamanidev** [i18next/next-i18next#2265]
Hello! I hope you're having a great day. I apologize for asking such a repeating question, I just really couldn't figure out how to solve it.

## 🐛 Bug Report
I am getting the hydration error `Error: Text content does not match server-rendered HTML.` when trying to translate with the `lng` option.

There's a mismatch between text content (translation) between the client and the server, the server having the correct translation, and this only happens when the locale is `en`, it works fine with `fr` locale.

Note: I am importing `useTranslation` from `next-i18next` as I should.

## Expected behavior
I want a piece of text to be in the other language. If the website is in English, this piece of text should be in French, and vice versa:
- When locale is `en`, I want the text to be *Le site web est aussi disponible en Français*.
- When locale is `fr`, I want the text to be *The website is also available in English*.

## To Reproduce
I have created a minimal [codesandbox](https://stackblitz.com/~/github.com/yamanidev/nextjs-hydration-error) for reproduction, or you can check the same code in this [repository](https://github.com/yamanidev/nextjs-hydration-error). Below is the JSX that's causing the error:

```tsx
<p lang="changeTo">
    {t('available_in', { lng: changeTo })}{' '}
    <Link href="/" locale={changeTo}>
        {t(changeTo === 'en' ? 'english' : 'french', { ns: 'language', lang: changeTo })}
    </Link>
</p>
```

Hooks and values used:
```tsx
const { t } = useTranslation('common');
const router = useRouter();
const changeTo = router.locale === 'en' ? 'fr' : 'en';
```

## Your Environment

- *runtime version*: Node v18.7.0
- *i18next version*: 23.10.0
- *os*: Linux (Ubuntu)
- *package manger*: pnpm

**Comment by adrai** [comment]
This means the changeTo variable has a different value on server side and on client side...

**Comment by adrai** [comment]
did not investigate it, but it may be the useRouter call (of next/router) is not returning the same language on server side and on client side

**Comment by yamanidev** [comment]
but it's working fine when the locale is fr (when you navigate to /fr). It's only showing that error for en locale (`/` path). I am using the pages router by the way, so no server components.

is there any way to debug this mismatch? I am clueless

**Comment by adrai** [comment]
condole.log the changeTo variable and check the server output and the browser console output...
You should see 2 different values. This means that page is prerendered on server side...

**Comment by yamanidev** [comment]
I just tried `const changeTo = 'fr'` without using `useRouter()` to determine locale, I am still getting the same hydration error

**Comment by adrai** [comment]
The problem is, you are using the t function with a language that is not loaded in the client.
So you need to do this: https://github.com/i18next/next-i18next?tab=readme-ov-file#5-declaring-locale-dependencies

```diff
export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
-      ...(await serverSideTranslations(locale ?? 'en', ['common', 'language']))
+      ...(await serverSideTranslations(locale ?? 'en', ['common', 'language'], null, ['en', 'fr']))
    }
  };
};
```

**Comment by yamanidev** [comment]
I totally missed that, thank you so much!

**Comment by yamanidev** [comment]
@adrai for the case of `localhost:3000/fr` that didn't raise any errors, was it because the translation in question was using the fallback language `en`, which loads automatically?

**Comment by adrai** [comment]
probably yes
