### ISSUE TITLE
Plugin transformers not applied server-side when App Router present

### ISSUE THREAD

**Issue by dmgawel** [i18next/next-i18next#2266]
## 🐛 Bug Report

When using a plugin via `use` config option, let it be [i18next-icu](https://www.npmjs.com/package/i18next-icu) or [i18next-pseudo](https://www.npmjs.com/package/i18next-pseudo), and when App Router is present in the project, the transformers provided by the plugin are only applied in the browser, causing hydration errors and invalid/incomplete content returned in the HTML initial response.

This is about usage in the Pages Router, I know that `next-i18next` is not meant to be used in the App Router, however, this behaviour makes using `next-i18next` in Pages and adopting App incrementally impossible, if someone relies on post processing.

## To Reproduce

I've created a minimal example repo based on the example website from next-i18next repository: https://github.com/dmgawel/next-i18next-app-plugin-issue

To reproduce:
1. Open dev server (`npm run dev`)
2. Visit home page
3. You'll get hydration errors, in the server console a raw string without processing will be logged

Now, remove the `app/` directory and repeat the steps. No hydration errors and post processing is applied sever-side as well.

## Expected behavior

Existence of App Router should not interfere with `next-i18next` behaviour in Pages Router. Post processing should be applied server side, regardless of whether someone uses App Router or not.

## Your Environment

- *runtime version*: node v20
- *i18next version*: newest
- *os*: Mac

**Comment by adrai** [comment]
You need to pass them in the next-i18next.config.js file (via use option)

**Comment by dmgawel** [comment]
No luck. Reproducible with my example as well:

```
 1 of 1 unhandled error
Server Error
TypeError: Cannot read properties of undefined (reading 'type')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/dawid/Dev/i18next-plugin-issue/node_modules/next-i18next/dist/commonjs/config/createConfig.js (134:14)
Array.some
<anonymous>
createConfig
file:///Users/dawid/Dev/i18next-plugin-issue/node_modules/next-i18next/dist/commonjs/config/createConfig.js (133:175)

[...]
```

**Comment by adrai** [comment]
`const ICU = require('i18next-icu').default || require('i18next-icu')`
