### ISSUE TITLE
import_server is not defined

### ISSUE THREAD

**Issue by slowwriter** [i18next/next-i18next#2271]
<img width="964" alt="Screenshot 2024-04-13 at 15 58 41" src="https://github.com/i18next/next-i18next/assets/89002912/c8c95c69-6de6-4367-9f57-dedbae82040f">

This error only occurs in "next dev --turbo"
- next 14.2.1
- next-international 1.2.4

**Comment by adrai** [comment]
next-international is not next-i18next
