### ISSUE TITLE
Text content does not match server-rendered HTML error with app router

### ISSUE THREAD

**Issue by zshnb** [i18next/next-i18next#2277]
## 🐛 Bug Report
I've follow this [post](https://locize.com/blog/next-app-dir-i18n/) to setup i18n in app router. However when I try to switch language, I got error "Text content does not match server-rendered HTML".
Also I try to add i18n in html title and description, but doesn't work.

## To Reproduce
visit https://www.domainprice.cc/zh and open devtool, in console you will see the error log.
the repo is here: https://github.com/zshnb/domain-price-compare

```js
// see app/[locale]/page.tsx & layout.tsx
```

## Expected behavior

title will change, no error

## Your Environment

- *runtime version*: i.e. node v20, chrome
- *i18next version*: i.e. 23.11.2
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
because of this: https://github.com/zshnb/domain-price-compare/pull/3

**Comment by zshnb** [comment]
> because of this: [zshnb/domain-price-compare#3](https://github.com/zshnb/domain-price-compare/pull/3)

thanks for your pr, yes it fixed the error!
btw, I want title and description in <head> also can i18n, do you know how to do it in i18n-next?
