### ISSUE TITLE
Production root shows 404 while local works fine

### ISSUE THREAD

**Issue by LixingSun** [i18next/next-i18next#2279]
## 🐛 Bug Report

I'm building [my nextjs project](https://github.com/LixingSun/oran-web) refer to this [example](https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example).

The local environment totally works fine, where the `http://localhost:3000` shows in default "en" language as expected. `http://localhost:3000/en` and `http://localhost:3000/zh` also show different content properly.

But after deploying to [the production environment](https://oran.zone/) on Github Pages, the root url shows 404 page not found. But after manually changing the url to `https://oran.zone/en` or `https://oran.zone/zh` it can still show page properly.

## To Reproduce

My Repo: [https://github.com/LixingSun/oran-web](https://github.com/LixingSun/oran-web)
Production Link: [https://oran.zone/](https://oran.zone/)

## Expected behavior

Expect the production can work as local, where https://oran.zone/ can proper show content in the default 'en' language as set, instead of 404.

## Your Environment

- *node version*: 20.13.1
- *react*: 18
- *i18next version*: 23.11.4
- *development os*: Mac

**Comment by adrai** [comment]
i18nexus is not i18next... 
please open the issue in this repository: https://github.com/i18nexus/next-i18n-router
or use the solutions of the official sponsor of i18next: https://locize.com/blog/next-app-dir-i18n/
