### ISSUE TITLE
How to set the default URL language based on the language reserved by the cookie

### ISSUE THREAD

**Issue by JZW-6** [i18next/next-i18next#2280]
## Documentation issue

A clear and concise description of what the issue is.

## Motivation

Please outline the motivation for the proposal.

**Comment by JZW-6** [comment]
http://localhost:3000/{cookie.language || defaultLocale}

**Comment by adrai** [comment]
This is handled by Next.js...
https://nextjs.org/docs/pages/building-your-application/routing/internationalization
<img width="657" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/b476ac76-393b-4a84-a732-c4461588d973">
