### ISSUE TITLE
locales folder names containing language and country

### ISSUE THREAD

**Issue by x1c0** [i18next/next-i18next#2285]
## Documentation issue

Is not clear for me from the docs, how should we use locales folder. As I understood if I have a country with several languages, like Switzerland, I could only make i18n work using `<lowercase language>-<UPPERCASE COUNTRY>`

<img width="203" alt="image" src="https://github.com/i18next/next-i18next/assets/2421483/380cdbb5-7ad1-43f5-9b0d-91fb6498e3ff">

I have a very small repo here: https://codesandbox.io/p/devbox/test-i18n-pglxnm

My question is if this is as indented, or if there is any way of configuring this, since now my urls also look like `/en-CH/...` or `/de-CH/..`
And if this is the default behavior, if is possible to have them in lowercase

Many thanks in advance!

**Comment by adrai** [comment]
currently afk, but try the loweCaseLng option: https://www.i18next.com/overview/configuration-options

![image](https://github.com/i18next/next-i18next/assets/1086194/26321808-df68-4c6d-8ff1-25a2d700d5eb)

**Comment by x1c0** [comment]
@adrai thank you that worked! I guess I need to keep the config file like this right?

```
  i18n: {
    loweCaseLng: true,
    defaultLocale: "en-CH",
    locales: ["en-CH", "de-CH"],
  },
```
will this have any impact on next locale? or the next locale will always be uppercase country?

**Comment by adrai** [comment]
I don't know how Next.js handles lowercase... that might be an issue, since Next.js will do the language detection

**Comment by x1c0** [comment]
@adrai do you have any idea why the translations do not work if the locales folders are lowercase? I updated the codepen https://codesandbox.io/p/devbox/test-i18n-pglxnm

**Comment by adrai** [comment]
currently afk, but I assume it's because Next.js requires them to not be lowercase? https://nextjs.org/docs/pages/building-your-application/routing/internationalization
To exclude an i18next problem, set the debug option to true and check the logs...

**Comment by x1c0** [comment]
no worries, but lets say, AFAIK nextjs only takes care about the locale change and cookie, but the locales folder are required by i18next right? 
```
i18next::backendConnector: loading namespace common for language en-CH failed Error: ENOENT: no such file or directory, open '/project/workspace/public/locales/en-CH/common.json'
    at Object.readFileSync (node:fs:453:20)
    at readFileInNodeSync (/project/workspace/node_modules/i18next-fs-backend/cjs/readFile.js:22:17)
```
and my config is like this
```
module.exports = {
  debug: true,
  loweCaseLng: true,
  i18n: {
    defaultLocale: "en-ch",
    locales: ["en-ch", "de-ch"],
  },
};
```

**Comment by x1c0** [comment]
here I found a comment about this https://github.com/i18next/i18next/issues/1467#issuecomment-646305827 so I guess the rule is, if we have a locale with country, then the folders need to match exactly that. I just wonder why..

**Comment by adrai** [comment]
It's `lowerCaseLng: true` not `loweCaseLng: true`

```diff
++lowerCaseLng: true
--loweCaseLng: true
```

**Comment by x1c0** [comment]
omg how did I miss that, let me try!
