### ISSUE TITLE
Next-Intl shows messages before loading them inside google results

### ISSUE THREAD

**Issue by yonirosenbaum** [i18next/next-i18next#2286]
## 🐛 Bug Report
Messages are crawled by google before the relevant text has been injected ie below 'quiz.general.whatWeDo' should equal 'What do we do'

<img width="508" alt="Screenshot 2024-07-02 at 9 33 38 pm" src="https://github.com/i18next/next-i18next/assets/49931551/83f9693a-aada-40e7-9b11-bd1e363f32de">

I am using i18n routing and have followed the docs: https://next-intl-docs.vercel.app/docs/getting-started/app-router/with-i18n-routing.

Here is the below page that is being affected, note the html is being stripped out and is just appearing as empty space.

### app/[locale]/what-we-do/page.tsx
`
'use client';
import styled from '@emotion/styled';
import { Typography, Button } from '@mui/material';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { css } from '@emotion/react';
import Alert, { AlertPosition, AlertColor } from 'src/components/DataDisplay/Alert';
import { MIN_WIDTH } from 'src/utils/constant';
import { routes } from 'src/utils/routes';
import { useTranslations } from 'next-intl';
import { useEffect } from 'react';

const WhatWeDo = () => {
  const t = useTranslations('quiz.general');
  return (
    <div>
      <div>
        <Typography variant="h2">{t('whatWeDo')}</Typography>
        <Typography>{t('dreamPhotoshoot')}</Typography>
      </div>
      <div position={AlertPosition.Bottom} color={AlertColor.White}>
        <div>
          <Button variant="contained" color="info" onClick={handleContinueClick}>
            {t('continue')}
          </Button>
        </div>
      </div>
    </div>
  );
};

export default WhatWeDo;
`
Here are some other pages which impact the i18n setup

### /app/[locale]/layout
`

const locales = ['en', 'es'];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

type RootLayoutProps = PropsWithChildren & ParamsType;

const RootLayout = async ({ children, params }: RootLayoutProps) => {
  const messages = await getMessages();
  return (
    <html lang={params.locale || 'en'}>
      <body>
            <NextIntlClientProvider locale={params.locale} messages={messages}>
              <ClientProviders>{children}</ClientProviders>
            </NextIntlClientProvider>
      </body>
    </html>
  );
};
`
### src/i18n.ts
`
import {notFound} from 'next/navigation';
import {getRequestConfig} from 'next-intl/server';
 
// Can be imported from a shared config
const locales = ['en', 'es'];
 
export default getRequestConfig(async ({locale}) => {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale as any)) notFound();
 
  return {
    messages: (await import(`../messages/${locale}.json`)).default
  };
});
`
### src/middleware.ts
`
import createMiddleware from 'next-intl/middleware';
 
export default createMiddleware({
  // A list of all locales that are supported
  locales: ['en', 'es'],
 
  // Used when no locale matches
  defaultLocale: 'en'
});
 
export const config = {
  // Match only internationalized pathnames
  matcher: ['/', '/(es|en)/:path*']
};
`

## Your Environment

- *runtime version*: i.e. node v20
- *i18next version*: i.e. 3.15.2
- *os*: Mac

**Comment by adrai** [comment]
This is the repo for next-i18next, not for next-intl...
