### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by crackAsmiles** [i18next/next-i18next#2302]
index.js?1ad7:687 Uncaught SyntaxError: Unexpected token '=' at Object../node_modules/.pnpm/[react-i18next@15.0.2_i18next](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@[23.15.2_react-dom@18.0.0_react](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@18.0.0/node_modules/react-i18next/dist/es/context.js (_app.js:3465) at Object.options.factory (webpack.js:675) at webpack_require (webpack.js:37) at fn (webpack.js:330) at eval (VM1851 Trans.js:8) at Module../node_modules/.pnpm/[react-i18next@15.0.2_i18next](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@[23.15.2_react-dom@18.0.0_react](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@18.0.0/node_modules/react-i18next/dist/es/Trans.js (_app.js:3432) at Module.options.factory (webpack.js:675) at webpack_require (webpack.js:37) at fn (webpack.js:330) at eval (VM1850 index.js:26) at Module../node_modules/.pnpm/[react-i18next@15.0.2_i18next](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@[23.15.2_react-dom@18.0.0_react](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@18.0.0/node_modules/react-i18next/dist/es/index.js (_app.js:3498) at Module.options.factory (webpack.js:675) at webpack_require (webpack.js:37) at fn (webpack.js:330) at eval (VM1849 index.js:11) at Module../node_modules/.pnpm/[next-i18next@15.3.1_i18next](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@[23.15.2_next@14.1.3_react-i18next](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)@[15.0.2_react@18.0.0](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/next-i18next/dist/esm/index.js (_app.js:72) at Module.options.factory (webpack.js:675) at webpack_require (webpack.js:37) at fn (webpack.js:330) at eval (_app.tsx:8) at Module../src/pages/_app.tsx (_app.js:2827) at Module.options.factory (webpack.js:675) at webpack_require (webpack.js:37) at fn (webpack.js:330) at eval (?7952:5) at eval (route-loader.js?2cce:234)

## 🐛 Bug Report

I encountered this issue in an Android WebView. How can I resolve it?

## Your Environment
- nextjs  14.1.3
- next-i18next 15.3.1
- os Android System WebView 83.0.4103.106 (arm64-v8a + arm-v7a) (Android 5.0+)

**Comment by adrai** [comment]
Does it work with react-i18next <  15

**Comment by crackAsmiles** [comment]
When i use next-i18next  < 12.1.0 it work, but not work 15

**Comment by adrai** [comment]
can you keep next-i18next on v15.3.1
and react-i18next on v14.1.3

**Comment by adrai** [comment]
//cc @VIKTORVAV99

**Comment by adrai** [comment]
I suspect it's this line: https://github.com/i18next/react-i18next/commit/926baf49d5024fddb33a2b4150111fa47cb2f7c4#diff-f00be3776778d4a72e4f0720b43138c8a7f09e508f31a1987b8952410b315518R17

**Comment by VIKTORVAV99** [comment]
You should be transpiling your code or pinning the dependencies to support older versions of browsers. This is not a library or package issue IMO.

**Comment by adrai** [comment]
> can you keep next-i18next on v15.3.1 and react-i18next on v14.1.3

@crackAsmiles out of curiosity, can you also try with react-i18next v15.0.3
